<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Lab 8 Repeated Measures ANOVA | Answering questions with data: Lab Manual</title>
  <meta name="description" content="A lab manual for Psyc 292 at StFX" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Lab 8 Repeated Measures ANOVA | Answering questions with data: Lab Manual" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A lab manual for Psyc 292 at StFX" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Lab 8 Repeated Measures ANOVA | Answering questions with data: Lab Manual" />
  
  <meta name="twitter:description" content="A lab manual for Psyc 292 at StFX" />
  

<meta name="author" content="Matthew J. C. Crump, Anjali Krishnan, Stephen Volz, and Alla Chavarga" />
<meta name="author" content="Adapted for PSYC 292, St. Francis Xavier University, by Erin L. Mazerolle, Sherry Neville-MacLean, Christine D. Lomore, and Margaret Vail." />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lab-7-one-way-anova.html"/>
<link rel="next" href="lab-9-factorial-anova.html"/>
<script src="libs/header-attrs-2.17/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-79429674-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-79429674-4');
</script>


<script type="text/javascript">
mattcrump=1;
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="tufte.css" type="text/css" />
<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics Lab Manual</a></li>

<li class="divider"></li>
<li><a href="index.html#preface" id="toc-preface">Preface</a>
<ul>
<li><a href="index.html#important-notes" id="toc-important-notes"><span class="toc-section-number">0.1</span> Important notes</a>
<ul>
<li><a href="index.html#attributions-and-versions" id="toc-attributions-and-versions"><span class="toc-section-number">0.1.1</span> Attributions and Versions</a></li>
<li><a href="index.html#cc-by-sa-4.0-license" id="toc-cc-by-sa-4.0-license"><span class="toc-section-number">0.1.2</span> CC BY-SA 4.0 license</a></li>
<li><a href="index.html#copying-the-lab-manual" id="toc-copying-the-lab-manual"><span class="toc-section-number">0.1.3</span> Copying the lab manual</a></li>
<li><a href="index.html#acknowledgments" id="toc-acknowledgments"><span class="toc-section-number">0.1.4</span> Acknowledgments</a></li>
</ul></li>
<li><a href="index.html#data" id="toc-data"><span class="toc-section-number">0.2</span> Data</a>
<ul>
<li><a href="index.html#data-repository" id="toc-data-repository"><span class="toc-section-number">0.2.1</span> Data Repository</a></li>
<li><a href="index.html#csv-format" id="toc-csv-format"><span class="toc-section-number">0.2.2</span> CSV format</a></li>
<li><a href="index.html#spss-format" id="toc-spss-format"><span class="toc-section-number">0.2.3</span> SPSS format</a></li>
</ul></li>
<li><a href="index.html#r" id="toc-r"><span class="toc-section-number">0.3</span> R</a>
<ul>
<li><a href="index.html#why-r" id="toc-why-r"><span class="toc-section-number">0.3.1</span> Why R?</a></li>
<li><a href="index.html#installing-r-and-r-studio" id="toc-installing-r-and-r-studio"><span class="toc-section-number">0.3.2</span> Installing R and R Studio</a></li>
<li><a href="index.html#r-studio-notes-and-tips" id="toc-r-studio-notes-and-tips"><span class="toc-section-number">0.3.3</span> R studio notes and tips</a></li>
<li><a href="index.html#how-to-complete-the-r-labs" id="toc-how-to-complete-the-r-labs"><span class="toc-section-number">0.3.4</span> How to complete the R Labs</a></li>
<li><a href="index.html#screencast-tutorial" id="toc-screencast-tutorial"><span class="toc-section-number">0.3.5</span> Screencast tutorial</a></li>
<li><a href="index.html#r-studio-cloud" id="toc-r-studio-cloud"><span class="toc-section-number">0.3.6</span> R-studio Cloud</a></li>
</ul></li>
<li><a href="index.html#excel" id="toc-excel"><span class="toc-section-number">0.4</span> Excel</a></li>
<li><a href="index.html#spss" id="toc-spss"><span class="toc-section-number">0.5</span> SPSS</a>
<ul>
<li><a href="index.html#installing-spss" id="toc-installing-spss"><span class="toc-section-number">0.5.1</span> Installing SPSS</a></li>
<li><a href="index.html#notes-and-tips" id="toc-notes-and-tips"><span class="toc-section-number">0.5.2</span> Notes and Tips</a></li>
<li><a href="index.html#opening-spss-and-the-spss-layout" id="toc-opening-spss-and-the-spss-layout"><span class="toc-section-number">0.5.3</span> Opening SPSS and the SPSS layout</a></li>
<li><a href="index.html#practice-problems" id="toc-practice-problems"><span class="toc-section-number">0.5.4</span> Practice Problems</a></li>
</ul></li>
<li><a href="index.html#jamovi---week-2---january-25-26" id="toc-jamovi---week-2---january-25-26"><span class="toc-section-number">0.6</span> JAMOVI - Week 2 - January 25 &amp; 26</a>
<ul>
<li><a href="index.html#getting-started-with-jamovi" id="toc-getting-started-with-jamovi"><span class="toc-section-number">0.6.1</span> Getting Started with jamovi</a></li>
<li><a href="index.html#analyses" id="toc-analyses"><span class="toc-section-number">0.6.2</span> Analyses</a></li>
<li><a href="index.html#the-spreadsheet" id="toc-the-spreadsheet"><span class="toc-section-number">0.6.3</span> The Spreadsheet</a></li>
<li><a href="index.html#loading-data-in-jamovi" id="toc-loading-data-in-jamovi"><span class="toc-section-number">0.6.4</span> Loading Data in jamovi</a></li>
<li><a href="index.html#importing-unusual-data-files" id="toc-importing-unusual-data-files"><span class="toc-section-number">0.6.5</span> Importing Unusual Data Files</a></li>
<li><a href="index.html#changing-data-from-one-level-to-another" id="toc-changing-data-from-one-level-to-another"><span class="toc-section-number">0.6.6</span> Changing Data from One Level to Another</a></li>
<li><a href="index.html#installing-add-on-modules-into-jamovi" id="toc-installing-add-on-modules-into-jamovi"><span class="toc-section-number">0.6.7</span> Installing Add-on Modules into jamovi</a></li>
<li><a href="index.html#quitting-jamovi" id="toc-quitting-jamovi"><span class="toc-section-number">0.6.8</span> Quitting jamovi</a></li>
<li><a href="index.html#summary" id="toc-summary"><span class="toc-section-number">0.6.9</span> Summary</a></li>
</ul></li>
</ul></li>
<li><a href="lab-1-graphing-data.html#lab-1-graphing-data" id="toc-lab-1-graphing-data"><span class="toc-section-number">1</span> Lab 1: Graphing Data</a>
<ul>
<li><a href="lab-1-graphing-data.html#general-goals" id="toc-general-goals"><span class="toc-section-number">1.1</span> General Goals</a>
<ul>
<li><a href="lab-1-graphing-data.html#important-info" id="toc-important-info"><span class="toc-section-number">1.1.1</span> Important info</a></li>
</ul></li>
<li><a href="lab-1-graphing-data.html#r-1" id="toc-r-1"><span class="toc-section-number">1.2</span> R</a>
<ul>
<li><a href="lab-1-graphing-data.html#download-the-lab-templates" id="toc-download-the-lab-templates"><span class="toc-section-number">1.2.1</span> Download the lab templates</a></li>
<li><a href="lab-1-graphing-data.html#get-some-data" id="toc-get-some-data"><span class="toc-section-number">1.2.2</span> Get some data</a></li>
<li><a href="lab-1-graphing-data.html#look-at-the-data" id="toc-look-at-the-data"><span class="toc-section-number">1.2.3</span> Look at the data</a></li>
<li><a href="lab-1-graphing-data.html#make-plots-to-answer-questions" id="toc-make-plots-to-answer-questions"><span class="toc-section-number">1.2.4</span> Make Plots to answer questions</a></li>
<li><a href="lab-1-graphing-data.html#ggplot2-basics" id="toc-ggplot2-basics"><span class="toc-section-number">1.2.5</span> ggplot2 basics</a></li>
<li><a href="lab-1-graphing-data.html#more-questions-about-nyc-films" id="toc-more-questions-about-nyc-films"><span class="toc-section-number">1.2.6</span> More questions about NYC films</a></li>
<li><a href="lab-1-graphing-data.html#gapminder-data" id="toc-gapminder-data"><span class="toc-section-number">1.2.7</span> Gapminder Data</a></li>
<li><a href="lab-1-graphing-data.html#asking-questions-with-the-gap-minder-data" id="toc-asking-questions-with-the-gap-minder-data"><span class="toc-section-number">1.2.8</span> Asking Questions with the gap minder data</a></li>
<li><a href="lab-1-graphing-data.html#generalization-exercise" id="toc-generalization-exercise"><span class="toc-section-number">1.2.9</span> Generalization Exercise</a></li>
<li><a href="lab-1-graphing-data.html#writing-assignment" id="toc-writing-assignment"><span class="toc-section-number">1.2.10</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-1-graphing-data.html#excel-1" id="toc-excel-1"><span class="toc-section-number">1.3</span> Excel</a></li>
<li><a href="lab-1-graphing-data.html#spss-1" id="toc-spss-1"><span class="toc-section-number">1.4</span> SPSS</a>
<ul>
<li><a href="lab-1-graphing-data.html#opening-spss-and-the-spss-layout-1" id="toc-opening-spss-and-the-spss-layout-1"><span class="toc-section-number">1.4.1</span> Opening SPSS and the SPSS layout</a></li>
<li><a href="lab-1-graphing-data.html#reviewing-variable-properties-and-the-variable-view-tab-1" id="toc-reviewing-variable-properties-and-the-variable-view-tab-1"><span class="toc-section-number">1.4.2</span> Reviewing variable properties and the Variable View tab</a></li>
<li><a href="lab-1-graphing-data.html#opening-a-data-file-and-producing-different-types-of-graphs" id="toc-opening-a-data-file-and-producing-different-types-of-graphs"><span class="toc-section-number">1.4.3</span> Opening a data file and producing different types of graphs</a></li>
<li><a href="lab-1-graphing-data.html#homework" id="toc-homework"><span class="toc-section-number">1.4.4</span> Homework</a></li>
</ul></li>
<li><a href="lab-1-graphing-data.html#jamovi---week-3---february-1-2" id="toc-jamovi---week-3---february-1-2"><span class="toc-section-number">1.5</span> JAMOVI - Week 3 - February 1 &amp; 2</a>
<ul>
<li><a href="lab-1-graphing-data.html#opening-jamovi-and-reviewing-the-jamovi-layout" id="toc-opening-jamovi-and-reviewing-the-jamovi-layout"><span class="toc-section-number">1.5.1</span> Opening jamovi and reviewing the jamovi layout</a></li>
<li><a href="lab-1-graphing-data.html#reviewing-variable-properties-and-the-setup-button" id="toc-reviewing-variable-properties-and-the-setup-button"><span class="toc-section-number">1.5.2</span> Reviewing variable properties and the Setup button</a></li>
<li><a href="lab-1-graphing-data.html#importing-a-data-file" id="toc-importing-a-data-file"><span class="toc-section-number">1.5.3</span> Importing a data file</a></li>
<li><a href="lab-1-graphing-data.html#graphs" id="toc-graphs"><span class="toc-section-number">1.5.4</span> Graphs</a></li>
<li><a href="lab-1-graphing-data.html#homework-1" id="toc-homework-1"><span class="toc-section-number">1.5.5</span> Homework</a></li>
<li><a href="lab-1-graphing-data.html#thinking-about-data---practice-questions" id="toc-thinking-about-data---practice-questions"><span class="toc-section-number">1.5.6</span> Thinking about Data - Practice Questions</a></li>
</ul></li>
</ul></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#lab-2-descriptive-statistics-and-more-graphs" id="toc-lab-2-descriptive-statistics-and-more-graphs"><span class="toc-section-number">2</span> Lab 2: Descriptive Statistics (and more graphs)</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#general-goals-1" id="toc-general-goals-1"><span class="toc-section-number">2.1</span> General Goals</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#important-info-1" id="toc-important-info-1"><span class="toc-section-number">2.1.1</span> Important info</a></li>
</ul></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#r-2" id="toc-r-2"><span class="toc-section-number">2.2</span> R</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#descriptives-basics-in-r" id="toc-descriptives-basics-in-r"><span class="toc-section-number">2.2.1</span> Descriptives basics in R</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#central-tendency" id="toc-central-tendency"><span class="toc-section-number">2.2.2</span> Central Tendency</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#variation" id="toc-variation"><span class="toc-section-number">2.2.3</span> Variation</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#descriptives-by-conditions" id="toc-descriptives-by-conditions"><span class="toc-section-number">2.2.4</span> Descriptives by conditions</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#describing-gapminder" id="toc-describing-gapminder"><span class="toc-section-number">2.2.5</span> Describing gapminder</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#generalization-exercise-1" id="toc-generalization-exercise-1"><span class="toc-section-number">2.2.6</span> Generalization Exercise</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#writing-assignment-1" id="toc-writing-assignment-1"><span class="toc-section-number">2.2.7</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#excel-2" id="toc-excel-2"><span class="toc-section-number">2.3</span> Excel</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#spss-2" id="toc-spss-2"><span class="toc-section-number">2.4</span> SPSS</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#calculating-descriptive-statistics" id="toc-calculating-descriptive-statistics"><span class="toc-section-number">2.4.1</span> Calculating Descriptive Statistics</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#descriptive-statistics-and-histograms" id="toc-descriptive-statistics-and-histograms"><span class="toc-section-number">2.4.2</span> Descriptive Statistics and Histograms</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#editing-graphs" id="toc-editing-graphs"><span class="toc-section-number">2.4.3</span> Editing graphs</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#boxplots" id="toc-boxplots"><span class="toc-section-number">2.4.4</span> Boxplots</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#homework-2" id="toc-homework-2"><span class="toc-section-number">2.4.5</span> Homework</a></li>
</ul></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#jamovi---week-4---february-8-9" id="toc-jamovi---week-4---february-8-9"><span class="toc-section-number">2.5</span> JAMOVI - Week 4 - February 8 &amp; 9</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#pre-lab-tasks" id="toc-pre-lab-tasks"><span class="toc-section-number">2.5.1</span> Pre-lab tasks</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#the-basics" id="toc-the-basics"><span class="toc-section-number">2.5.2</span> The basics</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#calculating-descriptive-statistics-1" id="toc-calculating-descriptive-statistics-1"><span class="toc-section-number">2.5.3</span> Calculating Descriptive Statistics</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#descriptive-statistics-and-graphs" id="toc-descriptive-statistics-and-graphs"><span class="toc-section-number">2.5.4</span> Descriptive Statistics and Graphs</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#selecting-the-appropriate-descriptive-statistics" id="toc-selecting-the-appropriate-descriptive-statistics"><span class="toc-section-number">2.5.5</span> Selecting the appropriate descriptive statistics</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#boxplots-1" id="toc-boxplots-1"><span class="toc-section-number">2.5.6</span> Boxplots</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#editing-graphs-1" id="toc-editing-graphs-1"><span class="toc-section-number">2.5.7</span> Editing graphs</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#homework-3" id="toc-homework-3"><span class="toc-section-number">2.5.8</span> Homework</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#practice-questions" id="toc-practice-questions"><span class="toc-section-number">2.5.9</span> Practice Questions</a></li>
</ul></li>
</ul></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#lab-3-sampling-and-sampling-distributions" id="toc-lab-3-sampling-and-sampling-distributions"><span class="toc-section-number">3</span> Lab 3: Sampling and Sampling Distributions</a>
<ul>
<li><a href="lab-3-sampling-and-sampling-distributions.html#r-3" id="toc-r-3"><span class="toc-section-number">3.1</span> R</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#excel-3" id="toc-excel-3"><span class="toc-section-number">3.2</span> Excel</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#spss-3" id="toc-spss-3"><span class="toc-section-number">3.3</span> SPSS</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#jamovi---week-7---march-8-9" id="toc-jamovi---week-7---march-8-9"><span class="toc-section-number">3.4</span> JAMOVI - Week 7 - March 8 &amp; 9</a>
<ul>
<li><a href="lab-3-sampling-and-sampling-distributions.html#learning-objectives" id="toc-learning-objectives"><span class="toc-section-number">3.4.1</span> Learning Objectives</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#pre-lab-tasks-1" id="toc-pre-lab-tasks-1"><span class="toc-section-number">3.4.2</span> Pre-lab tasks</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#the-impact-of-sampling-on-research-results" id="toc-the-impact-of-sampling-on-research-results"><span class="toc-section-number">3.4.3</span> The impact of sampling on research results</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#other-types-of-filters" id="toc-other-types-of-filters"><span class="toc-section-number">3.4.4</span> Other types of filters</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#homework-problems" id="toc-homework-problems"><span class="toc-section-number">3.4.5</span> Homework Problems</a></li>
</ul></li>
</ul></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#lab-4-t-test-one-sample-paired-sample" id="toc-lab-4-t-test-one-sample-paired-sample"><span class="toc-section-number">4</span> Lab 4: t-Test (one-sample, paired sample)</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#intro-material-for-r-and-spss-activities" id="toc-intro-material-for-r-and-spss-activities"><span class="toc-section-number">4.1</span> Intro material for R and SPSS activities</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#does-music-convey-social-information-to-infants" id="toc-does-music-convey-social-information-to-infants"><span class="toc-section-number">4.1.1</span> Does Music Convey Social Information to Infants?</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#lab-skills-learned" id="toc-lab-skills-learned"><span class="toc-section-number">4.1.2</span> Lab skills learned</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#important-stuff" id="toc-important-stuff"><span class="toc-section-number">4.1.3</span> Important Stuff</a></li>
</ul></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#r-4" id="toc-r-4"><span class="toc-section-number">4.2</span> R</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#loading-the-data" id="toc-loading-the-data"><span class="toc-section-number">4.2.1</span> Loading the data</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#inspect-the-data-frame" id="toc-inspect-the-data-frame"><span class="toc-section-number">4.2.2</span> Inspect the data frame</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#get-the-data-for-experiment-one" id="toc-get-the-data-for-experiment-one"><span class="toc-section-number">4.2.3</span> Get the data for Experiment one</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#baseline-phase-conduct-a-one-sample-t-test" id="toc-baseline-phase-conduct-a-one-sample-t-test"><span class="toc-section-number">4.2.4</span> Baseline phase: Conduct a one sample <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#test-phase" id="toc-test-phase"><span class="toc-section-number">4.2.5</span> Test phase</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#paired-samples-t-test" id="toc-paired-samples-t-test"><span class="toc-section-number">4.2.6</span> Paired-samples <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#graphing-the-findings" id="toc-graphing-the-findings"><span class="toc-section-number">4.2.7</span> Graphing the findings</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#data-simulation" id="toc-data-simulation"><span class="toc-section-number">4.2.8</span> Data-simulation</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#generalization-exercise-2" id="toc-generalization-exercise-2"><span class="toc-section-number">4.2.9</span> Generalization Exercise</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#writing-assignment-2" id="toc-writing-assignment-2"><span class="toc-section-number">4.2.10</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#excel-4" id="toc-excel-4"><span class="toc-section-number">4.3</span> Excel</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#spss-4" id="toc-spss-4"><span class="toc-section-number">4.4</span> SPSS</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#experiment-background" id="toc-experiment-background"><span class="toc-section-number">4.4.1</span> Experiment Background</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#optional-performing-a-one-sample-t-test" id="toc-optional-performing-a-one-sample-t-test"><span class="toc-section-number">4.4.2</span> OPTIONAL: Performing a one sample <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-paired-samples-t-test" id="toc-performing-a-paired-samples-t-test"><span class="toc-section-number">4.4.3</span> Performing a paired-samples <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#graphing-your-results" id="toc-graphing-your-results"><span class="toc-section-number">4.4.4</span> Graphing your results</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#optional-the-relationship-between-the-one-sample-and-the-paired-samples-t-test" id="toc-optional-the-relationship-between-the-one-sample-and-the-paired-samples-t-test"><span class="toc-section-number">4.4.5</span> OPTIONAL: The relationship between the one-sample and the paired-samples <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#using-descriptive-statistics-to-give-context-to-inferential-statistics" id="toc-using-descriptive-statistics-to-give-context-to-inferential-statistics"><span class="toc-section-number">4.4.6</span> Using descriptive statistics to give context to inferential statistics</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#lab-homework-6" id="toc-lab-homework-6"><span class="toc-section-number">4.4.7</span> Lab Homework #6</a></li>
</ul></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#jamovi---week-8---march-15-16" id="toc-jamovi---week-8---march-15-16"><span class="toc-section-number">4.5</span> JAMOVI - Week 8 - March 15 &amp; 16</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#learning-objectives-1" id="toc-learning-objectives-1"><span class="toc-section-number">4.5.1</span> Learning Objectives</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#pre-lab-tasks-2" id="toc-pre-lab-tasks-2"><span class="toc-section-number">4.5.2</span> Pre-lab Tasks</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#research-context-for-data-set" id="toc-research-context-for-data-set"><span class="toc-section-number">4.5.3</span> Research Context for Data Set</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-paired-samples-t-test-1" id="toc-performing-a-paired-samples-t-test-1"><span class="toc-section-number">4.5.4</span> Performing a Paired-Samples <em>t</em>-Test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#writing-results-in-apa-format" id="toc-writing-results-in-apa-format"><span class="toc-section-number">4.5.5</span> Writing results in APA format</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-one-sample-t-test" id="toc-performing-a-one-sample-t-test"><span class="toc-section-number">4.5.6</span> Performing a one-sample <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#homework-questions" id="toc-homework-questions"><span class="toc-section-number">4.5.7</span> Homework Questions</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#practice-questions-1" id="toc-practice-questions-1"><span class="toc-section-number">4.5.8</span> Practice Questions</a></li>
</ul></li>
</ul></li>
<li><a href="lab-5-t-test-independent-sample.html#lab-5-t-test-independent-sample" id="toc-lab-5-t-test-independent-sample"><span class="toc-section-number">5</span> Lab 5: <em>t</em>-test (Independent Sample)</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#do-you-come-across-as-smarter-when-people-read-what-you-say-or-hear-what-you-say" id="toc-do-you-come-across-as-smarter-when-people-read-what-you-say-or-hear-what-you-say"><span class="toc-section-number">5.1</span> Do you come across as smarter when people read what you say or hear what you say?</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#study-description-1" id="toc-study-description-1"><span class="toc-section-number">5.1.1</span> STUDY DESCRIPTION</a></li>
</ul></li>
<li><a href="lab-5-t-test-independent-sample.html#lab-skills-learned-1" id="toc-lab-skills-learned-1"><span class="toc-section-number">5.2</span> Lab skills learned</a></li>
<li><a href="lab-5-t-test-independent-sample.html#important-stuff-1" id="toc-important-stuff-1"><span class="toc-section-number">5.3</span> Important Stuff</a></li>
<li><a href="lab-5-t-test-independent-sample.html#r-5" id="toc-r-5"><span class="toc-section-number">5.4</span> R</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#load-the-data" id="toc-load-the-data"><span class="toc-section-number">5.4.1</span> Load the data</a></li>
<li><a href="lab-5-t-test-independent-sample.html#inspect-data-frame" id="toc-inspect-data-frame"><span class="toc-section-number">5.4.2</span> Inspect data frame</a></li>
<li><a href="lab-5-t-test-independent-sample.html#find-the-data-you-need" id="toc-find-the-data-you-need"><span class="toc-section-number">5.4.3</span> Find the data you need</a></li>
<li><a href="lab-5-t-test-independent-sample.html#look-at-the-dependent-variable." id="toc-look-at-the-dependent-variable."><span class="toc-section-number">5.4.4</span> Look at the dependent variable.</a></li>
<li><a href="lab-5-t-test-independent-sample.html#conduct-independent-samples-t-test" id="toc-conduct-independent-samples-t-test"><span class="toc-section-number">5.4.5</span> Conduct Independent samples <em>t</em>-test</a></li>
<li><a href="lab-5-t-test-independent-sample.html#remaining-ratings" id="toc-remaining-ratings"><span class="toc-section-number">5.4.6</span> Remaining ratings</a></li>
<li><a href="lab-5-t-test-independent-sample.html#reconstructing-the-graph-from-the-paper" id="toc-reconstructing-the-graph-from-the-paper"><span class="toc-section-number">5.4.7</span> Reconstructing the graph from the paper</a></li>
<li><a href="lab-5-t-test-independent-sample.html#generalization-exercise-3" id="toc-generalization-exercise-3"><span class="toc-section-number">5.4.8</span> Generalization Exercise</a></li>
<li><a href="lab-5-t-test-independent-sample.html#writing-assignment-3" id="toc-writing-assignment-3"><span class="toc-section-number">5.4.9</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-5-t-test-independent-sample.html#excel-5" id="toc-excel-5"><span class="toc-section-number">5.5</span> Excel</a></li>
<li><a href="lab-5-t-test-independent-sample.html#spss-5" id="toc-spss-5"><span class="toc-section-number">5.6</span> SPSS</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#experiment-background-1" id="toc-experiment-background-1"><span class="toc-section-number">5.6.1</span> Experiment Background</a></li>
<li><a href="lab-5-t-test-independent-sample.html#performing-an-independent-samples-t-test" id="toc-performing-an-independent-samples-t-test"><span class="toc-section-number">5.6.2</span> Performing an independent-samples <em>t</em>-test</a></li>
<li><a href="lab-5-t-test-independent-sample.html#graphing-your-data" id="toc-graphing-your-data"><span class="toc-section-number">5.6.3</span> Graphing your data</a></li>
<li><a href="lab-5-t-test-independent-sample.html#optional-activities" id="toc-optional-activities"><span class="toc-section-number">5.6.4</span> Optional activities</a></li>
<li><a href="lab-5-t-test-independent-sample.html#lab-homework-7" id="toc-lab-homework-7"><span class="toc-section-number">5.6.5</span> Lab Homework #7</a></li>
<li><a href="lab-5-t-test-independent-sample.html#example-answers-to-practice-problems" id="toc-example-answers-to-practice-problems"><span class="toc-section-number">5.6.6</span> Example answers to practice problems</a></li>
</ul></li>
<li><a href="lab-5-t-test-independent-sample.html#jamovi---week-9---march-22-23" id="toc-jamovi---week-9---march-22-23"><span class="toc-section-number">5.7</span> JAMOVI - Week 9 - March 22 &amp; 23</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#pre-lab-reading-and-tasks" id="toc-pre-lab-reading-and-tasks"><span class="toc-section-number">5.7.1</span> Pre-lab reading and tasks</a></li>
<li><a href="lab-5-t-test-independent-sample.html#performing-an-independent-samples-t-test-1" id="toc-performing-an-independent-samples-t-test-1"><span class="toc-section-number">5.7.2</span> Performing an independent-samples <em>t</em>-test</a></li>
<li><a href="lab-5-t-test-independent-sample.html#some-apa-formatting-reminders-for-writing-results-sections" id="toc-some-apa-formatting-reminders-for-writing-results-sections"><span class="toc-section-number">5.7.3</span> Some APA formatting reminders for writing results sections</a></li>
<li><a href="lab-5-t-test-independent-sample.html#graphing-your-data-1" id="toc-graphing-your-data-1"><span class="toc-section-number">5.7.4</span> Graphing your data</a></li>
<li><a href="lab-5-t-test-independent-sample.html#optional-exercises" id="toc-optional-exercises"><span class="toc-section-number">5.7.5</span> Optional exercises</a></li>
<li><a href="lab-5-t-test-independent-sample.html#lab-homework-7-1" id="toc-lab-homework-7-1"><span class="toc-section-number">5.7.6</span> Lab Homework #7</a></li>
<li><a href="lab-5-t-test-independent-sample.html#practice-problems-1" id="toc-practice-problems-1"><span class="toc-section-number">5.7.7</span> Practice Problems</a></li>
</ul></li>
</ul></li>
<li><a href="lab-6-correlation.html#lab-6-correlation" id="toc-lab-6-correlation"><span class="toc-section-number">6</span> Lab 6: Correlation</a>
<ul>
<li><a href="lab-6-correlation.html#general-goals-2" id="toc-general-goals-2"><span class="toc-section-number">6.1</span> General Goals</a>
<ul>
<li><a href="lab-6-correlation.html#important-info-2" id="toc-important-info-2"><span class="toc-section-number">6.1.1</span> Important Info</a></li>
</ul></li>
<li><a href="lab-6-correlation.html#r-6" id="toc-r-6"><span class="toc-section-number">6.2</span> R</a>
<ul>
<li><a href="lab-6-correlation.html#cor-for-correlation" id="toc-cor-for-correlation"><span class="toc-section-number">6.2.1</span> cor for correlation</a></li>
<li><a href="lab-6-correlation.html#world-happiness-report" id="toc-world-happiness-report"><span class="toc-section-number">6.2.2</span> World Happiness Report</a></li>
<li><a href="lab-6-correlation.html#generalization-exercise-4" id="toc-generalization-exercise-4"><span class="toc-section-number">6.2.3</span> Generalization Exercise</a></li>
<li><a href="lab-6-correlation.html#writing-assignment-4" id="toc-writing-assignment-4"><span class="toc-section-number">6.2.4</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-6-correlation.html#excel-6" id="toc-excel-6"><span class="toc-section-number">6.3</span> Excel</a></li>
<li><a href="lab-6-correlation.html#spss-6" id="toc-spss-6"><span class="toc-section-number">6.4</span> SPSS</a>
<ul>
<li><a href="lab-6-correlation.html#correlation-coefficient-for-bivariate-data-two-variables" id="toc-correlation-coefficient-for-bivariate-data-two-variables"><span class="toc-section-number">6.4.1</span> Correlation Coefficient for Bivariate Data: Two Variables</a></li>
<li><a href="lab-6-correlation.html#correlation-matrix" id="toc-correlation-matrix"><span class="toc-section-number">6.4.2</span> Correlation Matrix</a></li>
<li><a href="lab-6-correlation.html#correlation-and-scatterplots" id="toc-correlation-and-scatterplots"><span class="toc-section-number">6.4.3</span> Correlation and Scatterplots</a></li>
<li><a href="lab-6-correlation.html#splitting-a-file" id="toc-splitting-a-file"><span class="toc-section-number">6.4.4</span> Splitting a File</a></li>
<li><a href="lab-6-correlation.html#practice-problems-2" id="toc-practice-problems-2"><span class="toc-section-number">6.4.5</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-6-correlation.html#jamovi---week-10---march-29-30" id="toc-jamovi---week-10---march-29-30"><span class="toc-section-number">6.5</span> JAMOVI - Week 10 - March 29 &amp; 30</a>
<ul>
<li><a href="lab-6-correlation.html#pre-lab-reading-and-tasks-1" id="toc-pre-lab-reading-and-tasks-1"><span class="toc-section-number">6.5.1</span> Pre-lab reading and tasks</a></li>
<li><a href="lab-6-correlation.html#correlation-coefficient-for-bivariate-data" id="toc-correlation-coefficient-for-bivariate-data"><span class="toc-section-number">6.5.2</span> Correlation Coefficient for Bivariate Data</a></li>
<li><a href="lab-6-correlation.html#correlation-matrix-1" id="toc-correlation-matrix-1"><span class="toc-section-number">6.5.3</span> Correlation Matrix</a></li>
<li><a href="lab-6-correlation.html#apa-format-reporting-of-a-correlation" id="toc-apa-format-reporting-of-a-correlation"><span class="toc-section-number">6.5.4</span> APA format reporting of a correlation</a></li>
<li><a href="lab-6-correlation.html#correlation-and-scatterplots-1" id="toc-correlation-and-scatterplots-1"><span class="toc-section-number">6.5.5</span> Correlation and Scatterplots</a></li>
<li><a href="lab-6-correlation.html#optional-activities-1" id="toc-optional-activities-1"><span class="toc-section-number">6.5.6</span> Optional activities</a></li>
<li><a href="lab-6-correlation.html#example-answers-to-optional-activities-1" id="toc-example-answers-to-optional-activities-1"><span class="toc-section-number">6.5.7</span> Example answers to optional activities</a></li>
<li><a href="lab-6-correlation.html#homework-4" id="toc-homework-4"><span class="toc-section-number">6.5.8</span> Homework</a></li>
<li><a href="lab-6-correlation.html#practice-problems-3" id="toc-practice-problems-3"><span class="toc-section-number">6.5.9</span> Practice Problems</a></li>
</ul></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#lab-7-one-way-anova" id="toc-lab-7-one-way-anova"><span class="toc-section-number">7</span> Lab 7 One-way ANOVA</a>
<ul>
<li><a href="lab-7-one-way-anova.html#how-to-not-think-about-bad-memories-by-playing-tetris" id="toc-how-to-not-think-about-bad-memories-by-playing-tetris"><span class="toc-section-number">7.1</span> How to not think about bad memories by playing Tetris</a>
<ul>
<li><a href="lab-7-one-way-anova.html#study-description-2" id="toc-study-description-2"><span class="toc-section-number">7.1.1</span> STUDY DESCRIPTION</a></li>
<li><a href="lab-7-one-way-anova.html#study-methods" id="toc-study-methods"><span class="toc-section-number">7.1.2</span> Study Methods</a></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#lab-skills-learned-2" id="toc-lab-skills-learned-2"><span class="toc-section-number">7.2</span> Lab Skills Learned</a></li>
<li><a href="lab-7-one-way-anova.html#important-stuff-2" id="toc-important-stuff-2"><span class="toc-section-number">7.3</span> Important Stuff</a></li>
<li><a href="lab-7-one-way-anova.html#r-7" id="toc-r-7"><span class="toc-section-number">7.4</span> R</a>
<ul>
<li><a href="lab-7-one-way-anova.html#load-the-data-2" id="toc-load-the-data-2"><span class="toc-section-number">7.4.1</span> Load the data</a></li>
<li><a href="lab-7-one-way-anova.html#inspect-the-dataframe" id="toc-inspect-the-dataframe"><span class="toc-section-number">7.4.2</span> Inspect the dataframe</a></li>
<li><a href="lab-7-one-way-anova.html#get-the-data-you-need" id="toc-get-the-data-you-need"><span class="toc-section-number">7.4.3</span> Get the data you need</a></li>
<li><a href="lab-7-one-way-anova.html#look-at-the-data-2" id="toc-look-at-the-data-2"><span class="toc-section-number">7.4.4</span> Look at the data</a></li>
<li><a href="lab-7-one-way-anova.html#conduct-the-anova" id="toc-conduct-the-anova"><span class="toc-section-number">7.4.5</span> Conduct the ANOVA</a></li>
<li><a href="lab-7-one-way-anova.html#reporting-the-anova-results" id="toc-reporting-the-anova-results"><span class="toc-section-number">7.4.6</span> Reporting the ANOVA results</a></li>
<li><a href="lab-7-one-way-anova.html#individual-comparisons" id="toc-individual-comparisons"><span class="toc-section-number">7.4.7</span> Individual comparisons</a></li>
<li><a href="lab-7-one-way-anova.html#writing-it-all-up." id="toc-writing-it-all-up."><span class="toc-section-number">7.4.8</span> Writing it all up.</a></li>
<li><a href="lab-7-one-way-anova.html#food-for-thought" id="toc-food-for-thought"><span class="toc-section-number">7.4.9</span> Food for thought</a></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#control-vs-reactivationtetris" id="toc-control-vs-reactivationtetris"><span class="toc-section-number">7.5</span> control vs reactivation+Tetris</a></li>
<li><a href="lab-7-one-way-anova.html#tetris_only-vs-reactivationtetris" id="toc-tetris_only-vs-reactivationtetris"><span class="toc-section-number">7.6</span> Tetris_only vs reactivation+Tetris</a>
<ul>
<li><a href="lab-7-one-way-anova.html#generalization-exercise-5" id="toc-generalization-exercise-5"><span class="toc-section-number">7.6.1</span> Generalization Exercise</a></li>
<li><a href="lab-7-one-way-anova.html#writing-assignment-5" id="toc-writing-assignment-5"><span class="toc-section-number">7.6.2</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#excel-7" id="toc-excel-7"><span class="toc-section-number">7.7</span> Excel</a></li>
<li><a href="lab-7-one-way-anova.html#spss-7" id="toc-spss-7"><span class="toc-section-number">7.8</span> SPSS</a>
<ul>
<li><a href="lab-7-one-way-anova.html#experiment-background-3" id="toc-experiment-background-3"><span class="toc-section-number">7.8.1</span> Experiment Background</a></li>
<li><a href="lab-7-one-way-anova.html#performing-a-one-factor-analysis-of-variance-anova-graphing-the-data" id="toc-performing-a-one-factor-analysis-of-variance-anova-graphing-the-data"><span class="toc-section-number">7.8.2</span> Performing a One-Factor Analysis of Variance (ANOVA) &amp; Graphing the data</a></li>
<li><a href="lab-7-one-way-anova.html#follow-up-tests" id="toc-follow-up-tests"><span class="toc-section-number">7.8.3</span> Follow-Up Tests</a></li>
<li><a href="lab-7-one-way-anova.html#planned-comparisons-t-contrasts" id="toc-planned-comparisons-t-contrasts"><span class="toc-section-number">7.8.4</span> Planned Comparisons: T-Contrasts</a></li>
<li><a href="lab-7-one-way-anova.html#unplanned-comparisons-post-hoc-tests" id="toc-unplanned-comparisons-post-hoc-tests"><span class="toc-section-number">7.8.5</span> Unplanned Comparisons: <em>Post-hoc</em> tests</a></li>
<li><a href="lab-7-one-way-anova.html#other-commands-used-to-conduct-the-one-way-anova-in-spss-general-linear-model" id="toc-other-commands-used-to-conduct-the-one-way-anova-in-spss-general-linear-model"><span class="toc-section-number">7.8.6</span> Other Commands Used to Conduct the One-Way ANOVA in SPSS: General Linear Model</a></li>
<li><a href="lab-7-one-way-anova.html#homework-questions-1" id="toc-homework-questions-1"><span class="toc-section-number">7.8.7</span> Homework questions</a></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#jamovi" id="toc-jamovi"><span class="toc-section-number">7.9</span> JAMOVI</a>
<ul>
<li><a href="lab-7-one-way-anova.html#experiment-background-4" id="toc-experiment-background-4"><span class="toc-section-number">7.9.1</span> Experiment Background</a></li>
<li><a href="lab-7-one-way-anova.html#checking-assumptions" id="toc-checking-assumptions"><span class="toc-section-number">7.9.2</span> Checking Assumptions</a></li>
<li><a href="lab-7-one-way-anova.html#performing-a-one-factor-analysis-of-variance-anova-graphing-the-data-1" id="toc-performing-a-one-factor-analysis-of-variance-anova-graphing-the-data-1"><span class="toc-section-number">7.9.3</span> Performing a One-Factor Analysis of Variance (ANOVA) &amp; Graphing the data</a></li>
<li><a href="lab-7-one-way-anova.html#follow-up-tests-1" id="toc-follow-up-tests-1"><span class="toc-section-number">7.9.4</span> Follow-Up Tests</a></li>
</ul></li>
</ul></li>
<li><a href="lab-8-repeated-measures-anova.html#lab-8-repeated-measures-anova" id="toc-lab-8-repeated-measures-anova"><span class="toc-section-number">8</span> Lab 8 Repeated Measures ANOVA</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#betcha-cant-type-jhdbzkco-very-fast-on-your-first-try" id="toc-betcha-cant-type-jhdbzkco-very-fast-on-your-first-try"><span class="toc-section-number">8.1</span> Betcha can’t type JHDBZKCO very fast on your first try</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#study-description-3" id="toc-study-description-3"><span class="toc-section-number">8.1.1</span> STUDY DESCRIPTION</a></li>
<li><a href="lab-8-repeated-measures-anova.html#study-methods-1" id="toc-study-methods-1"><span class="toc-section-number">8.1.2</span> Study Methods</a></li>
</ul></li>
<li><a href="lab-8-repeated-measures-anova.html#lab-skills-learned-3" id="toc-lab-skills-learned-3"><span class="toc-section-number">8.2</span> Lab Skills Learned</a></li>
<li><a href="lab-8-repeated-measures-anova.html#important-stuff-3" id="toc-important-stuff-3"><span class="toc-section-number">8.3</span> Important Stuff</a></li>
<li><a href="lab-8-repeated-measures-anova.html#r-8" id="toc-r-8"><span class="toc-section-number">8.4</span> R</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#load-the-data-3" id="toc-load-the-data-3"><span class="toc-section-number">8.4.1</span> Load the data</a></li>
<li><a href="lab-8-repeated-measures-anova.html#inspect-the-dataframe-1" id="toc-inspect-the-dataframe-1"><span class="toc-section-number">8.4.2</span> Inspect the dataframe</a></li>
<li><a href="lab-8-repeated-measures-anova.html#get-the-data-you-need-1" id="toc-get-the-data-you-need-1"><span class="toc-section-number">8.4.3</span> Get the data you need</a></li>
<li><a href="lab-8-repeated-measures-anova.html#look-at-the-data-3" id="toc-look-at-the-data-3"><span class="toc-section-number">8.4.4</span> Look at the data</a></li>
<li><a href="lab-8-repeated-measures-anova.html#look-at-the-means" id="toc-look-at-the-means"><span class="toc-section-number">8.4.5</span> Look at the means</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-the-repeated-measures-anova" id="toc-conduct-the-repeated-measures-anova"><span class="toc-section-number">8.4.6</span> Conduct the repeated Measures ANOVA</a></li>
<li><a href="lab-8-repeated-measures-anova.html#follow-up-comparisons" id="toc-follow-up-comparisons"><span class="toc-section-number">8.4.7</span> Follow-up comparisons</a></li>
<li><a href="lab-8-repeated-measures-anova.html#reporting-everything" id="toc-reporting-everything"><span class="toc-section-number">8.4.8</span> Reporting everything</a></li>
<li><a href="lab-8-repeated-measures-anova.html#generalization-exercise-6" id="toc-generalization-exercise-6"><span class="toc-section-number">8.4.9</span> Generalization Exercise</a></li>
<li><a href="lab-8-repeated-measures-anova.html#writing-assignment-6" id="toc-writing-assignment-6"><span class="toc-section-number">8.4.10</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-8-repeated-measures-anova.html#excel-8" id="toc-excel-8"><span class="toc-section-number">8.5</span> Excel</a></li>
<li><a href="lab-8-repeated-measures-anova.html#spss-8" id="toc-spss-8"><span class="toc-section-number">8.6</span> SPSS</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#experiment-background-5" id="toc-experiment-background-5"><span class="toc-section-number">8.6.1</span> Experiment Background</a></li>
<li><a href="lab-8-repeated-measures-anova.html#produce-a-frequency-histogram-and-remove-outliers" id="toc-produce-a-frequency-histogram-and-remove-outliers"><span class="toc-section-number">8.6.2</span> Produce a frequency histogram and remove outliers</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-and-graph-one-factor-repeated-measures-anova" id="toc-conduct-and-graph-one-factor-repeated-measures-anova"><span class="toc-section-number">8.6.3</span> Conduct and graph One-Factor Repeated Measures ANOVA</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-planned-comparisons-using-a-paired-samples-t-test" id="toc-conduct-planned-comparisons-using-a-paired-samples-t-test"><span class="toc-section-number">8.6.4</span> Conduct planned comparisons using a paired-samples t-test</a></li>
<li><a href="lab-8-repeated-measures-anova.html#practice-problems-4" id="toc-practice-problems-4"><span class="toc-section-number">8.6.5</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-8-repeated-measures-anova.html#jamovi-1" id="toc-jamovi-1"><span class="toc-section-number">8.7</span> JAMOVI</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#experiment-background-6" id="toc-experiment-background-6"><span class="toc-section-number">8.7.1</span> Experiment Background</a></li>
<li><a href="lab-8-repeated-measures-anova.html#checking-assumptions-1" id="toc-checking-assumptions-1"><span class="toc-section-number">8.7.2</span> Checking Assumptions</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-and-graph-one-factor-repeated-measures-anova-1" id="toc-conduct-and-graph-one-factor-repeated-measures-anova-1"><span class="toc-section-number">8.7.3</span> Conduct and graph One-Factor Repeated Measures ANOVA</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-follow-up-tests" id="toc-conduct-follow-up-tests"><span class="toc-section-number">8.7.4</span> Conduct follow-up tests</a></li>
<li><a href="lab-8-repeated-measures-anova.html#some-apa-formatting-reminders-for-writing-results-sections-2" id="toc-some-apa-formatting-reminders-for-writing-results-sections-2"><span class="toc-section-number">8.7.5</span> Some APA formatting reminders for writing results sections</a></li>
<li><a href="lab-8-repeated-measures-anova.html#homework-5" id="toc-homework-5"><span class="toc-section-number">8.7.6</span> Homework</a></li>
<li><a href="lab-8-repeated-measures-anova.html#practice-problems-5" id="toc-practice-problems-5"><span class="toc-section-number">8.7.7</span> Practice Problems</a></li>
</ul></li>
</ul></li>
<li><a href="lab-9-factorial-anova.html#lab-9-factorial-anova" id="toc-lab-9-factorial-anova"><span class="toc-section-number">9</span> Lab 9: Factorial ANOVA</a>
<ul>
<li><a href="lab-9-factorial-anova.html#does-standing-up-make-you-focus-more" id="toc-does-standing-up-make-you-focus-more"><span class="toc-section-number">9.1</span> Does standing up make you focus more?</a>
<ul>
<li><a href="lab-9-factorial-anova.html#study-description-4" id="toc-study-description-4"><span class="toc-section-number">9.1.1</span> STUDY DESCRIPTION</a></li>
<li><a href="lab-9-factorial-anova.html#study-methods-2" id="toc-study-methods-2"><span class="toc-section-number">9.1.2</span> Study Methods</a></li>
</ul></li>
<li><a href="lab-9-factorial-anova.html#lab-skills-learned-4" id="toc-lab-skills-learned-4"><span class="toc-section-number">9.2</span> Lab Skills Learned</a></li>
<li><a href="lab-9-factorial-anova.html#important-stuff-4" id="toc-important-stuff-4"><span class="toc-section-number">9.3</span> Important Stuff</a></li>
<li><a href="lab-9-factorial-anova.html#r-9" id="toc-r-9"><span class="toc-section-number">9.4</span> R</a>
<ul>
<li><a href="lab-9-factorial-anova.html#load-the-data-4" id="toc-load-the-data-4"><span class="toc-section-number">9.4.1</span> Load the data</a></li>
<li><a href="lab-9-factorial-anova.html#inspect-the-dataframe-2" id="toc-inspect-the-dataframe-2"><span class="toc-section-number">9.4.2</span> Inspect the dataframe</a></li>
<li><a href="lab-9-factorial-anova.html#get-the-data-you-need-2" id="toc-get-the-data-you-need-2"><span class="toc-section-number">9.4.3</span> Get the data you need</a></li>
<li><a href="lab-9-factorial-anova.html#get-the-data-into-the-format-you-want" id="toc-get-the-data-into-the-format-you-want"><span class="toc-section-number">9.4.4</span> Get the data into the format you want</a></li>
<li><a href="lab-9-factorial-anova.html#look-at-the-data-4" id="toc-look-at-the-data-4"><span class="toc-section-number">9.4.5</span> Look at the data</a></li>
<li><a href="lab-9-factorial-anova.html#look-at-the-means-1" id="toc-look-at-the-means-1"><span class="toc-section-number">9.4.6</span> Look at the means</a></li>
<li><a href="lab-9-factorial-anova.html#conduct-the-anova-1" id="toc-conduct-the-anova-1"><span class="toc-section-number">9.4.7</span> Conduct the ANOVA</a></li>
<li><a href="lab-9-factorial-anova.html#between-subjects-anova" id="toc-between-subjects-anova"><span class="toc-section-number">9.4.8</span> Between Subjects ANOVA</a></li>
<li><a href="lab-9-factorial-anova.html#repeated-measures-anova" id="toc-repeated-measures-anova"><span class="toc-section-number">9.4.9</span> Repeated measures ANOVA</a></li>
<li><a href="lab-9-factorial-anova.html#follow-up-comparisons-1" id="toc-follow-up-comparisons-1"><span class="toc-section-number">9.4.10</span> Follow-up comparisons</a></li>
<li><a href="lab-9-factorial-anova.html#generalization-exercise-7" id="toc-generalization-exercise-7"><span class="toc-section-number">9.4.11</span> Generalization Exercise</a></li>
<li><a href="lab-9-factorial-anova.html#writing-asignment" id="toc-writing-asignment"><span class="toc-section-number">9.4.12</span> Writing asignment</a></li>
</ul></li>
<li><a href="lab-9-factorial-anova.html#excel-9" id="toc-excel-9"><span class="toc-section-number">9.5</span> Excel</a></li>
<li><a href="lab-9-factorial-anova.html#spss-9" id="toc-spss-9"><span class="toc-section-number">9.6</span> SPSS</a>
<ul>
<li><a href="lab-9-factorial-anova.html#experiment-background-7" id="toc-experiment-background-7"><span class="toc-section-number">9.6.1</span> Experiment Background</a></li>
<li><a href="lab-9-factorial-anova.html#conduct-a-between-subjects-two-factor-analysis-of-variance-anova" id="toc-conduct-a-between-subjects-two-factor-analysis-of-variance-anova"><span class="toc-section-number">9.6.2</span> Conduct a Between-Subjects Two-Factor Analysis of Variance (ANOVA)</a></li>
<li><a href="lab-9-factorial-anova.html#calculate-simple-effects" id="toc-calculate-simple-effects"><span class="toc-section-number">9.6.3</span> Calculate simple effects</a></li>
<li><a href="lab-9-factorial-anova.html#conduct-a-repeated-measures-two-factor-analysis-of-variance-anova" id="toc-conduct-a-repeated-measures-two-factor-analysis-of-variance-anova"><span class="toc-section-number">9.6.4</span> Conduct a Repeated Measures Two-Factor Analysis of Variance (ANOVA)</a></li>
<li><a href="lab-9-factorial-anova.html#calculate-simple-effects-1" id="toc-calculate-simple-effects-1"><span class="toc-section-number">9.6.5</span> Calculate simple effects</a></li>
<li><a href="lab-9-factorial-anova.html#practice-problems-6" id="toc-practice-problems-6"><span class="toc-section-number">9.6.6</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-9-factorial-anova.html#jamovi-2" id="toc-jamovi-2"><span class="toc-section-number">9.7</span> JAMOVI</a></li>
</ul></li>
<li><a href="lab-10-mixed-factorial-anova.html#lab-10-mixed-factorial-anova" id="toc-lab-10-mixed-factorial-anova"><span class="toc-section-number">10</span> Lab 10: Mixed Factorial ANOVA</a>
<ul>
<li><a href="lab-10-mixed-factorial-anova.html#do-you-remember-things-better-when-you-take-pictures-of-them" id="toc-do-you-remember-things-better-when-you-take-pictures-of-them"><span class="toc-section-number">10.1</span> Do you remember things better when you take pictures of them?</a>
<ul>
<li><a href="lab-10-mixed-factorial-anova.html#study-description-5" id="toc-study-description-5"><span class="toc-section-number">10.1.1</span> Study description</a></li>
</ul></li>
<li><a href="lab-10-mixed-factorial-anova.html#lab-skills-learned-5" id="toc-lab-skills-learned-5"><span class="toc-section-number">10.2</span> Lab Skills Learned</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#important-stuff-5" id="toc-important-stuff-5"><span class="toc-section-number">10.3</span> Important Stuff</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#r-10" id="toc-r-10"><span class="toc-section-number">10.4</span> R</a>
<ul>
<li><a href="lab-10-mixed-factorial-anova.html#load-the-data-5" id="toc-load-the-data-5"><span class="toc-section-number">10.4.1</span> Load the data</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#inspect-the-dataframe-3" id="toc-inspect-the-dataframe-3"><span class="toc-section-number">10.4.2</span> Inspect the dataframe</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#get-the-data-you-need-3" id="toc-get-the-data-you-need-3"><span class="toc-section-number">10.4.3</span> Get the data you need</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#get-the-data-into-the-format-you-want-1" id="toc-get-the-data-into-the-format-you-want-1"><span class="toc-section-number">10.4.4</span> Get the data into the format you want</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#look-at-the-data-5" id="toc-look-at-the-data-5"><span class="toc-section-number">10.4.5</span> Look at the data</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#look-at-the-means-2" id="toc-look-at-the-means-2"><span class="toc-section-number">10.4.6</span> Look at the means</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#conduct-the-anova-2" id="toc-conduct-the-anova-2"><span class="toc-section-number">10.4.7</span> Conduct the ANOVA</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#generalization-exercise-8" id="toc-generalization-exercise-8"><span class="toc-section-number">10.4.8</span> Generalization Exercise</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#writing-assignment-7" id="toc-writing-assignment-7"><span class="toc-section-number">10.4.9</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-10-mixed-factorial-anova.html#excel-10" id="toc-excel-10"><span class="toc-section-number">10.5</span> Excel</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#spss-10" id="toc-spss-10"><span class="toc-section-number">10.6</span> SPSS</a>
<ul>
<li><a href="lab-10-mixed-factorial-anova.html#experiment-background-8" id="toc-experiment-background-8"><span class="toc-section-number">10.6.1</span> Experiment Background</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#conduct-a-mixed-factorial-analysis-of-variance-anova" id="toc-conduct-a-mixed-factorial-analysis-of-variance-anova"><span class="toc-section-number">10.6.2</span> Conduct a Mixed-Factorial Analysis of Variance (ANOVA)</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#calculate-simple-effects-2" id="toc-calculate-simple-effects-2"><span class="toc-section-number">10.6.3</span> Calculate simple effects</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#practice-problems-7" id="toc-practice-problems-7"><span class="toc-section-number">10.6.4</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-10-mixed-factorial-anova.html#jamovi-3" id="toc-jamovi-3"><span class="toc-section-number">10.7</span> JAMOVI</a></li>
</ul></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#lab-11-choosing-an-appropriate-statistical-test" id="toc-lab-11-choosing-an-appropriate-statistical-test"><span class="toc-section-number">11</span> Lab 11: Choosing an appropriate statistical test</a>
<ul>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#general-goals-3" id="toc-general-goals-3"><span class="toc-section-number">11.1</span> General Goals</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#summary-of-the-tests" id="toc-summary-of-the-tests"><span class="toc-section-number">11.2</span> Summary of the tests</a>
<ul>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#pearsons-r-correlation-coefficient" id="toc-pearsons-r-correlation-coefficient"><span class="toc-section-number">11.2.1</span> Pearson’s <em>r</em> correlation coefficient</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#spearmans-r-correlation-coefficient" id="toc-spearmans-r-correlation-coefficient"><span class="toc-section-number">11.2.2</span> Spearman’s <em>r</em> correlation coefficient</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#independent-t-test" id="toc-independent-t-test"><span class="toc-section-number">11.2.3</span> Independent <em>t</em>-test</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#mann-whitney-u-test" id="toc-mann-whitney-u-test"><span class="toc-section-number">11.2.4</span> Mann-Whitney <em>U</em>-test</a></li>
</ul></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#spss-11" id="toc-spss-11"><span class="toc-section-number">11.3</span> SPSS</a>
<ul>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#pearson-and-spearman-correlation" id="toc-pearson-and-spearman-correlation"><span class="toc-section-number">11.3.1</span> Pearson and Spearman Correlation</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#independent-t-test-1" id="toc-independent-t-test-1"><span class="toc-section-number">11.3.2</span> Independent <em>t</em>-test</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#mann-whitney-u-test-1" id="toc-mann-whitney-u-test-1"><span class="toc-section-number">11.3.3</span> Mann-Whitney <em>U</em>-test</a></li>
</ul></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#homework-mar-9-and-10-2021" id="toc-homework-mar-9-and-10-2021"><span class="toc-section-number">11.4</span> Homework (Mar 9 and 10, 2021)</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#homework-feb-23-and-24-2021" id="toc-homework-feb-23-and-24-2021"><span class="toc-section-number">11.5</span> Homework (Feb 23 and 24, 2021)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Answering questions with data: Lab Manual</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<img src="LabmanualCover.png" id="coverpic" width="350" style="display: block; margin: auto;" />
<div id="lab-8-repeated-measures-anova" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Lab 8 Repeated Measures ANOVA<a href="lab-8-repeated-measures-anova.html#lab-8-repeated-measures-anova" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<script>
$("#coverpic").hide();
</script>
<p><span class="newthought">
However, perhaps the main point is that you are under no obligation to analyse variance into its parts if it does not come apart easily, and its unwillingness to do so naturally indicates that one’s line of approach is not very fruitful.
—R. A. Fisher
</span></p>
<div id="betcha-cant-type-jhdbzkco-very-fast-on-your-first-try" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Betcha can’t type JHDBZKCO very fast on your first try<a href="lab-8-repeated-measures-anova.html#betcha-cant-type-jhdbzkco-very-fast-on-your-first-try" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This lab activity uses the data from Behmer &amp; Crump (2017) to teach one-factor repeated measures ANOVA with-up follow comparisons</p>
<div id="study-description-3" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> STUDY DESCRIPTION<a href="lab-8-repeated-measures-anova.html#study-description-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Behmer &amp; Crump (2017) used the everyday task of typing on a computer keyboard to ask questions about how people learn to put sequences of actions together. Whenever you type a series of letters on the keyboard, you are putting a sequence of actions together, so typing is task that could be used to measure skilled sequencing. Typing also happens to be a convenient task for measuring sequencing. For example, every time a person types a letter, the timing of the button press and the letter pressed can be measured and stored for later analysis.</p>
<p>Behmer &amp; Crump were interested in asking a few different questions, however, we will simplify everything and talk about replication. First we describe an interesting finding from previous research. Behmer &amp; Crump repeated an experiment that should also produce this same finding. If they succeed in doing this, it means the finding can be replicated, and that it happens in more than one lab.</p>
<p><strong>Finding from previous resaearch:</strong> Prior research showed that typists do something funny. Skilled typists can type normal words very fast. This suggests they know how to locate all of the letters on the keyboard, and can press each letter very quickly to type words. That part isn’t particularly funny. However, if you take really skilled typists and make them type random letters like this: kwitb dhhgjtryq xkldpt mazhyffdt, guess what happens? They slow down a lot. It’s kind of weird that a typist would slow down, after all they can type letters really fast when they appear in words, but not when they appear in random orders…what gives? Last, it turns out that typists are kind of in the middle in terms of speed, if you ask them to type non-words that have similar properties to words, such as: quenp hamlke phwempy.</p>
<p>To summarize, prior research showed that typing speed changes as a function of the structure of the text, roughly in this order from fastest to slowest.</p>
<p>(FASTEST) Normal Words &lt; Word-like Non-words &lt; Random strings (SLOWEST)</p>
<p><strong>Replication question:</strong> Behmer &amp; Crump also measured typists while they typed words, non-words that were English-like, and random strings. They had some additional things they were interested in, but for us, we are interested in whether they would show the same effect. Would they replicate the pattern: Normal words (Fastest) &lt; Word-like Non-words (medium) &lt;- Random strings (Slowest)?</p>
</div>
<div id="study-methods-1" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Study Methods<a href="lab-8-repeated-measures-anova.html#study-methods-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The authors conducted a repeated measures experiment. A total of 38 subjects were used for the analysis.</p>
<p><strong>Independent Variable</strong>: The IV Stimulus or typing material had three levels: Normal, Bigrams, and Random. Normal refers to normal 5 letter English words (like truck, or plant). Bigrams refers to non-words that have properties similar to words (e.g., phemt quilp). Random refers to 5 letter strings whose letters were totally random (qmklt gdrzn lprni).</p>
<p><strong>Dependent Variables</strong>: There were three dependent variables, that all measured different aspects of typing performance. Reaction times (RTs) were defined as the temporal interval between seeing a stimulus (to type), and then starting to type it (first key press). Inter-keystroke intervals (IKSIs) are the times between each key-press. Last, accuracy was also measured (correct or incorrect key-presses)</p>
<p><strong>The task</strong>: Participants (who happened to also be students from Brooklyn College) sat in front a computer. They were presented with one stimulus (word, bigrams, or random) at a time. As soon as they saw the string of letters, they typed it as quickly and accurately as they could, then they moved on to the next trial.</p>
<p>Reminder, this is a repeated measures design because each participant typed letter strings from the word, bigrams, and random conditions.</p>
</div>
</div>
<div id="lab-skills-learned-3" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Lab Skills Learned<a href="lab-8-repeated-measures-anova.html#lab-skills-learned-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Conducting a one-factor repeated measures ANOVA</li>
<li>Conducting follow-up comparisons</li>
</ul>
</div>
<div id="important-stuff-3" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Important Stuff<a href="lab-8-repeated-measures-anova.html#important-stuff-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>citation: Behmer, Lawrence P., Crump, M. J. C. (2017). Spatial Knowledge during Skilled Action Sequencing: Hierarchical versus Non-Hierarchical Representations. Attention, Perception &amp; Psychophysics, 79, 2435-2448.</li>
<li><a href="https://github.com/CrumpLab/CrumpLab.github.io/raw/master/files/8753/Behmer%20and%20Crump%20-%202017.pdf">Link to .pdf of article</a></li>
<li><a href="https://github.com/CrumpLab/statisticsLab/raw/master/data/exp1_BehmerCrumpAPP.csv" download>Data in .csv format</a></li>
</ul>
</div>
<div id="r-8" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> R<a href="lab-8-repeated-measures-anova.html#r-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="load-the-data-3" class="section level3 hasAnchor" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> Load the data<a href="lab-8-repeated-measures-anova.html#load-the-data-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Remember that any line with a # makes a comment and the code does not run. Below is how to load the .csv data from the online repository, or from a local file (you need to change the file path to where the local file is, if you downloaded it). The data contains all of the measures and conditions from Experiment 1 in the paper.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="lab-8-repeated-measures-anova.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-2"><a href="lab-8-repeated-measures-anova.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#all_data &lt;- fread(&quot;https://github.com/CrumpLab/statisticsLab/raw/master/data/exp1_BehmerCrumpAPP.csv&quot;)</span></span>
<span id="cb1-3"><a href="lab-8-repeated-measures-anova.html#cb1-3" aria-hidden="true" tabindex="-1"></a>all_data <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;data/exp1_BehmerCrumpAPP.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in require_bit64_if_needed(ans): Some columns are type &#39;integer64&#39;
## but package bit64 is not installed. Those columns will print as strange
## looking floating point data. There is no need to reload the data. Simply
## install.packages(&#39;bit64&#39;) to obtain the integer64 print method and print the
## data again.</code></pre>
</div>
<div id="inspect-the-dataframe-1" class="section level3 hasAnchor" number="8.4.2">
<h3><span class="header-section-number">8.4.2</span> Inspect the dataframe<a href="lab-8-repeated-measures-anova.html#inspect-the-dataframe-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This will give you a big picture of the data frame. Click the button to view it in your browser, then take a look to see what is in it.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="lab-8-repeated-measures-anova.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb3-2"><a href="lab-8-repeated-measures-anova.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(<span class="fu">dfSummary</span>(all_data[,<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>,<span class="dv">10</span><span class="sc">:</span><span class="dv">20</span>)]))</span></code></pre></div>
<p>Note, there is some weird stuff in code above. Normally, we would just write <code>view(dfSummary(all_data))</code>, why we add this: <code>all_data[,c(1:7,10:20)]</code>? It turns out the dfSummary function didn’t like some of the data. In particular it didn’t like the data in columns 8 an 9 (notice those numbers are missing, the range inside c is 1 to 7 and 10 to 20). It doesn’t mean the data isn’t there, just that it didn’t want to display it in the viewer.</p>
</div>
<div id="get-the-data-you-need-1" class="section level3 hasAnchor" number="8.4.3">
<h3><span class="header-section-number">8.4.3</span> Get the data you need<a href="lab-8-repeated-measures-anova.html#get-the-data-you-need-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This data file contains all of the data from Experiment 1 in the paper. So, we don’t need to get rid of any rows.</p>
<p>There are numerous columns, some of them we don’t need for the analysis. But, we’ll just ignore these later when we use <code>dplyr</code> to group by the columns we want.</p>
<p>The structure of this data a file is in long form. Every row described a measurement for a single key-press. For example, the first 5 rows, have data for the timing of the first 5 key-presses, that the first subject made to type the first string of letters they saw. In total there were 85,410 key-presses made. That’s quite a lot.</p>
<div id="the-independent-variable-1" class="section level4 hasAnchor" number="8.4.3.1">
<h4><span class="header-section-number">8.4.3.1</span> The independent variable<a href="lab-8-repeated-measures-anova.html#the-independent-variable-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The important independent variable is in the column <code>Stimulus</code>.</p>
<ul>
<li>Normal (5 letter English words)</li>
<li>Bigrams (5 letter strings that kind of looked like words)</li>
<li>Random (5 letter strings that were random)</li>
</ul>
<p>It is also important to know that the <code>Order</code> column codes the position for each letter, from 1 to 5.</p>
<p>Note: there was another independent variable in the study as well. We talk about this later. The second IV is coded in the <code>Block</code> column.</p>
<ul>
<li>Baseline (normal typing, keyboard is visible while typing)</li>
<li>Manipulation (occluded typing, keyboard is covered while typing)</li>
</ul>
</div>
<div id="the-dependent-variables" class="section level4 hasAnchor" number="8.4.3.2">
<h4><span class="header-section-number">8.4.3.2</span> The dependent variables<a href="lab-8-repeated-measures-anova.html#the-dependent-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ol style="list-style-type: decimal">
<li><code>TimeFromOnset</code> : This column records the temporal interval in milliseconds between the onset of the word and each key-press. When order is 1 (first keystroke), the number here is the reaction time to start typing.</li>
<li><code>PureRTs</code> : This column contains keystroke intervals. The first interval is between the onset of the word and the first key-press (order 1), the second interval is between the first and second key-press (order 2), and so on. <code>PureRTs</code> for orders 2 to 5, represent the inter-keystroke intervals reported in paper.</li>
<li><code>AllCorrect</code> : 0 means incorrect (wrong letter was typed), 1 means correct (correct letter was typed)</li>
</ol>
</div>
</div>
<div id="look-at-the-data-3" class="section level3 hasAnchor" number="8.4.4">
<h3><span class="header-section-number">8.4.4</span> Look at the data<a href="lab-8-repeated-measures-anova.html#look-at-the-data-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Remember before we do any analysis, we always want to “look” at the data. This first pass let’s us know if the data “look right”. For example, the data file could be messed up and maybe there aren’t any numbers there, or maybe the numbers are just too weird.</p>
<p>For example, this study involves reaction times: the time between seeing something and responding to it. If you had done a study like this before, you would know that it usually doesn’t take people that long to start responding. Most reaction times will be under a second (or 1000 milliseconds). But, sometime people are little slow, and sometimes they do funny things like check their phone in the middle of an experiment.</p>
<p>Before I analyze reaction time data, I often make a histogram of all of the RT data, like this:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="lab-8-repeated-measures-anova.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(all_data<span class="sc">$</span>PureRTs)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>We can see that almost all of the reaction times are well below 5000 milliseconds (5 seconds), which is good. Most of the time people were paying attention and not “checking their phone”. Notice, the range of the histogram goes out to 15,000 milliseconds. You can’t see any bars out there (too small to notice), but there must be at least a few trials where somebody took 15 seconds to start responding. These are called outliers. We will remove them before we conduct our analysis</p>
</div>
<div id="look-at-the-means" class="section level3 hasAnchor" number="8.4.5">
<h3><span class="header-section-number">8.4.5</span> Look at the means<a href="lab-8-repeated-measures-anova.html#look-at-the-means" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As part of looking at the data, we might as well make a figure that shows the mean reaction times in each condition, and some error bars to look at the spread in each condition. The following code takes three important steps:</p>
<ol style="list-style-type: decimal">
<li>Get the means for each subject in each condition. These are put into the data frame called <code>subject_means</code>.</li>
<li>Get the means for each condition, by averaging over the means for each subject. These are put into the data frame called <code>plot_means</code>.</li>
<li>Make a graph with the <code>plot_means</code> data frame using ggplot2.</li>
</ol>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="lab-8-repeated-measures-anova.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:data.table&#39;:
## 
##     between, first, last</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="lab-8-repeated-measures-anova.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.1.2</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="lab-8-repeated-measures-anova.html#cb12-1" aria-hidden="true" tabindex="-1"></a>all_data<span class="sc">$</span>Block<span class="ot">&lt;-</span><span class="fu">as.factor</span>(all_data<span class="sc">$</span>Block)</span>
<span id="cb12-2"><a href="lab-8-repeated-measures-anova.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(all_data<span class="sc">$</span>Block) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Visible keyboard&quot;</span>,<span class="st">&quot;Covered Keyboard&quot;</span>)</span>
<span id="cb12-3"><a href="lab-8-repeated-measures-anova.html#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="lab-8-repeated-measures-anova.html#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="do">## get subject mean RTs</span></span>
<span id="cb12-5"><a href="lab-8-repeated-measures-anova.html#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="lab-8-repeated-measures-anova.html#cb12-6" aria-hidden="true" tabindex="-1"></a>subject_means <span class="ot">&lt;-</span> all_data <span class="sc">%&gt;%</span></span>
<span id="cb12-7"><a href="lab-8-repeated-measures-anova.html#cb12-7" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">filter</span>(Order<span class="sc">==</span><span class="dv">1</span>, Correct<span class="sc">==</span><span class="dv">1</span>, PureRTs<span class="sc">&lt;</span><span class="dv">5000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="lab-8-repeated-measures-anova.html#cb12-8" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">group_by</span>(Subject, Block, Stimulus) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="lab-8-repeated-measures-anova.html#cb12-9" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">summarise</span>(<span class="at">mean_rt =</span> <span class="fu">mean</span>(PureRTs))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Subject&#39;, &#39;Block&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="lab-8-repeated-measures-anova.html#cb14-1" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Subject<span class="ot">&lt;-</span><span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Subject)</span>
<span id="cb14-2"><a href="lab-8-repeated-measures-anova.html#cb14-2" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Block<span class="ot">&lt;-</span><span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Block)</span>
<span id="cb14-3"><a href="lab-8-repeated-measures-anova.html#cb14-3" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Stimulus<span class="ot">&lt;-</span><span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Stimulus)</span>
<span id="cb14-4"><a href="lab-8-repeated-measures-anova.html#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="lab-8-repeated-measures-anova.html#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="do">## get condition mean RTs</span></span>
<span id="cb14-6"><a href="lab-8-repeated-measures-anova.html#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="lab-8-repeated-measures-anova.html#cb14-7" aria-hidden="true" tabindex="-1"></a>plot_means <span class="ot">&lt;-</span> subject_means <span class="sc">%&gt;%</span></span>
<span id="cb14-8"><a href="lab-8-repeated-measures-anova.html#cb14-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">group_by</span>(Block, Stimulus) <span class="sc">%&gt;%</span></span>
<span id="cb14-9"><a href="lab-8-repeated-measures-anova.html#cb14-9" aria-hidden="true" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">means =</span> <span class="fu">mean</span>(mean_rt),</span>
<span id="cb14-10"><a href="lab-8-repeated-measures-anova.html#cb14-10" aria-hidden="true" tabindex="-1"></a>                        <span class="at">SEs =</span> <span class="fu">sd</span>(mean_rt)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(mean_rt)))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Block&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="lab-8-repeated-measures-anova.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">## plot the condition means</span></span>
<span id="cb16-2"><a href="lab-8-repeated-measures-anova.html#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="lab-8-repeated-measures-anova.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># re-order stimulus factor for plotting</span></span>
<span id="cb16-4"><a href="lab-8-repeated-measures-anova.html#cb16-4" aria-hidden="true" tabindex="-1"></a>plot_means<span class="sc">$</span>Stimulus <span class="ot">&lt;-</span> <span class="fu">factor</span>(plot_means<span class="sc">$</span>Stimulus, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Normal&quot;</span>, <span class="st">&quot;Bigrams&quot;</span>, <span class="st">&quot;Random&quot;</span>))</span>
<span id="cb16-5"><a href="lab-8-repeated-measures-anova.html#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="lab-8-repeated-measures-anova.html#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_means, <span class="fu">aes</span>(<span class="at">x=</span>Stimulus, <span class="at">y=</span>means, <span class="at">group=</span>Block, <span class="at">color=</span>Block))<span class="sc">+</span></span>
<span id="cb16-7"><a href="lab-8-repeated-measures-anova.html#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb16-8"><a href="lab-8-repeated-measures-anova.html#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb16-9"><a href="lab-8-repeated-measures-anova.html#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>means<span class="sc">-</span>SEs, <span class="at">ymax=</span>means<span class="sc">+</span>SEs), <span class="at">width=</span>.<span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb16-10"><a href="lab-8-repeated-measures-anova.html#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb16-11"><a href="lab-8-repeated-measures-anova.html#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Mean Reaction Time (ms)&quot;</span>)<span class="sc">+</span></span>
<span id="cb16-12"><a href="lab-8-repeated-measures-anova.html#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Typing Material&quot;</span>)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Alright, we made things a little bit more complicated than they need to be. Our primary question is whether reaction times followed this pattern: Normal &lt; Bigrams &lt; Random. We can see the means do follow this pattern. However, shouldn’t we only be looking at three means, why are their six means, and two lines?</p>
<p>The above code included the second independent variable <code>Block</code>. As a result, you are seeing the means for Typing material when subjects could see the keyboard, and when the couldn’t see the keyboard. We will come back to this later. For now, let’s ignore the Block condition, and find the means for the Typing Material IV by averaging over the Block conditions. We run the same code as above, by take out <code>Block</code>, in the <code>group_by</code> function. We also take <code>Block</code> out the ggplot function.</p>
<p><strong>VERY IMPORTANT</strong>: We did something in the above code that we didn’t point out. We filtered the data before we found the means. For most of the data sets in other labs, we given you data that is more or less ready to analyse. More often than not data needs to be pre-processed, or filtered before you analyze it. We can use the <code>filter</code> function in <code>dplyr</code> to do our filtering. <code>filter</code> filters the rows for us, so we will only include the rows that we want.</p>
<ol style="list-style-type: decimal">
<li><p>We want to analyze the time between the onset of the stimulus and the first keystroke. The reaction times for this value are in the <code>PureRTs</code> column, but this column contains other RTs that we do not want to analyse. For example, the <code>Order</code> column codes for the letter position in the string. We only want to analyze the rows that contain a <code>1</code>, for the first position. So, that is why we add <code>Order==1</code> to the filter function below.</p></li>
<li><p>We want to analyze only the reaction times that are correct. That is, when the subject typed the first letter correctly, and did not make a typo. Accuracy is coded in the <code>Correct</code> column, with 1 = correct, and 0 = incorrect. We add <code>Correct==1</code> to the filtering function.</p></li>
</ol>
<p>Note the use of <code>==</code>, that is two equal signs in a row. In R, two equal signs in a row has a special meaning. It means conduct a <code>logic</code> test to determine if one thing is the same as another.</p>
<ol start="3" style="list-style-type: decimal">
<li>We want to analyze only reaction times that are “sensible” to analyze. What does sensible mean? We don’t want to analyze data that is clearly garbage data. For example, if someone fell asleep at the computer and didn’t respond for 15 seconds, that kind of data is not what we want to analyze. If we were to filter the data, and exclude these kinds of <code>outliers</code>, we would be conducting an outlier elimination procedure. Behmer &amp; Crump (2017) did this, and it is commonly done in many different kinds of studies. We skip an extended discussion of outlier elimination for this lab. But, we do introduce the idea of doing it. We want to keep as much of the data as possible. So, what we do is keep all of the RTs that are less than 5000 ms (that’s 5 seconds). To do this, we add <code>PureRTs&lt;5000</code> to the filter function.</li>
</ol>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="lab-8-repeated-measures-anova.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## get subject mean RTs</span></span>
<span id="cb17-2"><a href="lab-8-repeated-measures-anova.html#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="lab-8-repeated-measures-anova.html#cb17-3" aria-hidden="true" tabindex="-1"></a>subject_means <span class="ot">&lt;-</span> all_data <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="lab-8-repeated-measures-anova.html#cb17-4" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">filter</span>(Order<span class="sc">==</span><span class="dv">1</span>, Correct<span class="sc">==</span><span class="dv">1</span>, PureRTs<span class="sc">&lt;</span><span class="dv">5000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="lab-8-repeated-measures-anova.html#cb17-5" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">group_by</span>(Subject, Stimulus) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="lab-8-repeated-measures-anova.html#cb17-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">summarise</span>(<span class="at">mean_rt =</span> <span class="fu">mean</span>(PureRTs))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Subject&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="lab-8-repeated-measures-anova.html#cb19-1" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Subject<span class="ot">&lt;-</span><span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Subject)</span>
<span id="cb19-2"><a href="lab-8-repeated-measures-anova.html#cb19-2" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Stimulus<span class="ot">&lt;-</span><span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Stimulus)</span>
<span id="cb19-3"><a href="lab-8-repeated-measures-anova.html#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="lab-8-repeated-measures-anova.html#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="do">## get condition mean RTs</span></span>
<span id="cb19-5"><a href="lab-8-repeated-measures-anova.html#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="lab-8-repeated-measures-anova.html#cb19-6" aria-hidden="true" tabindex="-1"></a>plot_means <span class="ot">&lt;-</span> subject_means <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="lab-8-repeated-measures-anova.html#cb19-7" aria-hidden="true" tabindex="-1"></a>              <span class="fu">group_by</span>(Stimulus) <span class="sc">%&gt;%</span></span>
<span id="cb19-8"><a href="lab-8-repeated-measures-anova.html#cb19-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">means =</span> <span class="fu">mean</span>(mean_rt),</span>
<span id="cb19-9"><a href="lab-8-repeated-measures-anova.html#cb19-9" aria-hidden="true" tabindex="-1"></a>                        <span class="at">SEs =</span> <span class="fu">sd</span>(mean_rt)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(mean_rt)))</span>
<span id="cb19-10"><a href="lab-8-repeated-measures-anova.html#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="lab-8-repeated-measures-anova.html#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="do">## plot the condition means</span></span>
<span id="cb19-12"><a href="lab-8-repeated-measures-anova.html#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="lab-8-repeated-measures-anova.html#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co"># re-order stimulus factor for plotting</span></span>
<span id="cb19-14"><a href="lab-8-repeated-measures-anova.html#cb19-14" aria-hidden="true" tabindex="-1"></a>plot_means<span class="sc">$</span>Stimulus <span class="ot">&lt;-</span> <span class="fu">factor</span>(plot_means<span class="sc">$</span>Stimulus, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Normal&quot;</span>, <span class="st">&quot;Bigrams&quot;</span>, <span class="st">&quot;Random&quot;</span>))</span>
<span id="cb19-15"><a href="lab-8-repeated-measures-anova.html#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="lab-8-repeated-measures-anova.html#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_means, <span class="fu">aes</span>(<span class="at">x=</span>Stimulus, <span class="at">y=</span>means, <span class="at">group=</span><span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb19-17"><a href="lab-8-repeated-measures-anova.html#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb19-18"><a href="lab-8-repeated-measures-anova.html#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>)<span class="sc">+</span></span>
<span id="cb19-19"><a href="lab-8-repeated-measures-anova.html#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>means<span class="sc">-</span>SEs, <span class="at">ymax=</span>means<span class="sc">+</span>SEs), <span class="at">width=</span>.<span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb19-20"><a href="lab-8-repeated-measures-anova.html#cb19-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb19-21"><a href="lab-8-repeated-measures-anova.html#cb19-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Mean Reaction Time (ms)&quot;</span>)<span class="sc">+</span></span>
<span id="cb19-22"><a href="lab-8-repeated-measures-anova.html#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Typing Material&quot;</span>)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="conduct-the-repeated-measures-anova" class="section level3 hasAnchor" number="8.4.6">
<h3><span class="header-section-number">8.4.6</span> Conduct the repeated Measures ANOVA<a href="lab-8-repeated-measures-anova.html#conduct-the-repeated-measures-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use the same <code>aov</code> function as we used last time. The only difference is that we add in a new part to the formula. Remember the formula for a one-factor between subjects ANOVA looked like this:</p>
<p><code>aov( DV ~ IV , dataframe)</code>, where DV is the name of the column with your independent variable, IV is the name of the column with your independent variable, and <code>dataframe</code> is the name of your data frame containing the means in each condition.</p>
<p>The formula for a repeated-measures ANOVA looks like this:</p>
<p><code>aov( DV ~ IV + Error(Subject/IV), dataframe)</code>. We have added <code>+ Error(Subject/IV)</code>. This tells R to use the appropriate error term for the repeated measures ANOVA. In the formula, <code>Subject</code> refers to the name of the column coding your subjects (make sure this is a factor in R), and <code>IV</code> is the name of the column for your independent variable.</p>
<p>The formula for our data would be: <code>aov( mean_rt ~ Stimulus + Error(Subject/Stimulus), subject_means)</code>.</p>
<p>Here is the code below. Just as reminder, the raw data codes every single key press on each row. We don’t want to submit this as the data frame to the <code>aov</code> function. Instead, we need to calculate the data frame for the subject means in each condition. We did that above as a step toward making the graphs. We do it again here to remind you that you need to do this.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="lab-8-repeated-measures-anova.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get subject means</span></span>
<span id="cb20-2"><a href="lab-8-repeated-measures-anova.html#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="lab-8-repeated-measures-anova.html#cb20-3" aria-hidden="true" tabindex="-1"></a>subject_means <span class="ot">&lt;-</span> all_data <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="lab-8-repeated-measures-anova.html#cb20-4" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">filter</span>(Order<span class="sc">==</span><span class="dv">1</span>, Correct<span class="sc">==</span><span class="dv">1</span>, PureRTs<span class="sc">&lt;</span><span class="dv">5000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="lab-8-repeated-measures-anova.html#cb20-5" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">group_by</span>(Subject, Stimulus) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="lab-8-repeated-measures-anova.html#cb20-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">summarise</span>(<span class="at">mean_rt =</span> <span class="fu">mean</span>(PureRTs))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Subject&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="lab-8-repeated-measures-anova.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure IV and Subject are coded as factors</span></span>
<span id="cb22-2"><a href="lab-8-repeated-measures-anova.html#cb22-2" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Subject  <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Subject)</span>
<span id="cb22-3"><a href="lab-8-repeated-measures-anova.html#cb22-3" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Stimulus <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Stimulus)</span>
<span id="cb22-4"><a href="lab-8-repeated-measures-anova.html#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="lab-8-repeated-measures-anova.html#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct the anova</span></span>
<span id="cb22-6"><a href="lab-8-repeated-measures-anova.html#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="lab-8-repeated-measures-anova.html#cb22-7" aria-hidden="true" tabindex="-1"></a>aov_out <span class="ot">&lt;-</span> <span class="fu">aov</span>( mean_rt <span class="sc">~</span> Stimulus <span class="sc">+</span> <span class="fu">Error</span>(Subject<span class="sc">/</span>Stimulus), subject_means)</span>
<span id="cb22-8"><a href="lab-8-repeated-measures-anova.html#cb22-8" aria-hidden="true" tabindex="-1"></a>summary_out <span class="ot">&lt;-</span> <span class="fu">summary</span>(aov_out)</span>
<span id="cb22-9"><a href="lab-8-repeated-measures-anova.html#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="lab-8-repeated-measures-anova.html#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xtable)</span></code></pre></div>
<pre><code>## Warning: package &#39;xtable&#39; was built under R version 4.1.1</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="lab-8-repeated-measures-anova.html#cb24-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">xtable</span>(summary_out))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Df</th>
<th align="right">Sum Sq</th>
<th align="right">Mean Sq</th>
<th align="right">F value</th>
<th align="right">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Residuals</td>
<td align="right">37</td>
<td align="right">3030779.9</td>
<td align="right">81912.970</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Stimulus</td>
<td align="right">2</td>
<td align="right">1157965.2</td>
<td align="right">578982.606</td>
<td align="right">230.5806</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Residuals1</td>
<td align="right">74</td>
<td align="right">185812.3</td>
<td align="right">2510.977</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<p>Great, we have conducted the ANOVA. We could write up the results of the ANOVA like this:</p>
<blockquote>
<p>For each subject we computed mean reactions for correct keystrokes in each condition of the Stimulus factor. These means were submitted to a one-factor repeated-measures ANOVA, with Stimulus (Normal, Bigrams, and Random) as the sole factor. The effect of Stimulus was signficant, F(2, 74) = 230.58, MSE = 2510.98, p &lt; 0.001.</p>
</blockquote>
<p>Note, the p-value shows up as a zero, that’s because it is so small that R doesn’t want to print the actual number 0.000000000000000…1.</p>
<p>What does this tell us?</p>
<ol style="list-style-type: decimal">
<li><p>The <span class="math inline">\(F\)</span> value we obtained (230.58) almost never occurs by chance. More specifically, the sampling distribution of F from the distribution of no differences virtually never produces a huge F like 230.58</p></li>
<li><p>It is super-duper unlikely that chance (sampling error) could have produced the difference we observed.</p></li>
<li><p>We reject the idea that chance caused the differences, and are very confident that the manipulation (changing the kinds of letters that people have to type), has a causal influence on reaction time in typing.</p></li>
</ol>
<div id="report-the-means-too" class="section level4 hasAnchor" number="8.4.6.1">
<h4><span class="header-section-number">8.4.6.1</span> Report the means too<a href="lab-8-repeated-measures-anova.html#report-the-means-too" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Remember, the important goal when conducting analyses, and then writing about them, is to tell people what you did and what you found. This involves more than one step. For this example, we might do three basic things. 1) make a figure to show the means, 2) report the ANOVA so people know if there is support for the inference that the differences between the means are not caused by chance, and 3) report descriptives for the means, so people know what the numbers are (the figure doesn’t show the exact values).</p>
<p>We’ve already made the figure and done the ANOVA, let’s report the condition means. To do this, we need to find the means for each condition, collapsing over the means for each subject in each condition. Note that, we already did this to make the figure. Here’s the code again:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="lab-8-repeated-measures-anova.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## get subject mean RTs</span></span>
<span id="cb25-2"><a href="lab-8-repeated-measures-anova.html#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="lab-8-repeated-measures-anova.html#cb25-3" aria-hidden="true" tabindex="-1"></a>subject_means <span class="ot">&lt;-</span> all_data <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="lab-8-repeated-measures-anova.html#cb25-4" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">filter</span>(Order<span class="sc">==</span><span class="dv">1</span>, Correct<span class="sc">==</span><span class="dv">1</span>, PureRTs<span class="sc">&lt;</span><span class="dv">5000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="lab-8-repeated-measures-anova.html#cb25-5" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">group_by</span>(Subject, Stimulus) <span class="sc">%&gt;%</span></span>
<span id="cb25-6"><a href="lab-8-repeated-measures-anova.html#cb25-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">summarise</span>(<span class="at">mean_rt =</span> <span class="fu">mean</span>(PureRTs))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Subject&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="lab-8-repeated-measures-anova.html#cb27-1" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Subject<span class="ot">&lt;-</span><span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Subject)</span>
<span id="cb27-2"><a href="lab-8-repeated-measures-anova.html#cb27-2" aria-hidden="true" tabindex="-1"></a>subject_means<span class="sc">$</span>Stimulus<span class="ot">&lt;-</span><span class="fu">as.factor</span>(subject_means<span class="sc">$</span>Stimulus)</span>
<span id="cb27-3"><a href="lab-8-repeated-measures-anova.html#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="lab-8-repeated-measures-anova.html#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="do">## get condition mean RTs</span></span>
<span id="cb27-5"><a href="lab-8-repeated-measures-anova.html#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="lab-8-repeated-measures-anova.html#cb27-6" aria-hidden="true" tabindex="-1"></a>plot_means <span class="ot">&lt;-</span> subject_means <span class="sc">%&gt;%</span></span>
<span id="cb27-7"><a href="lab-8-repeated-measures-anova.html#cb27-7" aria-hidden="true" tabindex="-1"></a>              <span class="fu">group_by</span>(Stimulus) <span class="sc">%&gt;%</span></span>
<span id="cb27-8"><a href="lab-8-repeated-measures-anova.html#cb27-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">means =</span> <span class="fu">mean</span>(mean_rt),</span>
<span id="cb27-9"><a href="lab-8-repeated-measures-anova.html#cb27-9" aria-hidden="true" tabindex="-1"></a>                        <span class="at">SEs =</span> <span class="fu">sd</span>(mean_rt)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(mean_rt)))</span>
<span id="cb27-10"><a href="lab-8-repeated-measures-anova.html#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="lab-8-repeated-measures-anova.html#cb27-11" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(plot_means)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Stimulus</th>
<th align="right">means</th>
<th align="right">SEs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bigrams</td>
<td align="right">924.8764</td>
<td align="right">26.69375</td>
</tr>
<tr class="even">
<td align="left">Normal</td>
<td align="right">833.1872</td>
<td align="right">24.00055</td>
</tr>
<tr class="odd">
<td align="left">Random</td>
<td align="right">1077.5361</td>
<td align="right">31.60979</td>
</tr>
</tbody>
</table>
<p>Now, our full write-up of the results would look like this.</p>
<blockquote>
<p>For each subject we computed mean reactions for correct keystrokes in each condition of the Stimulus factor. These means were submitted to a one-factor repeated-measures ANOVA, with Stimulus (Normal, Bigrams, and Random) as the sole factor. The effect of Stimulus was signficant, F(2, 74) = 230.58, MSE = 2510.98, p &lt; 0.001. The mean reaction time was fastest in the Normal condition (M = 833 ms, SE = 24 ms), followed by the Bigram condition, (M = 924 ms, SE = 27 ms) and slowest in the Random Condition (M = 1078 ms, SE = 32 ms).</p>
</blockquote>
</div>
</div>
<div id="follow-up-comparisons" class="section level3 hasAnchor" number="8.4.7">
<h3><span class="header-section-number">8.4.7</span> Follow-up comparisons<a href="lab-8-repeated-measures-anova.html#follow-up-comparisons" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The ANOVA tells us that the differences between the means are unlikely to be due to chance. But, remember, this is an omnibus test. It does not tell us if specific pairs of means are different from one another. To determine whether the difference between two specific means is not likely due to chance, we need to conduct follow-up tests.</p>
<p>Because this is a repeated-measures design, we can use the paired-samples t-test for follow-up tests. Let’s do two follow-up tests to confirm that the RTs for Normal words were indeed faster than the RTs for the Bigram condition (word-like non-words); and then, let’s confirm that the RTs for the Bigram condition were indeed faster than the RTs for the Random condition.</p>
<div id="normal-vs-bigrams" class="section level4 hasAnchor" number="8.4.7.1">
<h4><span class="header-section-number">8.4.7.1</span> Normal vs Bigrams<a href="lab-8-repeated-measures-anova.html#normal-vs-bigrams" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We use the <code>subject_means</code> data frame. But, we want to rid of all the rows containing the means from the Random condition. We use filter to do that, then we conduct the paired-samples t-test.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="lab-8-repeated-measures-anova.html#cb28-1" aria-hidden="true" tabindex="-1"></a>comparison_df <span class="ot">&lt;-</span> subject_means <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="lab-8-repeated-measures-anova.html#cb28-2" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">filter</span>(Stimulus <span class="sc">!=</span> <span class="st">&quot;Random&quot;</span>)</span>
<span id="cb28-3"><a href="lab-8-repeated-measures-anova.html#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="lab-8-repeated-measures-anova.html#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mean_rt<span class="sc">~</span>Stimulus, </span>
<span id="cb28-5"><a href="lab-8-repeated-measures-anova.html#cb28-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired=</span><span class="cn">TRUE</span>, </span>
<span id="cb28-6"><a href="lab-8-repeated-measures-anova.html#cb28-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal=</span><span class="cn">TRUE</span>, </span>
<span id="cb28-7"><a href="lab-8-repeated-measures-anova.html#cb28-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> comparison_df)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  mean_rt by Stimulus
## t = 12.14, df = 37, p-value = 1.807e-14
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   76.38601 106.99253
## sample estimates:
## mean of the differences 
##                91.68927</code></pre>
</div>
<div id="bigrams-vs-random" class="section level4 hasAnchor" number="8.4.7.2">
<h4><span class="header-section-number">8.4.7.2</span> Bigrams vs Random<a href="lab-8-repeated-measures-anova.html#bigrams-vs-random" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We use the <code>subject_means</code> data frame. But, we want to rid of all the rows containing the means from the Normal condition. We use filter to do that, then we conduct the paired-samples t-test.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="lab-8-repeated-measures-anova.html#cb30-1" aria-hidden="true" tabindex="-1"></a>comparison_df <span class="ot">&lt;-</span> subject_means <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="lab-8-repeated-measures-anova.html#cb30-2" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">filter</span>(Stimulus <span class="sc">!=</span> <span class="st">&quot;Normal&quot;</span>)</span>
<span id="cb30-3"><a href="lab-8-repeated-measures-anova.html#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="lab-8-repeated-measures-anova.html#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mean_rt<span class="sc">~</span>Stimulus, </span>
<span id="cb30-5"><a href="lab-8-repeated-measures-anova.html#cb30-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired=</span><span class="cn">TRUE</span>, </span>
<span id="cb30-6"><a href="lab-8-repeated-measures-anova.html#cb30-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal=</span><span class="cn">TRUE</span>, </span>
<span id="cb30-7"><a href="lab-8-repeated-measures-anova.html#cb30-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> comparison_df)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  mean_rt by Stimulus
## t = -14.212, df = 37, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -174.4245 -130.8949
## sample estimates:
## mean of the differences 
##               -152.6597</code></pre>
</div>
</div>
<div id="reporting-everything" class="section level3 hasAnchor" number="8.4.8">
<h3><span class="header-section-number">8.4.8</span> Reporting everything<a href="lab-8-repeated-measures-anova.html#reporting-everything" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now we can look at some write-ups that report everything we did, and everything we want to know. I’ll show you two ways to do it.</p>
<div id="first-way" class="section level4 hasAnchor" number="8.4.8.1">
<h4><span class="header-section-number">8.4.8.1</span> First way<a href="lab-8-repeated-measures-anova.html#first-way" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In the first way, we embed the results of the t-test into the description of the mean reaction times.</p>
<p>For each subject we computed mean reactions for correct keystrokes in each condition of the Stimulus factor. These means were submitted to a one-factor repeated-measures ANOVA, with Stimulus (Normal, Bigrams, and Random) as the sole factor. The effect of Stimulus was significant, F(2, 74) = 230.58, MSE = 2510.98, p &lt; 0.001. The mean reaction time was significantly faster in the Normal condition (M = 833 ms, SE = 24 ms), compared to the Bigram condition, (M = 924 ms, SE = 27 ms), t(37) = 12.14, p&lt;0.001. Additionally, mean reactions in the Bigram condition were significantly faster than the Random Condition (M = 1078 ms, SE = 32 ms), t(37) = 14.21, p &lt; 0.001.</p>
</div>
<div id="second-way" class="section level4 hasAnchor" number="8.4.8.2">
<h4><span class="header-section-number">8.4.8.2</span> Second way<a href="lab-8-repeated-measures-anova.html#second-way" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In the second way, we first report the means as we did the very first time, and then after that we report the t-test results to highlight the size the of the differences between each comparison.</p>
<p>For each subject we computed mean reactions for correct keystrokes in each condition of the Stimulus factor. These means were submitted to a one-factor repeated-measures ANOVA, with Stimulus (Normal, Bigrams, and Random) as the sole factor. The effect of Stimulus was significant, F(2, 74) = 230.58, MSE = 2510.98, p &lt; 0.001. The mean reaction time was fastest in the Normal condition (M = 833 ms, SE = 24 ms), followed by the Bigram condition, (M = 924 ms, SE = 27 ms) and slowest in the Random Condition (M = 1078 ms, SE = 32 ms). Mean reaction times were significantly faster (M = 91 ms) in the Normal than Bigrams condition, t(37) = 12.14, p &lt; 0.001. And, mean reaction times were significantly faster (M = 152 ms) in the Bigrams than Random condition, t(37) = 14.21, p &lt; 0.01.</p>
<p>There are other ways to write-up statistical results. These are just some example recipes. The important thing is to:</p>
<ol style="list-style-type: decimal">
<li>Say what the numbers were that you are analyzing</li>
<li>Say what the statistical test was</li>
<li>Say the results of the statistical test</li>
<li>Say what the patterns of means were</li>
<li>Say what the follow-up tests were when you test differences between specific means.</li>
<li>Add a table or figure so it is easier to “see” the results.</li>
</ol>
</div>
</div>
<div id="generalization-exercise-6" class="section level3 hasAnchor" number="8.4.9">
<h3><span class="header-section-number">8.4.9</span> Generalization Exercise<a href="lab-8-repeated-measures-anova.html#generalization-exercise-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Your task is to conduct another repeated-measures ANOVA. Rather than using the reaction time for the first-keystroke as the dependent measure, you will use the reaction times between all of the keystrokes in each word, these are called interkeystroke intervals. The <code>Order</code> variable is used to code keystroke position (1 to 5). You will want to analyze only the <code>PureRTs</code> that have an <code>Order</code> greater than 1. For example, you could use the following code to get the subject_means for the mean interkeystroke intervals.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="lab-8-repeated-measures-anova.html#cb32-1" aria-hidden="true" tabindex="-1"></a>subject_means <span class="ot">&lt;-</span> all_data <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="lab-8-repeated-measures-anova.html#cb32-2" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">filter</span>(Order <span class="sc">&gt;</span> <span class="dv">1</span>, Correct<span class="sc">==</span><span class="dv">1</span>, PureRTs<span class="sc">&lt;</span><span class="dv">5000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="lab-8-repeated-measures-anova.html#cb32-3" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">group_by</span>(Subject, Stimulus) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="lab-8-repeated-measures-anova.html#cb32-4" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">summarise</span>(<span class="at">mean_rt =</span> <span class="fu">mean</span>(PureRTs))</span></code></pre></div>
<p>A. Make a figure for the new DV
B. Report the ANOVA table for the new repeated measures ANOVA
C. Discuss whether the general pattern is the same as before.</p>
</div>
<div id="writing-assignment-6" class="section level3 hasAnchor" number="8.4.10">
<h3><span class="header-section-number">8.4.10</span> Writing assignment<a href="lab-8-repeated-measures-anova.html#writing-assignment-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>(2 points - Graded)</p>
<ol style="list-style-type: decimal">
<li><p>Explain the concept of <span class="math inline">\(SS_\text{Total}\)</span> (.5 points)</p></li>
<li><p>Explain the concept of partitioning SS_ into smaller pieces. What is the goal of the spitting? (.5 points)</p></li>
<li><p>Explain the major difference between a between-subjects ANOVA and repeated-measures ANOVA in terms of what is being partioned. (1 point)</p></li>
</ol>
<p>General grading.</p>
<ul>
<li>You will receive 0 points for missing answers</li>
<li>You must write in complete sentences. Point form sentences will be given 0 points.</li>
<li>Completely incorrect answers will receive 0 points.</li>
<li>If your answer is generally correct but very difficult to understand and unclear you may receive half points for the question</li>
</ul>
</div>
</div>
<div id="excel-8" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Excel<a href="lab-8-repeated-measures-anova.html#excel-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How to do it in Excel</p>
</div>
<div id="spss-8" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> SPSS<a href="lab-8-repeated-measures-anova.html#spss-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this lab, we will use SPSS to:</p>
<ol style="list-style-type: decimal">
<li>Produce a frequency histogram and remove outliers</li>
<li>Conduct and graph One-Factor Repeated Measures ANOVA</li>
<li>Conduct planned comparisons using a paired-samples t-test</li>
</ol>
<div id="experiment-background-5" class="section level3 hasAnchor" number="8.6.1">
<h3><span class="header-section-number">8.6.1</span> Experiment Background<a href="lab-8-repeated-measures-anova.html#experiment-background-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>In this experiment, Behmer and Crump (2017) recruited 38 subjects to type words presented on a screen as quickly as they could. The independent variable was typing material and it had 3 levels: Normal (5 letter English words), Bigrams (5 letter non-words that have properties like real words), and Random (random 5 letter strings). The authors wanted to know whether reaction time (RT) was different according to the type of word being typed.</p>
<p>Dependent Variables: There were three dependent variables, that all measured different aspects of typing performance. Reaction times (RTs) were defined as the temporal interval between seeing a stimulus (to type), and then starting to type it (first key press). Inter-keystroke intervals (IKSIs) are the times between each key-press. Last, accuracy was also measured (correct or incorrect key-presses). For this analysis we will use <code>Pure RTs</code> as our one DV.</p>
<p>Nota bene: This is a repeated measures design because each participant typed letter strings from the word, bigrams, and random conditions.</p>
</div>
<div id="produce-a-frequency-histogram-and-remove-outliers" class="section level3 hasAnchor" number="8.6.2">
<h3><span class="header-section-number">8.6.2</span> Produce a frequency histogram and remove outliers<a href="lab-8-repeated-measures-anova.html#produce-a-frequency-histogram-and-remove-outliers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p><a href="https://github.com/CrumpLab/statisticsLab/blob/master/data/spssdata/BehmerCrump.sav">Here</a> is a link to the data file. It is named BehmerCrump.sav. Your data should look like this:</p>
<p><img src="img/9.4.11.png" /><!-- --></p>
<p>First, we’ll be creating a histogram to look at our data. Go to <span style="color:blue">Graphs</span>, then <span style="color:blue">Legacy Dialogs</span>, then <span style="color:blue">Histogram…</span></p>
<p><img src="img/9.4.12.png" /><!-- --></p>
<p>The next window will ask you to specify the variable you would like graphed. Choose <code>PureRTs</code> from the list on the left and move it into the “Variable” field using the arrow.</p>
<p><img src="img/9.4.13.png" /><!-- --></p>
<p>Click <span style="color:blue">OK</span>. SPSS will produce a frequency histogram of your data.</p>
<p><img src="img/9.4.14.png" /><!-- --></p>
<p>Notice that the RTs form a positively skewed distribution. Most RT measurements are on the lower end of the scale, and there are very few RTs that are higher than 5000ms. These measurements could have resulted from subjects falling asleep, looking at their phones, or being otherwise distracted in the middle of the experiment. We want to remove those values so they do not influence and mischaracterize our results. To do this, go to the top menu and choose <span style="color:blue">Data</span>, then <span style="color:blue">Select Cases…</span></p>
<p><img src="img/9.4.15.png" /><!-- --></p>
<p>The next window will ask you which cases to select. We specifically want to remove any cases larger than 5000, so check off <span style="color:blue">If condition is satisfied:</span></p>
<p><img src="img/9.4.16.png" /><!-- --></p>
<p>Then click <span style="color:blue">If…</span> The window that follows will ask you to specify the condition for inclusion. Find the variable <code>PureRTs</code> in the left-hand list and move it to the field on top using the arrow. Then, type “&lt; 5000” to specify that we want to keep only values under 5000ms.</p>
<p><img src="img/9.4.17.png" /><!-- --></p>
<p>Click <span style="color:blue">Continue</span>. Your data has now been edited so that trials on which the <code>PureRTs</code> value was greater than 5000 have been removed.</p>
<p>Let’s take some time to think about this data. We have measurements taken from many participants across multiple trials and multiple conditions. Our goal is to be able to come up with a single RT for each person per condition. The only way to do this is to take an individual’s RTs for a particular condition and average them. To do this, we need to calculate means. First, go to <span style="color:blue">Analyze</span>, then <span style="color:blue">Compare Means</span>, then <span style="color:blue"> Means…</span></p>
<p><img src="img/9.4.18.png" /><!-- --></p>
<p>In the next window, move the <code>PureRTs</code> variable into the “Dependent List” field. In the field below, labeled “Independent List”, place the <code>Subject</code> variable:</p>
<p><img src="img/9.4.19.png" /><!-- --></p>
<p>Then, click <span style="color:blue">Next</span>. The bottom field will become blank again, and you can now place the <code>Stimulus</code> variable into it.</p>
<p><img src="img/9.4.20.png" /><!-- --></p>
<p>Click <span style="color:blue">OK</span>. SPSS will produce an output table containing each subject’s average RT per condition:</p>
<p><img src="img/9.4.21.png" /><!-- --></p>
</div>
<div id="conduct-and-graph-one-factor-repeated-measures-anova" class="section level3 hasAnchor" number="8.6.3">
<h3><span class="header-section-number">8.6.3</span> Conduct and graph One-Factor Repeated Measures ANOVA<a href="lab-8-repeated-measures-anova.html#conduct-and-graph-one-factor-repeated-measures-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>For this part of the tutorial, we will switch over to a new SPSS file. <a href="https://github.com/CrumpLab/statisticsLab/blob/master/data/spssdata/BehmerCrumpMeanRTs.sav">Here</a> is the link; it’s called BehmerCrumpMeanRTs.sav. When you open the file, it should look like this:</p>
<p><img src="img/9.4.22.png" /><!-- --></p>
<p>Notice that this file contains the means from the table we just created. Each person’s data is contained within a row: there are 3 measurements corresponding to all stimulus conditions. To calculate a One-Factor Repeated Measures ANOVA, go to <span style="color:blue">Analyze</span>, then <span style="color:blue">General Linear Model</span>, then <span style="color:blue">Repeated Measures…</span></p>
<p><img src="img/9.4.23.png" /><!-- --></p>
<p>The next window will ask you to label your within-subjects variable. Type <code>Stimulus</code> into the “Within-Subjects Factor Name” field. Indicate that this variable has 3 levels. Then click <span style="color:blue">Add</span>, and then <span style="color:blue">Define</span>.</p>
<p><img src="img/9.4.24.png" /><!-- --></p>
<p>In the next window, move all 3 conditions listed on the left into the “Within-Subjects Variables” field.</p>
<p><img src="img/9.4.25.png" /><!-- --></p>
<p>Click <span style="color:blue">OK</span>. SPSS will produce an output table labeled “Tests of Within-SUbjects Effects” that contains The F statistic and its corresponding p-value.</p>
<p><img src="img/9.4.26.png" /><!-- --></p>
<p>From this table, we see that there is a significant effect of stimulus on RT, F(2, 74)= 420.33, p&lt;.05. In order to graph this data and look at the means, go to <span style="color:blue">Graphs</span>, then <span style="color:blue">Legacy Dialogs</span>, then <span style="color:blue">Bar…</span></p>
<p><img src="img/9.4.27.png" /><!-- --></p>
<p>In the next window, choose <span style="color:blue">Simple</span>, but this time select <span style="color:blue">Summaries of separate variables</span>, then <span style="color:blue">Define</span>:</p>
<p><img src="img/9.4.28.png" /><!-- --></p>
<p>In the next window, move the three stimulus conditions listed in the field on the left into the field labeled “Bars Represent.”</p>
<p><img src="img/9.4.29.png" /><!-- --></p>
<p>Then click <span style="color:blue">OK</span>. SPSS will produce a bar graph with each bar representing the mean of each of the conditions. We can see that the Random condition has the longest RT, followed by Bigrams, and then Normal. However, at this point we do not know which groups are significantly different from the others.</p>
<p><img src="img/9.4.30.png" /><!-- --></p>
</div>
<div id="conduct-planned-comparisons-using-a-paired-samples-t-test" class="section level3 hasAnchor" number="8.6.4">
<h3><span class="header-section-number">8.6.4</span> Conduct planned comparisons using a paired-samples t-test<a href="lab-8-repeated-measures-anova.html#conduct-planned-comparisons-using-a-paired-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>To find out where the difference among these 3 conditions exists, we will use a planned comparison in the form of a paired-samples t-test. This method takes 2 groups at a time and tests for pairwise differences. There are three comparisons that can be made here:</p>
<ol style="list-style-type: decimal">
<li>normal vs. bigram</li>
<li>bigram vs. random</li>
<li>random vs. normal</li>
</ol>
<p>We will use a paired-samples t-test instead of an independent-samples t-test because in each comparison, the same people are being remeasured in each group.</p>
<p>To begin, go to <span style="color:blue">Analyze</span>, then <span style="color:blue">Compare Means</span>, then <span style="color:blue">Paired Samples T-test…</span></p>
<p><img src="img/9.4.31.png" /><!-- --></p>
<p>In the next window, move the two conditions of our first pairwise comparison (<code>normal</code> vs. <code>bigram</code>) into the field on the right using the arrow.</p>
<p><img src="img/9.4.32.png" /><!-- --></p>
<p>Click <span style="color:blue">OK</span>. SPSS will produce a series of tables. The “Paired Samples test” table contains the t-statistic and its associated p-value.</p>
<p><img src="img/9.4.33.png" /><!-- --></p>
<p>Looking at this output, we can see that the Normal and Bigrams conditions are indeed significantly different, t(37)= 13.09, p&lt;.05.</p>
<p>You can use this same method for the remaining comparisons.</p>
</div>
<div id="practice-problems-4" class="section level3 hasAnchor" number="8.6.5">
<h3><span class="header-section-number">8.6.5</span> Practice Problems<a href="lab-8-repeated-measures-anova.html#practice-problems-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<ol style="list-style-type: decimal">
<li><p>Run the same analysis as illustrated in this lab tutorial but with accuracy (correct) as the dependent variable. Use an alpha level of .05. Remember to calculate means per subject and stimulus first. This will generate a table, whose values you can enter into a new SPSS spreadsheet file.</p></li>
<li><p>Is there an effect of stimulus on error rate? If so, conduct the appropriate planned comparisons.</p></li>
<li><p>Graph the means using a bar graph; include +/-1 SEM Error bars.</p></li>
</ol>
</div>
</div>
<div id="jamovi-1" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> JAMOVI<a href="lab-8-repeated-measures-anova.html#jamovi-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<hr />
<div class="marginnote">
<p>This section is copied, almost verbatim, with some editorial changes, from <a href="https://www.erinmazerolle.com/statisticsLab/lab-8-repeated-measures-anova.html#spss-8">Answering questions with data: The lab manual for R, Excel, SPSS and JAMOVI, Lab 8, Section 8.6, SPSS</a>, according to its <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.ast">CC license</a>. Thank you to Crump, Krishnan, Volz, &amp; Chavarga (2018).</p>
</div>
<p>In this lab, we will use JAMOVI to:</p>
<ol style="list-style-type: decimal">
<li>Conduct and graph One-Factor Repeated Measures ANOVA</li>
<li>Conduct follow-up tests</li>
</ol>
<div id="experiment-background-6" class="section level3 hasAnchor" number="8.7.1">
<h3><span class="header-section-number">8.7.1</span> Experiment Background<a href="lab-8-repeated-measures-anova.html#experiment-background-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p>As described in more detail at the <a href="https://www.erinmazerolle.com/statisticsLab/lab-8-repeated-measures-anova.html#betcha-cant-type-jhdbzkco-very-fast-on-your-first-try">beginning of this lab manual section</a>, Behmer and Crump (2017) recruited 38 subjects to type words presented on a screen as quickly as they could. The independent variable was typing material and it had 3 levels: Normal (5 letter English words), Bigrams (5 letter non-words that have properties like real words), and Random (random 5 letter strings). The authors wanted to know whether reaction time (RT) was different according to the type of word being typed.</p>
<p>Dependent Variables: There were three dependent variables, that all measured different aspects of typing performance. Reaction times (RTs) were defined as the temporal interval between seeing a stimulus (to type), and then starting to type it (first key press). Inter-keystroke intervals (IKSIs) are the times between each key-press. Last, accuracy was also measured (correct or incorrect key-presses). For this analysis we will use <code>Pure RTs</code> as our one DV.</p>
<p>Nota bene: This is a repeated measures design because each participant typed letter strings from the Normal, Bigrams, and Random conditions.</p>
</div>
<div id="checking-assumptions-1" class="section level3 hasAnchor" number="8.7.2">
<h3><span class="header-section-number">8.7.2</span> Checking Assumptions<a href="lab-8-repeated-measures-anova.html#checking-assumptions-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall that the Repeated Measures ANOVA assumes:</p>
<ol style="list-style-type: decimal">
<li><p>The sampling distributions are normally distributed. Consider the central limit theorem and/or histograms.</p></li>
<li><p>The data are measured using an interval or a ratio scale. Consider what you know about how the data were collected and/or look at the variable attributes in the JAMOVI data spreadsheet.</p></li>
<li><p>The data are spherical. (No two conditions are any more dependent than any other two. OR There is equal correlation among pairs of conditions. OR There is equal variance among differences between pairs of conditions.) To test this, we use Mauchly’s test. This test can be requested when you run the Repeated Measures ANOVA in JAMOVI.</p></li>
</ol>
<p><strong>Challenge</strong>: On your own and using the data set to be used in our lab demonstration, check the first two assumptions. Were these assumptions met or violated? How do you know? (<strong>Be prepared to answer these questions at the beginning of lab.</strong>)</p>
</div>
<div id="conduct-and-graph-one-factor-repeated-measures-anova-1" class="section level3 hasAnchor" number="8.7.3">
<h3><span class="header-section-number">8.7.3</span> Conduct and graph One-Factor Repeated Measures ANOVA<a href="lab-8-repeated-measures-anova.html#conduct-and-graph-one-factor-repeated-measures-anova-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<p><a href="https://moodle.stfx.ca/mod/resource/view.php?id=926115">Here</a> is the link to the data set we will use; it’s called BehmerCrumpMeanRTs.omv. When you open the file, it should look like this:</p>
<p><img src="img/BehmerCrump_FileView.png" /><!-- --></p>
<p>Notice that this file contains means. Each person’s data is contained within a row: there are 3 measurements corresponding to all stimulus conditions. To calculate a One-Factor Repeated Measures ANOVA, go to <span style="color:blue">Analyses</span>, <span style="color:blue">ANOVA</span>, and then <span style="color:blue">Repeated Measures ANOVA</span>.</p>
<p><img src="img/RM_ANOVACommands.png" /><!-- --></p>
<p>In the pane where you enter the commands, you can label your within-subjects variable. In the window called “Repeated Measures Factors,” type the name after highlighting or clicking in the area where you read “RM Factor 1”. Remember, we are looking at a <strong>One-Factor</strong> Repeated Measures ANOVA, so we only need to concern ourselves with this section. In other words, we do not have other “factors” to consider (We can ignore “RM Factor 2”.).</p>
<p><img src="img/RM_ANOVA_NamingTheFactor.png" /><!-- --></p>
<p>At this point, we need to define the levels of this factor. Notice that only two levels are being displayed in JAMOVI under the “Repeated Measures Factors” window. In its font colour, “Level 3” is light grey, rather than black. (<em>Even if we move the names of the levels into the “Repeated Measures Cells,” JAMOVI does not rename the levels above.</em>) If you want the names of the levels to show in your output, type the names of the levels in where you see Level 1, Level 2, and so on in the “Repeated Measures Factors” window.</p>
<p><img src="img/RM_ANOVA_NamingTheLevels.png" /><!-- --></p>
<p>Then, you should highlight and <strong>drag</strong> each and every level of the factor (aka variable) from the window on the left to the corresponding area in the “Repeated Measures Cells” window on the right.</p>
<p><img src="img/RM_ANOVA_BigramsMoved.png" /><!-- --></p>
<p><img src="img/RM_ANOVA_NormalMoved.png" /><!-- --></p>
<p><img src="img/RM_ANOVA_RandomMoved.png" /><!-- --></p>
<p>Before we can look at the results JAMOVI has been generating in the Results pane, we should request Mauchly’s test. To do this, move down in commands pane (on the left), and under the “Assumption Checks” ribbon, select <span style="color:blue">Sphericity tests</span>. Just in case the assumption of sphericity is violated, you could request corrections at this time; click <span style="color:blue">Greenhouse-Geisser</span>.</p>
<p><img src="img/RM_ANOVA_Sphericity.png" /><!-- --></p>
<p>JAMOVI will produce a few tables in the Results pane. Much like you checked the results of Levene’s test before moving ahead to read the One-Way ANOVA table (when you performed a One-Factor or One-Way ANOVA), you should check the results of Mauchly’s test before moving ahead to read the Repeated Measures ANOVA table. Let’s do that; let’s check the results of Mauchly’s test.</p>
<p><img src="img/RM_ANOVA_MauchlysTestResults.png" /><!-- --></p>
<p>Mauchly’s test indicates a significant result, <em>p</em> &lt; .0001. The assumption of sphericity is violated. We should read the results of the Repeated Measures ANOVA table with the sphericity correction, the Greenhouse-Geisser correction, applied.</p>
<p><img src="img/RM_ANOVA_Results.png" /><!-- --></p>
<p>To make it easier for you to read, let’s cover any information that we will not use in our interpretation of the results.</p>
<p><img src="img/RM_ANOVA_Results_Simplified.png" /><!-- --></p>
<p>From this table, we see that there is a significant effect of stimulus (or typing material) on reaction time because <em>p</em> &lt; .0001. We might say it more formally as follows:</p>
<p>A one-way repeated measures ANOVA was conducted, and Greenhouse-Geisser estimates of sphericity were used to correct the degrees of freedom (ε = .59) because Mauchly’s test indicated a violation to the assumption, <em>p</em> &lt; .05. The mean reaction times were significantly different among the types of stimulus, <em>F</em>(1.17, 43.46) = 420.33, <em>p</em> &lt; .0001.</p>
<p>Have a look at the two tables from which these results were taken. Can you see where these statistics were taken from?</p>
<p><img src="img/RM_ANOVA_MauchlysTestResults.png" /><!-- --></p>
<p><img src="img/RM_ANOVA_Results_Simplified.png" /><!-- --></p>
<p>Remember this is an omnibus ANOVA result. We do not know how many differences among means exist or between which means they would be found.</p>
<p>In order to graph this data and look at the means, go to back into the analysis commands. Remember, you can do this by clicking on the results generated in the Results pane. The commands will appear on the left of your JAMOVI file. Now, scroll down to the “Estimated Marginal Means” ribbon. Move the factor (in our example, <code>Typing_Material_Condition</code>, to the Marginal Means window under “Term 1”. Then, under “Output”, select <span style="color:blue">Marginal means plot</span> and <span style="color:blue">Marginal means tables</span>.</p>
<p><img src="img/RM_ANOVA_Graph.png" /><!-- --></p>
<p>In the Results pane, you should now see a graph and a table.</p>
<p><img src="img/RM_ANOVA_GraphOfMeans_Results.png" /><!-- --></p>
<p><img src="img/RM_ANOVA_EMMTable_Results.png" /><!-- --></p>
<p><strong>Think about an answer to this question</strong>: Looking at the graph and considering the mean of each level, where would you guess at least one significant difference in mean reaction times between stimulus levels might be found?</p>
<p>To the best of our knowledge, there is currently no way to request a bar graph depicting all three means using JAMOVI.</p>
</div>
<div id="conduct-follow-up-tests" class="section level3 hasAnchor" number="8.7.4">
<h3><span class="header-section-number">8.7.4</span> Conduct follow-up tests<a href="lab-8-repeated-measures-anova.html#conduct-follow-up-tests" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="planned-comparisons-2" class="section level4 hasAnchor" number="8.7.4.1">
<h4><span class="header-section-number">8.7.4.1</span> Planned comparisons<a href="lab-8-repeated-measures-anova.html#planned-comparisons-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If you had <em>a priori</em> hypotheses about where the difference(s) may be, you would conduct planned comparisons. In JAMOVI, there is no easy way for us to request these planned comparisons because there are no built-in or programmed contrasts, and there is no way to chunk variance. As such, you would do conduct planned comparisons in JAMOVI by conducting paired-samples <em>t</em>-tests because, in each comparison, the reactions times are being measured from the same people.</p>
</div>
<div id="post-hoc-tests" class="section level4 hasAnchor" number="8.7.4.2">
<h4><span class="header-section-number">8.7.4.2</span> <em>Post-hoc</em> tests<a href="lab-8-repeated-measures-anova.html#post-hoc-tests" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If you had no <em>a priori</em> hypotheses about where the difference(s) may be, you would conduct unplanned comparisons, or <em>post-hoc</em> tests. To find out where the difference among these 3 conditions exists, we will use <em>post-hoc</em> tests.
We could go through the menus again to request the <em>post-hoc</em> tests, or we could simplify the output in the Results pane by clicking on the Results to have the commands pop up to the left. Let’s do the latter. Next, scroll down to the “Post Hoc Tests” ribbon, move the factor (<code>Typing_Material_Condition</code>) to the window on the right, and then select the correction you want applied. Let’s select <span style="color:blue">Bonferroni</span>.</p>
<p><img src="img/RM_ANOVA_PostHocCommands.png" /><!-- --></p>
<p>JAMOVI will produce a new table in the Results pane. It will appear before the graph JAMOVI created based on commands entered previously.</p>
<p><img src="img/RM_ANOVA_PostHocResults.png" /><!-- --></p>
<p>Before reading ahead, <strong>think about this</strong>: We had already written information about the results of the omnibus ANOVA. What would we now add to this write-up to help readers understand the significant result in more detail?</p>
<p>If we wish to view and report the descriptive statistics, we could find the mean reaction times for each level (typing material condition), as well as the 95% confidence interval, in the “Estimated Marginal Means” table in the Results pane. This table does not give us the standard deviation, though. To get the standard deviations, use the commands with which you are familiar: <span style="color:blue">Analyses</span>, <span style="color:blue">Exploration</span>, and <span style="color:blue">Descriptives</span>.</p>
<p><img src="img/RM_ANOVA_DescStats.png" /><!-- --></p>
<p>To get the effect sizes, you will need to calculate Cohen’s <em>d</em>. An appropriate formula to use follows:</p>
<p><img src="img/RM_ANOVA_Cohensd.png" /><!-- --></p>
<p>We will need to calculate the effect size for each comparison we will report. Remember, there were three unique comparisons. We can take the mean difference from the “Post Hoc Comparisons” table or fill in each pair of means and take the difference.
The calculation of effect size for the comparison between the Bigram and Normal conditions follows:</p>
<p><img src="img/EffectSize_BigramsVsNormal.png" /><!-- --></p>
<p>The calculation of effect size for the comparison between the Bigram and Random conditions follows:</p>
<p><img src="img/EffectSize_BigramsVsRandom.png" /><!-- --></p>
<p>The calculation of effect size for the comparison between the Normal and Normal conditions follows:</p>
<p><img src="img/EffectSize_NormalVsRandom.png" /><!-- --></p>
<p>Based on the statistics presented in tables presented in this section, we would add to what we had already formally written about the omnibus ANOVA and construct a Results section something like this:</p>
<p>A one-way repeated measures ANOVA was conducted, and Greenhouse-Geisser estimates of sphericity were used to correct the degrees of freedom (ε = .59) because Mauchly’s test indicated a violation to the assumption, <em>p</em> &lt; .05. The mean reaction times were significantly different among the types of stimulus, <em>F</em>(1.17, 43.46) = 420.33, <em>p</em> &lt; .0001. <em>Post-hoc</em> pairwise comparisons with Bonferroni corrections were performed. It was found that mean reaction time in the Bigram condition (<em>M</em> = 431.99, <em>SD</em> = 103.63, 95% CI [397.93, 466.05]) was significantly different from that in the Normal condition (<em>M</em> = 365.76, <em>SD</em> = 85.69, 95% CI [337.60, 393.93]), <em>p</em> &lt; .0001, <em>d</em> = 0.64, and the mean reaction time in the Bigram condition was also significantly different from that in the Random condition (<em>M</em> = 596.23, <em>SD</em> = 139.77, 95% CI [550.29, 642.29]), <em>p</em> &lt; .0001, <em>d</em> = -1.58. Furthermore, the mean reaction time in the Normal condition was significantly different from that in the Random condition, <em>p</em> &lt; .0001, <em>d</em> = -2.69.</p>
</div>
</div>
<div id="some-apa-formatting-reminders-for-writing-results-sections-2" class="section level3 hasAnchor" number="8.7.5">
<h3><span class="header-section-number">8.7.5</span> Some APA formatting reminders for writing results sections<a href="lab-8-repeated-measures-anova.html#some-apa-formatting-reminders-for-writing-results-sections-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Always note the name of the test you performed (in this case, one-way analysis of variance, or ANOVA) and whether the result is significant or non-significant <em>(<strong>Note</strong>: We do not use the word insignificant.)</em>.</p></li>
<li><p>We usually round to two decimal places, except for <em>p</em>-values. If your <em>p</em>-value was .0001, it would be okay to write <em>p</em> = .0001 or <em>p</em> &lt; .001.</p></li>
<li><p>Do not include a leading 0 before the decimal for the <em>p</em>-value (<em>p</em> = .001 not <em>p</em> = 0.001, or <em>p</em> &lt; .05 not <em>p</em> &lt; 0.05) or before ε (ex. ε = .59 not ε = 0.59).</p>
<div class="marginnote">
<p>Yes, I’m serious. No, I don’t know why. Yes, it does seem a bit silly. Yes, you lose points if you don’t adhere to APA format when requested to do so.</p>
</div></li>
<li><p>Pay attention to spaces, parentheses, etc. APA is very picky about that. For example, it’s <em>F</em>(3, 35.75) = 6.08 <strong>not</strong> <em>F</em>(3,35.75)=6.08. There are spaces on either side of =, &gt;, or &lt; symbols.</p></li>
<li><p>Italicize symbols such as <em>M</em>, <em>SD</em>, <em>p</em>, <em>t</em>, <em>d</em>, and <em>F</em>.</p></li>
</ol>
</div>
<div id="homework-5" class="section level3 hasAnchor" number="8.7.6">
<h3><span class="header-section-number">8.7.6</span> Homework<a href="lab-8-repeated-measures-anova.html#homework-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>See <a href="https://moodle.stfx.ca/course/view.php?id=28797">Moodle</a>.</p>
</div>
<div id="practice-problems-5" class="section level3 hasAnchor" number="8.7.7">
<h3><span class="header-section-number">8.7.7</span> Practice Problems<a href="lab-8-repeated-measures-anova.html#practice-problems-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>In the lab demonstration, we saw that the assumption of sphericity was violated. Try changing data points until the assumption is upheld.</p></li>
<li><p>In the lab demonstration, we saw that the assumption of sphericity was violated. Try changing data points until the assumption is upheld while aiming to minimize the changes you make overall.</p></li>
<li><p>Use the Mean Accuracy Scores 2 <a href="https://moodle.stfx.ca/mod/resource/view.php?id=926491">data set</a> to practice checking assumptions and running a repeated measures ANOVA with follow-up testsing.</p></li>
<li><p>When we discussed <em>t</em>-tests, we talked about the Mehr, Song, and Spelke (2016) study. Have a look at that <a href="https://moodle.stfx.ca/mod/resource/view.php?id=901715">data set</a>, and try to develop a research question that might be answered with a repeated measures ANOVA. (<em>Hint</em>: It is okay to use only the variable name, rather than the phrase for what was measured, in your research question.)</p></li>
</ol>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lab-7-one-way-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lab-9-factorial-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/CrumpLab/statisticsLab/blob/master/08-RMANOVA.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Statistics_Lab.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
