<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Lab 4: t-Test (one-sample, paired sample) | Answering questions with data: Lab Manual</title>
  <meta name="description" content="A lab manual for Psyc 292 at StFX" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Lab 4: t-Test (one-sample, paired sample) | Answering questions with data: Lab Manual" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A lab manual for Psyc 292 at StFX" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Lab 4: t-Test (one-sample, paired sample) | Answering questions with data: Lab Manual" />
  
  <meta name="twitter:description" content="A lab manual for Psyc 292 at StFX" />
  

<meta name="author" content="Matthew J. C. Crump, Anjali Krishnan, Stephen Volz, and Alla Chavarga" />
<meta name="author" content="Adapted for PSYC 292, St. Francis Xavier University, by Erin L. Mazerolle, Sherry Neville-MacLean, Christine D. Lomore, and Margaret Vail." />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lab-3-sampling-and-sampling-distributions.html"/>
<link rel="next" href="lab-5-t-test-independent-sample.html"/>
<script src="libs/header-attrs-2.17/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-79429674-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-79429674-4');
</script>


<script type="text/javascript">
mattcrump=1;
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="tufte.css" type="text/css" />
<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics Lab Manual</a></li>

<li class="divider"></li>
<li><a href="index.html#preface" id="toc-preface">Preface</a>
<ul>
<li><a href="index.html#important-notes" id="toc-important-notes"><span class="toc-section-number">0.1</span> Important notes</a>
<ul>
<li><a href="index.html#attributions-and-versions" id="toc-attributions-and-versions"><span class="toc-section-number">0.1.1</span> Attributions and Versions</a></li>
<li><a href="index.html#cc-by-sa-4.0-license" id="toc-cc-by-sa-4.0-license"><span class="toc-section-number">0.1.2</span> CC BY-SA 4.0 license</a></li>
<li><a href="index.html#copying-the-lab-manual" id="toc-copying-the-lab-manual"><span class="toc-section-number">0.1.3</span> Copying the lab manual</a></li>
<li><a href="index.html#acknowledgments" id="toc-acknowledgments"><span class="toc-section-number">0.1.4</span> Acknowledgments</a></li>
</ul></li>
<li><a href="index.html#data" id="toc-data"><span class="toc-section-number">0.2</span> Data</a>
<ul>
<li><a href="index.html#data-repository" id="toc-data-repository"><span class="toc-section-number">0.2.1</span> Data Repository</a></li>
<li><a href="index.html#csv-format" id="toc-csv-format"><span class="toc-section-number">0.2.2</span> CSV format</a></li>
<li><a href="index.html#spss-format" id="toc-spss-format"><span class="toc-section-number">0.2.3</span> SPSS format</a></li>
</ul></li>
<li><a href="index.html#r" id="toc-r"><span class="toc-section-number">0.3</span> R</a>
<ul>
<li><a href="index.html#why-r" id="toc-why-r"><span class="toc-section-number">0.3.1</span> Why R?</a></li>
<li><a href="index.html#installing-r-and-r-studio" id="toc-installing-r-and-r-studio"><span class="toc-section-number">0.3.2</span> Installing R and R Studio</a></li>
<li><a href="index.html#r-studio-notes-and-tips" id="toc-r-studio-notes-and-tips"><span class="toc-section-number">0.3.3</span> R studio notes and tips</a></li>
<li><a href="index.html#how-to-complete-the-r-labs" id="toc-how-to-complete-the-r-labs"><span class="toc-section-number">0.3.4</span> How to complete the R Labs</a></li>
<li><a href="index.html#screencast-tutorial" id="toc-screencast-tutorial"><span class="toc-section-number">0.3.5</span> Screencast tutorial</a></li>
<li><a href="index.html#r-studio-cloud" id="toc-r-studio-cloud"><span class="toc-section-number">0.3.6</span> R-studio Cloud</a></li>
</ul></li>
<li><a href="index.html#excel" id="toc-excel"><span class="toc-section-number">0.4</span> Excel</a></li>
<li><a href="index.html#spss" id="toc-spss"><span class="toc-section-number">0.5</span> SPSS</a>
<ul>
<li><a href="index.html#installing-spss" id="toc-installing-spss"><span class="toc-section-number">0.5.1</span> Installing SPSS</a></li>
<li><a href="index.html#notes-and-tips" id="toc-notes-and-tips"><span class="toc-section-number">0.5.2</span> Notes and Tips</a></li>
<li><a href="index.html#opening-spss-and-the-spss-layout" id="toc-opening-spss-and-the-spss-layout"><span class="toc-section-number">0.5.3</span> Opening SPSS and the SPSS layout</a></li>
<li><a href="index.html#practice-problems" id="toc-practice-problems"><span class="toc-section-number">0.5.4</span> Practice Problems</a></li>
</ul></li>
<li><a href="index.html#jamovi---week-1---january-10th-11th" id="toc-jamovi---week-1---january-10th-11th"><span class="toc-section-number">0.6</span> JAMOVI - Week 1 - January 10th &amp; 11th</a>
<ul>
<li><a href="index.html#getting-started-with-jamovi" id="toc-getting-started-with-jamovi"><span class="toc-section-number">0.6.1</span> Getting Started with jamovi</a></li>
<li><a href="index.html#analyses" id="toc-analyses"><span class="toc-section-number">0.6.2</span> Analyses</a></li>
<li><a href="index.html#the-spreadsheet" id="toc-the-spreadsheet"><span class="toc-section-number">0.6.3</span> The Spreadsheet</a></li>
<li><a href="index.html#loading-data-in-jamovi" id="toc-loading-data-in-jamovi"><span class="toc-section-number">0.6.4</span> Loading Data in jamovi</a></li>
<li><a href="index.html#importing-unusual-data-files" id="toc-importing-unusual-data-files"><span class="toc-section-number">0.6.5</span> Importing Unusual Data Files</a></li>
<li><a href="index.html#changing-data-from-one-level-to-another" id="toc-changing-data-from-one-level-to-another"><span class="toc-section-number">0.6.6</span> Changing Data from One Level to Another</a></li>
<li><a href="index.html#installing-add-on-modules-into-jamovi" id="toc-installing-add-on-modules-into-jamovi"><span class="toc-section-number">0.6.7</span> Installing Add-on Modules into jamovi</a></li>
<li><a href="index.html#quitting-jamovi" id="toc-quitting-jamovi"><span class="toc-section-number">0.6.8</span> Quitting jamovi</a></li>
<li><a href="index.html#summary" id="toc-summary"><span class="toc-section-number">0.6.9</span> Summary</a></li>
</ul></li>
</ul></li>
<li><a href="lab-1-graphing-data.html#lab-1-graphing-data" id="toc-lab-1-graphing-data"><span class="toc-section-number">1</span> Lab 1: Graphing Data</a>
<ul>
<li><a href="lab-1-graphing-data.html#general-goals" id="toc-general-goals"><span class="toc-section-number">1.1</span> General Goals</a>
<ul>
<li><a href="lab-1-graphing-data.html#important-info" id="toc-important-info"><span class="toc-section-number">1.1.1</span> Important info</a></li>
</ul></li>
<li><a href="lab-1-graphing-data.html#r-1" id="toc-r-1"><span class="toc-section-number">1.2</span> R</a>
<ul>
<li><a href="lab-1-graphing-data.html#download-the-lab-templates" id="toc-download-the-lab-templates"><span class="toc-section-number">1.2.1</span> Download the lab templates</a></li>
<li><a href="lab-1-graphing-data.html#get-some-data" id="toc-get-some-data"><span class="toc-section-number">1.2.2</span> Get some data</a></li>
<li><a href="lab-1-graphing-data.html#look-at-the-data" id="toc-look-at-the-data"><span class="toc-section-number">1.2.3</span> Look at the data</a></li>
<li><a href="lab-1-graphing-data.html#make-plots-to-answer-questions" id="toc-make-plots-to-answer-questions"><span class="toc-section-number">1.2.4</span> Make Plots to answer questions</a></li>
<li><a href="lab-1-graphing-data.html#ggplot2-basics" id="toc-ggplot2-basics"><span class="toc-section-number">1.2.5</span> ggplot2 basics</a></li>
<li><a href="lab-1-graphing-data.html#more-questions-about-nyc-films" id="toc-more-questions-about-nyc-films"><span class="toc-section-number">1.2.6</span> More questions about NYC films</a></li>
<li><a href="lab-1-graphing-data.html#gapminder-data" id="toc-gapminder-data"><span class="toc-section-number">1.2.7</span> Gapminder Data</a></li>
<li><a href="lab-1-graphing-data.html#asking-questions-with-the-gap-minder-data" id="toc-asking-questions-with-the-gap-minder-data"><span class="toc-section-number">1.2.8</span> Asking Questions with the gap minder data</a></li>
<li><a href="lab-1-graphing-data.html#generalization-exercise" id="toc-generalization-exercise"><span class="toc-section-number">1.2.9</span> Generalization Exercise</a></li>
<li><a href="lab-1-graphing-data.html#writing-assignment" id="toc-writing-assignment"><span class="toc-section-number">1.2.10</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-1-graphing-data.html#excel-1" id="toc-excel-1"><span class="toc-section-number">1.3</span> Excel</a></li>
<li><a href="lab-1-graphing-data.html#spss-1" id="toc-spss-1"><span class="toc-section-number">1.4</span> SPSS</a>
<ul>
<li><a href="lab-1-graphing-data.html#opening-spss-and-the-spss-layout-1" id="toc-opening-spss-and-the-spss-layout-1"><span class="toc-section-number">1.4.1</span> Opening SPSS and the SPSS layout</a></li>
<li><a href="lab-1-graphing-data.html#reviewing-variable-properties-and-the-variable-view-tab-1" id="toc-reviewing-variable-properties-and-the-variable-view-tab-1"><span class="toc-section-number">1.4.2</span> Reviewing variable properties and the Variable View tab</a></li>
<li><a href="lab-1-graphing-data.html#opening-a-data-file-and-producing-different-types-of-graphs" id="toc-opening-a-data-file-and-producing-different-types-of-graphs"><span class="toc-section-number">1.4.3</span> Opening a data file and producing different types of graphs</a></li>
<li><a href="lab-1-graphing-data.html#homework" id="toc-homework"><span class="toc-section-number">1.4.4</span> Homework</a></li>
</ul></li>
<li><a href="lab-1-graphing-data.html#jamovi---week-7---february-28th-march-1st" id="toc-jamovi---week-7---february-28th-march-1st"><span class="toc-section-number">1.5</span> JAMOVI - Week 7 - February 28th &amp; March 1st</a>
<ul>
<li><a href="lab-1-graphing-data.html#opening-jamovi-and-reviewing-the-jamovi-layout" id="toc-opening-jamovi-and-reviewing-the-jamovi-layout"><span class="toc-section-number">1.5.1</span> Opening jamovi and reviewing the jamovi layout</a></li>
<li><a href="lab-1-graphing-data.html#reviewing-variable-properties-and-the-setup-button" id="toc-reviewing-variable-properties-and-the-setup-button"><span class="toc-section-number">1.5.2</span> Reviewing variable properties and the Setup button</a></li>
<li><a href="lab-1-graphing-data.html#importing-a-data-file" id="toc-importing-a-data-file"><span class="toc-section-number">1.5.3</span> Importing a data file</a></li>
<li><a href="lab-1-graphing-data.html#graphs" id="toc-graphs"><span class="toc-section-number">1.5.4</span> Graphs</a></li>
<li><a href="lab-1-graphing-data.html#homework-1" id="toc-homework-1"><span class="toc-section-number">1.5.5</span> Homework</a></li>
<li><a href="lab-1-graphing-data.html#thinking-about-data---practice-questions" id="toc-thinking-about-data---practice-questions"><span class="toc-section-number">1.5.6</span> Thinking about Data - Practice Questions</a></li>
</ul></li>
</ul></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#lab-2-descriptive-statistics-and-more-graphs" id="toc-lab-2-descriptive-statistics-and-more-graphs"><span class="toc-section-number">2</span> Lab 2: Descriptive Statistics (and more graphs)</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#general-goals-1" id="toc-general-goals-1"><span class="toc-section-number">2.1</span> General Goals</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#important-info-1" id="toc-important-info-1"><span class="toc-section-number">2.1.1</span> Important info</a></li>
</ul></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#r-2" id="toc-r-2"><span class="toc-section-number">2.2</span> R</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#descriptives-basics-in-r" id="toc-descriptives-basics-in-r"><span class="toc-section-number">2.2.1</span> Descriptives basics in R</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#central-tendency" id="toc-central-tendency"><span class="toc-section-number">2.2.2</span> Central Tendency</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#variation" id="toc-variation"><span class="toc-section-number">2.2.3</span> Variation</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#descriptives-by-conditions" id="toc-descriptives-by-conditions"><span class="toc-section-number">2.2.4</span> Descriptives by conditions</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#describing-gapminder" id="toc-describing-gapminder"><span class="toc-section-number">2.2.5</span> Describing gapminder</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#generalization-exercise-1" id="toc-generalization-exercise-1"><span class="toc-section-number">2.2.6</span> Generalization Exercise</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#writing-assignment-1" id="toc-writing-assignment-1"><span class="toc-section-number">2.2.7</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#excel-2" id="toc-excel-2"><span class="toc-section-number">2.3</span> Excel</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#spss-2" id="toc-spss-2"><span class="toc-section-number">2.4</span> SPSS</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#calculating-descriptive-statistics" id="toc-calculating-descriptive-statistics"><span class="toc-section-number">2.4.1</span> Calculating Descriptive Statistics</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#descriptive-statistics-and-histograms" id="toc-descriptive-statistics-and-histograms"><span class="toc-section-number">2.4.2</span> Descriptive Statistics and Histograms</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#editing-graphs" id="toc-editing-graphs"><span class="toc-section-number">2.4.3</span> Editing graphs</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#boxplots" id="toc-boxplots"><span class="toc-section-number">2.4.4</span> Boxplots</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#homework-2" id="toc-homework-2"><span class="toc-section-number">2.4.5</span> Homework</a></li>
</ul></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#jamovi---week-3---january-24th-25th" id="toc-jamovi---week-3---january-24th-25th"><span class="toc-section-number">2.5</span> JAMOVI - Week 3 - January 24th &amp; 25th</a>
<ul>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#pre-lab-tasks" id="toc-pre-lab-tasks"><span class="toc-section-number">2.5.1</span> Pre-lab tasks</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#the-basics" id="toc-the-basics"><span class="toc-section-number">2.5.2</span> The basics</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#calculating-descriptive-statistics-1" id="toc-calculating-descriptive-statistics-1"><span class="toc-section-number">2.5.3</span> Calculating Descriptive Statistics</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#descriptive-statistics-and-graphs" id="toc-descriptive-statistics-and-graphs"><span class="toc-section-number">2.5.4</span> Descriptive Statistics and Graphs</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#selecting-the-appropriate-descriptive-statistics" id="toc-selecting-the-appropriate-descriptive-statistics"><span class="toc-section-number">2.5.5</span> Selecting the appropriate descriptive statistics</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#boxplots-1" id="toc-boxplots-1"><span class="toc-section-number">2.5.6</span> Boxplots</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#editing-graphs-1" id="toc-editing-graphs-1"><span class="toc-section-number">2.5.7</span> Editing graphs</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#homework-3" id="toc-homework-3"><span class="toc-section-number">2.5.8</span> Homework</a></li>
<li><a href="lab-2-descriptive-statistics-and-more-graphs.html#practice-questions" id="toc-practice-questions"><span class="toc-section-number">2.5.9</span> Practice Questions</a></li>
</ul></li>
</ul></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#lab-3-sampling-and-sampling-distributions" id="toc-lab-3-sampling-and-sampling-distributions"><span class="toc-section-number">3</span> Lab 3: Sampling and Sampling Distributions</a>
<ul>
<li><a href="lab-3-sampling-and-sampling-distributions.html#r-3" id="toc-r-3"><span class="toc-section-number">3.1</span> R</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#excel-3" id="toc-excel-3"><span class="toc-section-number">3.2</span> Excel</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#spss-3" id="toc-spss-3"><span class="toc-section-number">3.3</span> SPSS</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#jamovi---week-7---march-8-9" id="toc-jamovi---week-7---march-8-9"><span class="toc-section-number">3.4</span> JAMOVI - Week 7 - March 8 &amp; 9</a>
<ul>
<li><a href="lab-3-sampling-and-sampling-distributions.html#learning-objectives" id="toc-learning-objectives"><span class="toc-section-number">3.4.1</span> Learning Objectives</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#pre-lab-tasks-1" id="toc-pre-lab-tasks-1"><span class="toc-section-number">3.4.2</span> Pre-lab tasks</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#the-impact-of-sampling-on-research-results" id="toc-the-impact-of-sampling-on-research-results"><span class="toc-section-number">3.4.3</span> The impact of sampling on research results</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#other-types-of-filters" id="toc-other-types-of-filters"><span class="toc-section-number">3.4.4</span> Other types of filters</a></li>
<li><a href="lab-3-sampling-and-sampling-distributions.html#homework-problems" id="toc-homework-problems"><span class="toc-section-number">3.4.5</span> Homework Problems</a></li>
</ul></li>
</ul></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#lab-4-t-test-one-sample-paired-sample" id="toc-lab-4-t-test-one-sample-paired-sample"><span class="toc-section-number">4</span> Lab 4: t-Test (one-sample, paired sample)</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#intro-material-for-r-and-spss-activities" id="toc-intro-material-for-r-and-spss-activities"><span class="toc-section-number">4.1</span> Intro material for R and SPSS activities</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#does-music-convey-social-information-to-infants" id="toc-does-music-convey-social-information-to-infants"><span class="toc-section-number">4.1.1</span> Does Music Convey Social Information to Infants?</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#lab-skills-learned" id="toc-lab-skills-learned"><span class="toc-section-number">4.1.2</span> Lab skills learned</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#important-stuff" id="toc-important-stuff"><span class="toc-section-number">4.1.3</span> Important Stuff</a></li>
</ul></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#r-4" id="toc-r-4"><span class="toc-section-number">4.2</span> R</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#loading-the-data" id="toc-loading-the-data"><span class="toc-section-number">4.2.1</span> Loading the data</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#inspect-the-data-frame" id="toc-inspect-the-data-frame"><span class="toc-section-number">4.2.2</span> Inspect the data frame</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#get-the-data-for-experiment-one" id="toc-get-the-data-for-experiment-one"><span class="toc-section-number">4.2.3</span> Get the data for Experiment one</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#baseline-phase-conduct-a-one-sample-t-test" id="toc-baseline-phase-conduct-a-one-sample-t-test"><span class="toc-section-number">4.2.4</span> Baseline phase: Conduct a one sample <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#test-phase" id="toc-test-phase"><span class="toc-section-number">4.2.5</span> Test phase</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#paired-samples-t-test" id="toc-paired-samples-t-test"><span class="toc-section-number">4.2.6</span> Paired-samples <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#graphing-the-findings" id="toc-graphing-the-findings"><span class="toc-section-number">4.2.7</span> Graphing the findings</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#data-simulation" id="toc-data-simulation"><span class="toc-section-number">4.2.8</span> Data-simulation</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#generalization-exercise-2" id="toc-generalization-exercise-2"><span class="toc-section-number">4.2.9</span> Generalization Exercise</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#writing-assignment-2" id="toc-writing-assignment-2"><span class="toc-section-number">4.2.10</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#excel-4" id="toc-excel-4"><span class="toc-section-number">4.3</span> Excel</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#spss-4" id="toc-spss-4"><span class="toc-section-number">4.4</span> SPSS</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#experiment-background" id="toc-experiment-background"><span class="toc-section-number">4.4.1</span> Experiment Background</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#optional-performing-a-one-sample-t-test" id="toc-optional-performing-a-one-sample-t-test"><span class="toc-section-number">4.4.2</span> OPTIONAL: Performing a one sample <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-paired-samples-t-test" id="toc-performing-a-paired-samples-t-test"><span class="toc-section-number">4.4.3</span> Performing a paired-samples <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#graphing-your-results" id="toc-graphing-your-results"><span class="toc-section-number">4.4.4</span> Graphing your results</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#optional-the-relationship-between-the-one-sample-and-the-paired-samples-t-test" id="toc-optional-the-relationship-between-the-one-sample-and-the-paired-samples-t-test"><span class="toc-section-number">4.4.5</span> OPTIONAL: The relationship between the one-sample and the paired-samples <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#using-descriptive-statistics-to-give-context-to-inferential-statistics" id="toc-using-descriptive-statistics-to-give-context-to-inferential-statistics"><span class="toc-section-number">4.4.6</span> Using descriptive statistics to give context to inferential statistics</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#lab-homework-6" id="toc-lab-homework-6"><span class="toc-section-number">4.4.7</span> Lab Homework #6</a></li>
</ul></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#jamovi---week-9---march-14th-15th" id="toc-jamovi---week-9---march-14th-15th"><span class="toc-section-number">4.5</span> JAMOVI - Week 9 - March 14th &amp; 15th</a>
<ul>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#learning-objectives-1" id="toc-learning-objectives-1"><span class="toc-section-number">4.5.1</span> Learning Objectives</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#pre-lab-tasks-2" id="toc-pre-lab-tasks-2"><span class="toc-section-number">4.5.2</span> Pre-lab Tasks</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#research-context-for-data-set" id="toc-research-context-for-data-set"><span class="toc-section-number">4.5.3</span> Research Context for Data Set</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-paired-samples-t-test-1" id="toc-performing-a-paired-samples-t-test-1"><span class="toc-section-number">4.5.4</span> Performing a Paired-Samples <em>t</em>-Test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#writing-results-in-apa-format" id="toc-writing-results-in-apa-format"><span class="toc-section-number">4.5.5</span> Writing results in APA format</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-one-sample-t-test" id="toc-performing-a-one-sample-t-test"><span class="toc-section-number">4.5.6</span> Performing a one-sample <em>t</em>-test</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#homework-questions" id="toc-homework-questions"><span class="toc-section-number">4.5.7</span> Homework Questions</a></li>
<li><a href="lab-4-t-test-one-sample-paired-sample.html#practice-questions-1" id="toc-practice-questions-1"><span class="toc-section-number">4.5.8</span> Practice Questions</a></li>
</ul></li>
</ul></li>
<li><a href="lab-5-t-test-independent-sample.html#lab-5-t-test-independent-sample" id="toc-lab-5-t-test-independent-sample"><span class="toc-section-number">5</span> Lab 5: <em>t</em>-test (Independent Sample)</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#do-you-come-across-as-smarter-when-people-read-what-you-say-or-hear-what-you-say" id="toc-do-you-come-across-as-smarter-when-people-read-what-you-say-or-hear-what-you-say"><span class="toc-section-number">5.1</span> Do you come across as smarter when people read what you say or hear what you say?</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#study-description-1" id="toc-study-description-1"><span class="toc-section-number">5.1.1</span> STUDY DESCRIPTION</a></li>
</ul></li>
<li><a href="lab-5-t-test-independent-sample.html#lab-skills-learned-1" id="toc-lab-skills-learned-1"><span class="toc-section-number">5.2</span> Lab skills learned</a></li>
<li><a href="lab-5-t-test-independent-sample.html#important-stuff-1" id="toc-important-stuff-1"><span class="toc-section-number">5.3</span> Important Stuff</a></li>
<li><a href="lab-5-t-test-independent-sample.html#r-5" id="toc-r-5"><span class="toc-section-number">5.4</span> R</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#load-the-data" id="toc-load-the-data"><span class="toc-section-number">5.4.1</span> Load the data</a></li>
<li><a href="lab-5-t-test-independent-sample.html#inspect-data-frame" id="toc-inspect-data-frame"><span class="toc-section-number">5.4.2</span> Inspect data frame</a></li>
<li><a href="lab-5-t-test-independent-sample.html#find-the-data-you-need" id="toc-find-the-data-you-need"><span class="toc-section-number">5.4.3</span> Find the data you need</a></li>
<li><a href="lab-5-t-test-independent-sample.html#look-at-the-dependent-variable." id="toc-look-at-the-dependent-variable."><span class="toc-section-number">5.4.4</span> Look at the dependent variable.</a></li>
<li><a href="lab-5-t-test-independent-sample.html#conduct-independent-samples-t-test" id="toc-conduct-independent-samples-t-test"><span class="toc-section-number">5.4.5</span> Conduct Independent samples <em>t</em>-test</a></li>
<li><a href="lab-5-t-test-independent-sample.html#remaining-ratings" id="toc-remaining-ratings"><span class="toc-section-number">5.4.6</span> Remaining ratings</a></li>
<li><a href="lab-5-t-test-independent-sample.html#reconstructing-the-graph-from-the-paper" id="toc-reconstructing-the-graph-from-the-paper"><span class="toc-section-number">5.4.7</span> Reconstructing the graph from the paper</a></li>
<li><a href="lab-5-t-test-independent-sample.html#generalization-exercise-3" id="toc-generalization-exercise-3"><span class="toc-section-number">5.4.8</span> Generalization Exercise</a></li>
<li><a href="lab-5-t-test-independent-sample.html#writing-assignment-3" id="toc-writing-assignment-3"><span class="toc-section-number">5.4.9</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-5-t-test-independent-sample.html#excel-5" id="toc-excel-5"><span class="toc-section-number">5.5</span> Excel</a></li>
<li><a href="lab-5-t-test-independent-sample.html#spss-5" id="toc-spss-5"><span class="toc-section-number">5.6</span> SPSS</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#experiment-background-1" id="toc-experiment-background-1"><span class="toc-section-number">5.6.1</span> Experiment Background</a></li>
<li><a href="lab-5-t-test-independent-sample.html#performing-an-independent-samples-t-test" id="toc-performing-an-independent-samples-t-test"><span class="toc-section-number">5.6.2</span> Performing an independent-samples <em>t</em>-test</a></li>
<li><a href="lab-5-t-test-independent-sample.html#graphing-your-data" id="toc-graphing-your-data"><span class="toc-section-number">5.6.3</span> Graphing your data</a></li>
<li><a href="lab-5-t-test-independent-sample.html#optional-activities" id="toc-optional-activities"><span class="toc-section-number">5.6.4</span> Optional activities</a></li>
<li><a href="lab-5-t-test-independent-sample.html#lab-homework-7" id="toc-lab-homework-7"><span class="toc-section-number">5.6.5</span> Lab Homework #7</a></li>
<li><a href="lab-5-t-test-independent-sample.html#example-answers-to-practice-problems" id="toc-example-answers-to-practice-problems"><span class="toc-section-number">5.6.6</span> Example answers to practice problems</a></li>
</ul></li>
<li><a href="lab-5-t-test-independent-sample.html#jamovi---week-9---march-21st-22nd" id="toc-jamovi---week-9---march-21st-22nd"><span class="toc-section-number">5.7</span> JAMOVI - Week 9 - March 21st &amp; 22nd</a>
<ul>
<li><a href="lab-5-t-test-independent-sample.html#pre-lab-reading-and-tasks" id="toc-pre-lab-reading-and-tasks"><span class="toc-section-number">5.7.1</span> Pre-lab reading and tasks</a></li>
<li><a href="lab-5-t-test-independent-sample.html#performing-an-independent-samples-t-test-1" id="toc-performing-an-independent-samples-t-test-1"><span class="toc-section-number">5.7.2</span> Performing an independent-samples <em>t</em>-test</a></li>
<li><a href="lab-5-t-test-independent-sample.html#some-apa-formatting-reminders-for-writing-results-sections" id="toc-some-apa-formatting-reminders-for-writing-results-sections"><span class="toc-section-number">5.7.3</span> Some APA formatting reminders for writing results sections</a></li>
<li><a href="lab-5-t-test-independent-sample.html#graphing-your-data-1" id="toc-graphing-your-data-1"><span class="toc-section-number">5.7.4</span> Graphing your data</a></li>
<li><a href="lab-5-t-test-independent-sample.html#optional-exercises" id="toc-optional-exercises"><span class="toc-section-number">5.7.5</span> Optional exercises</a></li>
<li><a href="lab-5-t-test-independent-sample.html#lab-homework-7-1" id="toc-lab-homework-7-1"><span class="toc-section-number">5.7.6</span> Lab Homework #7</a></li>
<li><a href="lab-5-t-test-independent-sample.html#practice-problems-1" id="toc-practice-problems-1"><span class="toc-section-number">5.7.7</span> Practice Problems</a></li>
</ul></li>
</ul></li>
<li><a href="lab-6-correlation.html#lab-6-correlation" id="toc-lab-6-correlation"><span class="toc-section-number">6</span> Lab 6: Correlation</a>
<ul>
<li><a href="lab-6-correlation.html#general-goals-2" id="toc-general-goals-2"><span class="toc-section-number">6.1</span> General Goals</a>
<ul>
<li><a href="lab-6-correlation.html#important-info-2" id="toc-important-info-2"><span class="toc-section-number">6.1.1</span> Important Info</a></li>
</ul></li>
<li><a href="lab-6-correlation.html#r-6" id="toc-r-6"><span class="toc-section-number">6.2</span> R</a>
<ul>
<li><a href="lab-6-correlation.html#cor-for-correlation" id="toc-cor-for-correlation"><span class="toc-section-number">6.2.1</span> cor for correlation</a></li>
<li><a href="lab-6-correlation.html#world-happiness-report" id="toc-world-happiness-report"><span class="toc-section-number">6.2.2</span> World Happiness Report</a></li>
<li><a href="lab-6-correlation.html#generalization-exercise-4" id="toc-generalization-exercise-4"><span class="toc-section-number">6.2.3</span> Generalization Exercise</a></li>
<li><a href="lab-6-correlation.html#writing-assignment-4" id="toc-writing-assignment-4"><span class="toc-section-number">6.2.4</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-6-correlation.html#excel-6" id="toc-excel-6"><span class="toc-section-number">6.3</span> Excel</a></li>
<li><a href="lab-6-correlation.html#spss-6" id="toc-spss-6"><span class="toc-section-number">6.4</span> SPSS</a>
<ul>
<li><a href="lab-6-correlation.html#correlation-coefficient-for-bivariate-data-two-variables" id="toc-correlation-coefficient-for-bivariate-data-two-variables"><span class="toc-section-number">6.4.1</span> Correlation Coefficient for Bivariate Data: Two Variables</a></li>
<li><a href="lab-6-correlation.html#correlation-matrix" id="toc-correlation-matrix"><span class="toc-section-number">6.4.2</span> Correlation Matrix</a></li>
<li><a href="lab-6-correlation.html#correlation-and-scatterplots" id="toc-correlation-and-scatterplots"><span class="toc-section-number">6.4.3</span> Correlation and Scatterplots</a></li>
<li><a href="lab-6-correlation.html#splitting-a-file" id="toc-splitting-a-file"><span class="toc-section-number">6.4.4</span> Splitting a File</a></li>
<li><a href="lab-6-correlation.html#practice-problems-2" id="toc-practice-problems-2"><span class="toc-section-number">6.4.5</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-6-correlation.html#jamovi---week-10---march-28th-29th" id="toc-jamovi---week-10---march-28th-29th"><span class="toc-section-number">6.5</span> JAMOVI - Week 10 - March 28th &amp; 29th</a>
<ul>
<li><a href="lab-6-correlation.html#pre-lab-reading-and-tasks-1" id="toc-pre-lab-reading-and-tasks-1"><span class="toc-section-number">6.5.1</span> Pre-lab reading and tasks</a></li>
<li><a href="lab-6-correlation.html#correlation-coefficient-for-bivariate-data" id="toc-correlation-coefficient-for-bivariate-data"><span class="toc-section-number">6.5.2</span> Correlation Coefficient for Bivariate Data</a></li>
<li><a href="lab-6-correlation.html#correlation-matrix-1" id="toc-correlation-matrix-1"><span class="toc-section-number">6.5.3</span> Correlation Matrix</a></li>
<li><a href="lab-6-correlation.html#apa-format-reporting-of-a-correlation" id="toc-apa-format-reporting-of-a-correlation"><span class="toc-section-number">6.5.4</span> APA format reporting of a correlation</a></li>
<li><a href="lab-6-correlation.html#correlation-and-scatterplots-1" id="toc-correlation-and-scatterplots-1"><span class="toc-section-number">6.5.5</span> Correlation and Scatterplots</a></li>
<li><a href="lab-6-correlation.html#optional-activities-1" id="toc-optional-activities-1"><span class="toc-section-number">6.5.6</span> Optional activities</a></li>
<li><a href="lab-6-correlation.html#example-answers-to-optional-activities-1" id="toc-example-answers-to-optional-activities-1"><span class="toc-section-number">6.5.7</span> Example answers to optional activities</a></li>
<li><a href="lab-6-correlation.html#homework-4" id="toc-homework-4"><span class="toc-section-number">6.5.8</span> Homework</a></li>
<li><a href="lab-6-correlation.html#practice-problems-3" id="toc-practice-problems-3"><span class="toc-section-number">6.5.9</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-6-correlation.html#jamovi-correlation-for-psyc-394-students" id="toc-jamovi-correlation-for-psyc-394-students"><span class="toc-section-number">6.6</span> JAMOVI – Correlation – FOR PSYC 394 STUDENTS</a>
<ul>
<li><a href="lab-6-correlation.html#pre-lab-reading-and-tasks-2" id="toc-pre-lab-reading-and-tasks-2"><span class="toc-section-number">6.6.1</span> Pre-lab reading and tasks</a></li>
<li><a href="lab-6-correlation.html#correlation-coefficient-for-bivariate-data-1" id="toc-correlation-coefficient-for-bivariate-data-1"><span class="toc-section-number">6.6.2</span> Correlation Coefficient for Bivariate Data</a></li>
<li><a href="lab-6-correlation.html#correlation-matrix-2" id="toc-correlation-matrix-2"><span class="toc-section-number">6.6.3</span> Correlation Matrix</a></li>
<li><a href="lab-6-correlation.html#apa-format-reporting-of-a-correlation-1" id="toc-apa-format-reporting-of-a-correlation-1"><span class="toc-section-number">6.6.4</span> APA format reporting of a correlation</a></li>
<li><a href="lab-6-correlation.html#correlation-and-scatterplots-2" id="toc-correlation-and-scatterplots-2"><span class="toc-section-number">6.6.5</span> Correlation and Scatterplots</a></li>
<li><a href="lab-6-correlation.html#optional-activities-2" id="toc-optional-activities-2"><span class="toc-section-number">6.6.6</span> Optional activities</a></li>
<li><a href="lab-6-correlation.html#example-answers-to-optional-activities-2" id="toc-example-answers-to-optional-activities-2"><span class="toc-section-number">6.6.7</span> Example answers to optional activities</a></li>
<li><a href="lab-6-correlation.html#homework-5" id="toc-homework-5"><span class="toc-section-number">6.6.8</span> Homework</a></li>
<li><a href="lab-6-correlation.html#practice-problems-4" id="toc-practice-problems-4"><span class="toc-section-number">6.6.9</span> Practice Problems</a></li>
</ul></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#lab-7-one-way-anova" id="toc-lab-7-one-way-anova"><span class="toc-section-number">7</span> Lab 7 One-way ANOVA</a>
<ul>
<li><a href="lab-7-one-way-anova.html#how-to-not-think-about-bad-memories-by-playing-tetris" id="toc-how-to-not-think-about-bad-memories-by-playing-tetris"><span class="toc-section-number">7.1</span> How to not think about bad memories by playing Tetris</a>
<ul>
<li><a href="lab-7-one-way-anova.html#study-description-2" id="toc-study-description-2"><span class="toc-section-number">7.1.1</span> STUDY DESCRIPTION</a></li>
<li><a href="lab-7-one-way-anova.html#study-methods" id="toc-study-methods"><span class="toc-section-number">7.1.2</span> Study Methods</a></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#lab-skills-learned-2" id="toc-lab-skills-learned-2"><span class="toc-section-number">7.2</span> Lab Skills Learned</a></li>
<li><a href="lab-7-one-way-anova.html#important-stuff-2" id="toc-important-stuff-2"><span class="toc-section-number">7.3</span> Important Stuff</a></li>
<li><a href="lab-7-one-way-anova.html#r-7" id="toc-r-7"><span class="toc-section-number">7.4</span> R</a>
<ul>
<li><a href="lab-7-one-way-anova.html#load-the-data-2" id="toc-load-the-data-2"><span class="toc-section-number">7.4.1</span> Load the data</a></li>
<li><a href="lab-7-one-way-anova.html#inspect-the-dataframe" id="toc-inspect-the-dataframe"><span class="toc-section-number">7.4.2</span> Inspect the dataframe</a></li>
<li><a href="lab-7-one-way-anova.html#get-the-data-you-need" id="toc-get-the-data-you-need"><span class="toc-section-number">7.4.3</span> Get the data you need</a></li>
<li><a href="lab-7-one-way-anova.html#look-at-the-data-2" id="toc-look-at-the-data-2"><span class="toc-section-number">7.4.4</span> Look at the data</a></li>
<li><a href="lab-7-one-way-anova.html#conduct-the-anova" id="toc-conduct-the-anova"><span class="toc-section-number">7.4.5</span> Conduct the ANOVA</a></li>
<li><a href="lab-7-one-way-anova.html#reporting-the-anova-results" id="toc-reporting-the-anova-results"><span class="toc-section-number">7.4.6</span> Reporting the ANOVA results</a></li>
<li><a href="lab-7-one-way-anova.html#individual-comparisons" id="toc-individual-comparisons"><span class="toc-section-number">7.4.7</span> Individual comparisons</a></li>
<li><a href="lab-7-one-way-anova.html#writing-it-all-up." id="toc-writing-it-all-up."><span class="toc-section-number">7.4.8</span> Writing it all up.</a></li>
<li><a href="lab-7-one-way-anova.html#food-for-thought" id="toc-food-for-thought"><span class="toc-section-number">7.4.9</span> Food for thought</a></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#control-vs-reactivationtetris" id="toc-control-vs-reactivationtetris"><span class="toc-section-number">7.5</span> control vs reactivation+Tetris</a></li>
<li><a href="lab-7-one-way-anova.html#tetris_only-vs-reactivationtetris" id="toc-tetris_only-vs-reactivationtetris"><span class="toc-section-number">7.6</span> Tetris_only vs reactivation+Tetris</a>
<ul>
<li><a href="lab-7-one-way-anova.html#generalization-exercise-5" id="toc-generalization-exercise-5"><span class="toc-section-number">7.6.1</span> Generalization Exercise</a></li>
<li><a href="lab-7-one-way-anova.html#writing-assignment-5" id="toc-writing-assignment-5"><span class="toc-section-number">7.6.2</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#excel-7" id="toc-excel-7"><span class="toc-section-number">7.7</span> Excel</a></li>
<li><a href="lab-7-one-way-anova.html#spss-7" id="toc-spss-7"><span class="toc-section-number">7.8</span> SPSS</a>
<ul>
<li><a href="lab-7-one-way-anova.html#experiment-background-3" id="toc-experiment-background-3"><span class="toc-section-number">7.8.1</span> Experiment Background</a></li>
<li><a href="lab-7-one-way-anova.html#performing-a-one-factor-analysis-of-variance-anova-graphing-the-data" id="toc-performing-a-one-factor-analysis-of-variance-anova-graphing-the-data"><span class="toc-section-number">7.8.2</span> Performing a One-Factor Analysis of Variance (ANOVA) &amp; Graphing the data</a></li>
<li><a href="lab-7-one-way-anova.html#follow-up-tests" id="toc-follow-up-tests"><span class="toc-section-number">7.8.3</span> Follow-Up Tests</a></li>
<li><a href="lab-7-one-way-anova.html#planned-comparisons-t-contrasts" id="toc-planned-comparisons-t-contrasts"><span class="toc-section-number">7.8.4</span> Planned Comparisons: T-Contrasts</a></li>
<li><a href="lab-7-one-way-anova.html#unplanned-comparisons-post-hoc-tests" id="toc-unplanned-comparisons-post-hoc-tests"><span class="toc-section-number">7.8.5</span> Unplanned Comparisons: <em>Post-hoc</em> tests</a></li>
<li><a href="lab-7-one-way-anova.html#other-commands-used-to-conduct-the-one-way-anova-in-spss-general-linear-model" id="toc-other-commands-used-to-conduct-the-one-way-anova-in-spss-general-linear-model"><span class="toc-section-number">7.8.6</span> Other Commands Used to Conduct the One-Way ANOVA in SPSS: General Linear Model</a></li>
<li><a href="lab-7-one-way-anova.html#homework-questions-1" id="toc-homework-questions-1"><span class="toc-section-number">7.8.7</span> Homework questions</a></li>
</ul></li>
<li><a href="lab-7-one-way-anova.html#jamovi" id="toc-jamovi"><span class="toc-section-number">7.9</span> JAMOVI</a>
<ul>
<li><a href="lab-7-one-way-anova.html#experiment-background-4" id="toc-experiment-background-4"><span class="toc-section-number">7.9.1</span> Experiment Background</a></li>
<li><a href="lab-7-one-way-anova.html#checking-assumptions" id="toc-checking-assumptions"><span class="toc-section-number">7.9.2</span> Checking Assumptions</a></li>
<li><a href="lab-7-one-way-anova.html#performing-a-one-factor-analysis-of-variance-anova-graphing-the-data-1" id="toc-performing-a-one-factor-analysis-of-variance-anova-graphing-the-data-1"><span class="toc-section-number">7.9.3</span> Performing a One-Factor Analysis of Variance (ANOVA) &amp; Graphing the data</a></li>
<li><a href="lab-7-one-way-anova.html#follow-up-tests-1" id="toc-follow-up-tests-1"><span class="toc-section-number">7.9.4</span> Follow-Up Tests</a></li>
</ul></li>
</ul></li>
<li><a href="lab-8-repeated-measures-anova.html#lab-8-repeated-measures-anova" id="toc-lab-8-repeated-measures-anova"><span class="toc-section-number">8</span> Lab 8 Repeated Measures ANOVA</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#betcha-cant-type-jhdbzkco-very-fast-on-your-first-try" id="toc-betcha-cant-type-jhdbzkco-very-fast-on-your-first-try"><span class="toc-section-number">8.1</span> Betcha can’t type JHDBZKCO very fast on your first try</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#study-description-3" id="toc-study-description-3"><span class="toc-section-number">8.1.1</span> STUDY DESCRIPTION</a></li>
<li><a href="lab-8-repeated-measures-anova.html#study-methods-1" id="toc-study-methods-1"><span class="toc-section-number">8.1.2</span> Study Methods</a></li>
</ul></li>
<li><a href="lab-8-repeated-measures-anova.html#lab-skills-learned-3" id="toc-lab-skills-learned-3"><span class="toc-section-number">8.2</span> Lab Skills Learned</a></li>
<li><a href="lab-8-repeated-measures-anova.html#important-stuff-3" id="toc-important-stuff-3"><span class="toc-section-number">8.3</span> Important Stuff</a></li>
<li><a href="lab-8-repeated-measures-anova.html#r-8" id="toc-r-8"><span class="toc-section-number">8.4</span> R</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#load-the-data-3" id="toc-load-the-data-3"><span class="toc-section-number">8.4.1</span> Load the data</a></li>
<li><a href="lab-8-repeated-measures-anova.html#inspect-the-dataframe-1" id="toc-inspect-the-dataframe-1"><span class="toc-section-number">8.4.2</span> Inspect the dataframe</a></li>
<li><a href="lab-8-repeated-measures-anova.html#get-the-data-you-need-1" id="toc-get-the-data-you-need-1"><span class="toc-section-number">8.4.3</span> Get the data you need</a></li>
<li><a href="lab-8-repeated-measures-anova.html#look-at-the-data-3" id="toc-look-at-the-data-3"><span class="toc-section-number">8.4.4</span> Look at the data</a></li>
<li><a href="lab-8-repeated-measures-anova.html#look-at-the-means" id="toc-look-at-the-means"><span class="toc-section-number">8.4.5</span> Look at the means</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-the-repeated-measures-anova" id="toc-conduct-the-repeated-measures-anova"><span class="toc-section-number">8.4.6</span> Conduct the repeated Measures ANOVA</a></li>
<li><a href="lab-8-repeated-measures-anova.html#follow-up-comparisons" id="toc-follow-up-comparisons"><span class="toc-section-number">8.4.7</span> Follow-up comparisons</a></li>
<li><a href="lab-8-repeated-measures-anova.html#reporting-everything" id="toc-reporting-everything"><span class="toc-section-number">8.4.8</span> Reporting everything</a></li>
<li><a href="lab-8-repeated-measures-anova.html#generalization-exercise-6" id="toc-generalization-exercise-6"><span class="toc-section-number">8.4.9</span> Generalization Exercise</a></li>
<li><a href="lab-8-repeated-measures-anova.html#writing-assignment-6" id="toc-writing-assignment-6"><span class="toc-section-number">8.4.10</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-8-repeated-measures-anova.html#excel-8" id="toc-excel-8"><span class="toc-section-number">8.5</span> Excel</a></li>
<li><a href="lab-8-repeated-measures-anova.html#spss-8" id="toc-spss-8"><span class="toc-section-number">8.6</span> SPSS</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#experiment-background-5" id="toc-experiment-background-5"><span class="toc-section-number">8.6.1</span> Experiment Background</a></li>
<li><a href="lab-8-repeated-measures-anova.html#produce-a-frequency-histogram-and-remove-outliers" id="toc-produce-a-frequency-histogram-and-remove-outliers"><span class="toc-section-number">8.6.2</span> Produce a frequency histogram and remove outliers</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-and-graph-one-factor-repeated-measures-anova" id="toc-conduct-and-graph-one-factor-repeated-measures-anova"><span class="toc-section-number">8.6.3</span> Conduct and graph One-Factor Repeated Measures ANOVA</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-planned-comparisons-using-a-paired-samples-t-test" id="toc-conduct-planned-comparisons-using-a-paired-samples-t-test"><span class="toc-section-number">8.6.4</span> Conduct planned comparisons using a paired-samples t-test</a></li>
<li><a href="lab-8-repeated-measures-anova.html#practice-problems-5" id="toc-practice-problems-5"><span class="toc-section-number">8.6.5</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-8-repeated-measures-anova.html#jamovi-1" id="toc-jamovi-1"><span class="toc-section-number">8.7</span> JAMOVI</a>
<ul>
<li><a href="lab-8-repeated-measures-anova.html#experiment-background-6" id="toc-experiment-background-6"><span class="toc-section-number">8.7.1</span> Experiment Background</a></li>
<li><a href="lab-8-repeated-measures-anova.html#checking-assumptions-1" id="toc-checking-assumptions-1"><span class="toc-section-number">8.7.2</span> Checking Assumptions</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-and-graph-one-factor-repeated-measures-anova-1" id="toc-conduct-and-graph-one-factor-repeated-measures-anova-1"><span class="toc-section-number">8.7.3</span> Conduct and graph One-Factor Repeated Measures ANOVA</a></li>
<li><a href="lab-8-repeated-measures-anova.html#conduct-follow-up-tests" id="toc-conduct-follow-up-tests"><span class="toc-section-number">8.7.4</span> Conduct follow-up tests</a></li>
<li><a href="lab-8-repeated-measures-anova.html#some-apa-formatting-reminders-for-writing-results-sections-2" id="toc-some-apa-formatting-reminders-for-writing-results-sections-2"><span class="toc-section-number">8.7.5</span> Some APA formatting reminders for writing results sections</a></li>
<li><a href="lab-8-repeated-measures-anova.html#homework-6" id="toc-homework-6"><span class="toc-section-number">8.7.6</span> Homework</a></li>
<li><a href="lab-8-repeated-measures-anova.html#practice-problems-6" id="toc-practice-problems-6"><span class="toc-section-number">8.7.7</span> Practice Problems</a></li>
</ul></li>
</ul></li>
<li><a href="lab-9-factorial-anova.html#lab-9-factorial-anova" id="toc-lab-9-factorial-anova"><span class="toc-section-number">9</span> Lab 9: Factorial ANOVA</a>
<ul>
<li><a href="lab-9-factorial-anova.html#does-standing-up-make-you-focus-more" id="toc-does-standing-up-make-you-focus-more"><span class="toc-section-number">9.1</span> Does standing up make you focus more?</a>
<ul>
<li><a href="lab-9-factorial-anova.html#study-description-4" id="toc-study-description-4"><span class="toc-section-number">9.1.1</span> STUDY DESCRIPTION</a></li>
<li><a href="lab-9-factorial-anova.html#study-methods-2" id="toc-study-methods-2"><span class="toc-section-number">9.1.2</span> Study Methods</a></li>
</ul></li>
<li><a href="lab-9-factorial-anova.html#lab-skills-learned-4" id="toc-lab-skills-learned-4"><span class="toc-section-number">9.2</span> Lab Skills Learned</a></li>
<li><a href="lab-9-factorial-anova.html#important-stuff-4" id="toc-important-stuff-4"><span class="toc-section-number">9.3</span> Important Stuff</a></li>
<li><a href="lab-9-factorial-anova.html#r-9" id="toc-r-9"><span class="toc-section-number">9.4</span> R</a>
<ul>
<li><a href="lab-9-factorial-anova.html#load-the-data-4" id="toc-load-the-data-4"><span class="toc-section-number">9.4.1</span> Load the data</a></li>
<li><a href="lab-9-factorial-anova.html#inspect-the-dataframe-2" id="toc-inspect-the-dataframe-2"><span class="toc-section-number">9.4.2</span> Inspect the dataframe</a></li>
<li><a href="lab-9-factorial-anova.html#get-the-data-you-need-2" id="toc-get-the-data-you-need-2"><span class="toc-section-number">9.4.3</span> Get the data you need</a></li>
<li><a href="lab-9-factorial-anova.html#get-the-data-into-the-format-you-want" id="toc-get-the-data-into-the-format-you-want"><span class="toc-section-number">9.4.4</span> Get the data into the format you want</a></li>
<li><a href="lab-9-factorial-anova.html#look-at-the-data-4" id="toc-look-at-the-data-4"><span class="toc-section-number">9.4.5</span> Look at the data</a></li>
<li><a href="lab-9-factorial-anova.html#look-at-the-means-1" id="toc-look-at-the-means-1"><span class="toc-section-number">9.4.6</span> Look at the means</a></li>
<li><a href="lab-9-factorial-anova.html#conduct-the-anova-1" id="toc-conduct-the-anova-1"><span class="toc-section-number">9.4.7</span> Conduct the ANOVA</a></li>
<li><a href="lab-9-factorial-anova.html#between-subjects-anova" id="toc-between-subjects-anova"><span class="toc-section-number">9.4.8</span> Between Subjects ANOVA</a></li>
<li><a href="lab-9-factorial-anova.html#repeated-measures-anova" id="toc-repeated-measures-anova"><span class="toc-section-number">9.4.9</span> Repeated measures ANOVA</a></li>
<li><a href="lab-9-factorial-anova.html#follow-up-comparisons-1" id="toc-follow-up-comparisons-1"><span class="toc-section-number">9.4.10</span> Follow-up comparisons</a></li>
<li><a href="lab-9-factorial-anova.html#generalization-exercise-7" id="toc-generalization-exercise-7"><span class="toc-section-number">9.4.11</span> Generalization Exercise</a></li>
<li><a href="lab-9-factorial-anova.html#writing-asignment" id="toc-writing-asignment"><span class="toc-section-number">9.4.12</span> Writing asignment</a></li>
</ul></li>
<li><a href="lab-9-factorial-anova.html#excel-9" id="toc-excel-9"><span class="toc-section-number">9.5</span> Excel</a></li>
<li><a href="lab-9-factorial-anova.html#spss-9" id="toc-spss-9"><span class="toc-section-number">9.6</span> SPSS</a>
<ul>
<li><a href="lab-9-factorial-anova.html#experiment-background-7" id="toc-experiment-background-7"><span class="toc-section-number">9.6.1</span> Experiment Background</a></li>
<li><a href="lab-9-factorial-anova.html#conduct-a-between-subjects-two-factor-analysis-of-variance-anova" id="toc-conduct-a-between-subjects-two-factor-analysis-of-variance-anova"><span class="toc-section-number">9.6.2</span> Conduct a Between-Subjects Two-Factor Analysis of Variance (ANOVA)</a></li>
<li><a href="lab-9-factorial-anova.html#calculate-simple-effects" id="toc-calculate-simple-effects"><span class="toc-section-number">9.6.3</span> Calculate simple effects</a></li>
<li><a href="lab-9-factorial-anova.html#conduct-a-repeated-measures-two-factor-analysis-of-variance-anova" id="toc-conduct-a-repeated-measures-two-factor-analysis-of-variance-anova"><span class="toc-section-number">9.6.4</span> Conduct a Repeated Measures Two-Factor Analysis of Variance (ANOVA)</a></li>
<li><a href="lab-9-factorial-anova.html#calculate-simple-effects-1" id="toc-calculate-simple-effects-1"><span class="toc-section-number">9.6.5</span> Calculate simple effects</a></li>
<li><a href="lab-9-factorial-anova.html#practice-problems-7" id="toc-practice-problems-7"><span class="toc-section-number">9.6.6</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-9-factorial-anova.html#jamovi-2" id="toc-jamovi-2"><span class="toc-section-number">9.7</span> JAMOVI</a></li>
</ul></li>
<li><a href="lab-10-mixed-factorial-anova.html#lab-10-mixed-factorial-anova" id="toc-lab-10-mixed-factorial-anova"><span class="toc-section-number">10</span> Lab 10: Mixed Factorial ANOVA</a>
<ul>
<li><a href="lab-10-mixed-factorial-anova.html#do-you-remember-things-better-when-you-take-pictures-of-them" id="toc-do-you-remember-things-better-when-you-take-pictures-of-them"><span class="toc-section-number">10.1</span> Do you remember things better when you take pictures of them?</a>
<ul>
<li><a href="lab-10-mixed-factorial-anova.html#study-description-5" id="toc-study-description-5"><span class="toc-section-number">10.1.1</span> Study description</a></li>
</ul></li>
<li><a href="lab-10-mixed-factorial-anova.html#lab-skills-learned-5" id="toc-lab-skills-learned-5"><span class="toc-section-number">10.2</span> Lab Skills Learned</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#important-stuff-5" id="toc-important-stuff-5"><span class="toc-section-number">10.3</span> Important Stuff</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#r-10" id="toc-r-10"><span class="toc-section-number">10.4</span> R</a>
<ul>
<li><a href="lab-10-mixed-factorial-anova.html#load-the-data-5" id="toc-load-the-data-5"><span class="toc-section-number">10.4.1</span> Load the data</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#inspect-the-dataframe-3" id="toc-inspect-the-dataframe-3"><span class="toc-section-number">10.4.2</span> Inspect the dataframe</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#get-the-data-you-need-3" id="toc-get-the-data-you-need-3"><span class="toc-section-number">10.4.3</span> Get the data you need</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#get-the-data-into-the-format-you-want-1" id="toc-get-the-data-into-the-format-you-want-1"><span class="toc-section-number">10.4.4</span> Get the data into the format you want</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#look-at-the-data-5" id="toc-look-at-the-data-5"><span class="toc-section-number">10.4.5</span> Look at the data</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#look-at-the-means-2" id="toc-look-at-the-means-2"><span class="toc-section-number">10.4.6</span> Look at the means</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#conduct-the-anova-2" id="toc-conduct-the-anova-2"><span class="toc-section-number">10.4.7</span> Conduct the ANOVA</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#generalization-exercise-8" id="toc-generalization-exercise-8"><span class="toc-section-number">10.4.8</span> Generalization Exercise</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#writing-assignment-7" id="toc-writing-assignment-7"><span class="toc-section-number">10.4.9</span> Writing assignment</a></li>
</ul></li>
<li><a href="lab-10-mixed-factorial-anova.html#excel-10" id="toc-excel-10"><span class="toc-section-number">10.5</span> Excel</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#spss-10" id="toc-spss-10"><span class="toc-section-number">10.6</span> SPSS</a>
<ul>
<li><a href="lab-10-mixed-factorial-anova.html#experiment-background-8" id="toc-experiment-background-8"><span class="toc-section-number">10.6.1</span> Experiment Background</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#conduct-a-mixed-factorial-analysis-of-variance-anova" id="toc-conduct-a-mixed-factorial-analysis-of-variance-anova"><span class="toc-section-number">10.6.2</span> Conduct a Mixed-Factorial Analysis of Variance (ANOVA)</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#calculate-simple-effects-2" id="toc-calculate-simple-effects-2"><span class="toc-section-number">10.6.3</span> Calculate simple effects</a></li>
<li><a href="lab-10-mixed-factorial-anova.html#practice-problems-8" id="toc-practice-problems-8"><span class="toc-section-number">10.6.4</span> Practice Problems</a></li>
</ul></li>
<li><a href="lab-10-mixed-factorial-anova.html#jamovi-3" id="toc-jamovi-3"><span class="toc-section-number">10.7</span> JAMOVI</a></li>
</ul></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#lab-11-choosing-an-appropriate-statistical-test" id="toc-lab-11-choosing-an-appropriate-statistical-test"><span class="toc-section-number">11</span> Lab 11: Choosing an appropriate statistical test</a>
<ul>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#general-goals-3" id="toc-general-goals-3"><span class="toc-section-number">11.1</span> General Goals</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#summary-of-the-tests" id="toc-summary-of-the-tests"><span class="toc-section-number">11.2</span> Summary of the tests</a>
<ul>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#pearsons-r-correlation-coefficient" id="toc-pearsons-r-correlation-coefficient"><span class="toc-section-number">11.2.1</span> Pearson’s <em>r</em> correlation coefficient</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#spearmans-r-correlation-coefficient" id="toc-spearmans-r-correlation-coefficient"><span class="toc-section-number">11.2.2</span> Spearman’s <em>r</em> correlation coefficient</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#independent-t-test" id="toc-independent-t-test"><span class="toc-section-number">11.2.3</span> Independent <em>t</em>-test</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#mann-whitney-u-test" id="toc-mann-whitney-u-test"><span class="toc-section-number">11.2.4</span> Mann-Whitney <em>U</em>-test</a></li>
</ul></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#spss-11" id="toc-spss-11"><span class="toc-section-number">11.3</span> SPSS</a>
<ul>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#pearson-and-spearman-correlation" id="toc-pearson-and-spearman-correlation"><span class="toc-section-number">11.3.1</span> Pearson and Spearman Correlation</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#independent-t-test-1" id="toc-independent-t-test-1"><span class="toc-section-number">11.3.2</span> Independent <em>t</em>-test</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#mann-whitney-u-test-1" id="toc-mann-whitney-u-test-1"><span class="toc-section-number">11.3.3</span> Mann-Whitney <em>U</em>-test</a></li>
</ul></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#homework-mar-9-and-10-2021" id="toc-homework-mar-9-and-10-2021"><span class="toc-section-number">11.4</span> Homework (Mar 9 and 10, 2021)</a></li>
<li><a href="lab-11-choosing-an-appropriate-statistical-test.html#homework-feb-23-and-24-2021" id="toc-homework-feb-23-and-24-2021"><span class="toc-section-number">11.5</span> Homework (Feb 23 and 24, 2021)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Answering questions with data: Lab Manual</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<img src="LabmanualCover.png" id="coverpic" width="350" style="display: block; margin: auto;" />
<div id="lab-4-t-test-one-sample-paired-sample" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Lab 4: t-Test (one-sample, paired sample)<a href="lab-4-t-test-one-sample-paired-sample.html#lab-4-t-test-one-sample-paired-sample" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<script>
$("#coverpic").hide();
</script>
<p><span class="newthought">
Any experiment may be regarded as forming an individual of a ‘population’ of experiments which might be performed under the same conditions. A series of experiments is a sample drawn from this population.
-William Sealy Gossett
</span></p>
<div class="marginnote">
<p>This lab is modified and extended from <a href="https://sites.trinity.edu/osl">Open Stats Labs</a>. Thanks to Open Stats Labs (Dr. Kevin P. McIntyre) for their fantastic work.</p>
</div>
<div id="intro-material-for-r-and-spss-activities" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Intro material for R and SPSS activities<a href="lab-4-t-test-one-sample-paired-sample.html#intro-material-for-r-and-spss-activities" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="does-music-convey-social-information-to-infants" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Does Music Convey Social Information to Infants?<a href="lab-4-t-test-one-sample-paired-sample.html#does-music-convey-social-information-to-infants" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This lab activity uses the open data from Experiment 1 of Mehr, Song, and Spelke (2016) to teach one-sample and paired samples <em>t</em>-tests. Results of the activity provided below should exactly reproduce the results described in the paper.</p>
<div id="study-description" class="section level4 hasAnchor" number="4.1.1.1">
<h4><span class="header-section-number">4.1.1.1</span> Study description<a href="lab-4-t-test-one-sample-paired-sample.html#study-description" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Parents often sing to their children and, even as infants, children listen to and look at their parents while they are singing. Research by Mehr, Song, and Spelke (2016) sought to explore the psychological function that music has for parents and infants, by examining the hypothesis that particular melodies convey important social information to infants. Specifically, melodies convey information about social affiliation.</p>
<p>The authors argue that melodies are shared within social groups. Whereas children growing up in one culture may be exposed to certain songs as infants (e.g., “Rock-a-bye Baby”), children growing up in other cultures (or even other groups within a culture) may be exposed to different songs. Thus, when a novel person (someone who the infant has never seen before) sings a familiar song, it may signal to the infant that this new person is a member of their social group.</p>
<p>To test this hypothesis, the researchers recruited 32 infants and their parents to complete an experiment. During their first visit to the lab, the parents were taught a new lullaby (one that neither they nor their infants had heard before). The experimenters asked the parents to sing the new lullaby to their child every day for the next 1-2 weeks.</p>
<p>Following this 1-2 week exposure period, the parents and their infant returned to the lab to complete the experimental portion of the study. Infants were first shown a screen with side-by-side videos of two unfamiliar people, each of whom were silently smiling and looking at the infant. The researchers recorded the looking behavior (or gaze) of the infants during this ‘baseline’ phase. Next, one by one, the two unfamiliar people on the screen sang either the lullaby that the parents learned or a different lullaby (that had the same lyrics and rhythm, but a different melody). Finally, the infants saw the same silent video used at baseline, and the researchers again recorded the looking behavior of the infants during this ‘test’ phase.For more details on the experiment’s methods, please refer to Mehr et al. (2016) Experiment 1.</p>
</div>
</div>
<div id="lab-skills-learned" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Lab skills learned<a href="lab-4-t-test-one-sample-paired-sample.html#lab-skills-learned" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Conducting a one-sample <em>t</em>-test</li>
<li>Conducting a paired samples <em>t</em>-test</li>
<li>Plotting the data</li>
<li>Discussing inferences and limitations</li>
</ol>
</div>
<div id="important-stuff" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Important Stuff<a href="lab-4-t-test-one-sample-paired-sample.html#important-stuff" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>citation: Mehr, S. A., Song. L. A., &amp; Spelke, E. S. (2016). For 5-month-old infants, melodies are social. Psychological Science, 27, 486-501.</li>
<li><a href="http://journals.sagepub.com/stoken/default+domain/d5HcBHg85XamSXGdYqYN/full">Link to .pdf of article</a></li>
<li><a href="https://raw.githubusercontent.com/CrumpLab/statisticsLab/master/data/MehrSongSpelke2016.csv" download>Data in .csv format</a></li>
<li><a href="https://drive.google.com/open?id=0Bz-rhZ21ShvOa3c4X3hqOWxwcUU">Data in SPSS format</a></li>
</ul>
</div>
</div>
<div id="r-4" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> R<a href="lab-4-t-test-one-sample-paired-sample.html#r-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="loading-the-data" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Loading the data<a href="lab-4-t-test-one-sample-paired-sample.html#loading-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The first thing to do is download the .csv formatted data file, using the link above, or just click <a href="https://drive.google.com/open?id=0Bz-rhZ21ShvOdW1wV0pmUTJSSk0">here</a>. It turns out there are lots of ways to load .csv files into R.</p>
<ol style="list-style-type: decimal">
<li>Load the data.table library. Then use the <code>fread</code> function and supply the web address to the file. Just like this. No downloading required.</li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb1-2" aria-hidden="true" tabindex="-1"></a>all_data <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;https://raw.githubusercontent.com/CrumpLab/statisticsLab/master/data/MehrSongSpelke2016.csv&quot;</span>)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Or, if you downloaded the .csv file. Then you can use <code>fread</code>, but you need to point it to the correct file location. The file location in this next example will not work for you, because the file is on my computer.</li>
</ol>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb2-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb2-2" aria-hidden="true" tabindex="-1"></a>all_data <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">&quot;data/MehrSongSpelke2016.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="inspect-the-data-frame" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Inspect the data frame<a href="lab-4-t-test-one-sample-paired-sample.html#inspect-the-data-frame" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When you have loaded data it’s always a good idea to check out what it looks like. You can look at all of the data in the environment tab on the top right hand corner. The data should be in a variable called <code>all_data</code>. Clicking on <code>all_data</code> will load it into a viewer, and you can scroll around. This can be helpful to see things. But, there is so much data, can be hard to know what you are looking for.</p>
<div id="summarytools-1" class="section level4 hasAnchor" number="4.2.2.1">
<h4><span class="header-section-number">4.2.2.1</span> summarytools<a href="lab-4-t-test-one-sample-paired-sample.html#summarytools-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>summarytools</code> packages give a quick way to summarize all of the data in a data frame. Here’s how. When you run this code you will see the summary in the viewer on the bottom right hand side. There’s a little browser button (arrow on top of little window) that you can click to expand and see the whole thing in a browser.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span>
<span id="cb3-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">view</span>(<span class="fu">dfSummary</span>(all_data))</span></code></pre></div>
</div>
</div>
<div id="get-the-data-for-experiment-one" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Get the data for Experiment one<a href="lab-4-t-test-one-sample-paired-sample.html#get-the-data-for-experiment-one" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The data contains all of the measurements from all five experiments in the paper. By searching through the <code>all_data</code> data frame, you should look for the variables that code for each experiment. For example, the third column is called <code>exp1</code>, which stands for experiment 1. Notice that it contains a series of 1s. If you keep scrolling down, the 1s stop. These 1s identify the rows associated with the data for Experiment 1. We only want to analyse that data. So, we need to filter our data, and put only those rows into a new variable. We do this with the <code>dplyr</code> library, using the <code>filter</code> function.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:data.table&#39;:
## 
##     between, first, last</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb9-1" aria-hidden="true" tabindex="-1"></a>experiment_one <span class="ot">&lt;-</span> all_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(exp1<span class="sc">==</span><span class="dv">1</span>)</span></code></pre></div>
<p>Now if you look at the new variable <code>experiment_one</code>, there are only 32 rows of data. Much less than before. Now we have the data from experiment 1.</p>
</div>
<div id="baseline-phase-conduct-a-one-sample-t-test" class="section level3 hasAnchor" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> Baseline phase: Conduct a one sample <em>t</em>-test<a href="lab-4-t-test-one-sample-paired-sample.html#baseline-phase-conduct-a-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You first want to show that infants’ looking behavior did not differ from chance during the baseline trial. The baseline trial was 16 seconds long. During the baseline, infants watched a video of two unfamiliar people, one of the left and one on the right. There was no sound during the baseline. Both of the actors in the video smiled directly at the infant.</p>
<p>The important question was to determine whether the infant looked more or less to either person. If they showed no preference, the infant should look at both people about 50% of the time. How could we determine whether the infant looked at both people about 50% of the time?</p>
<p>The <code>experiment_one</code> data frame has a column called <code>Baseline_Proportion_Gaze_to_Singer</code>. All of these values show how the proportion of time that the infant looked to the person who would later sing the familiar song to them. If the average of these proportion is .5 across the infants, then we would have some evidence that the infants were not biased at the beginning of the experiment. However, if the infants on average had a bias toward the singer, then the average proportion of the looking time should be different than .5.</p>
<p>Using a one-sample <em>t</em>-test, we can test the hypothesis that our sample mean for the <code>Baseline_Proportion_Gaze_to_Singer</code> was not different from .5.</p>
<p>To do this in R, we just need to isolate the column of data called <code>Baseline_Proportion_Gaze_to_Singer</code>. We will do this using the <code>$</code> operator. The <code>$</code> operator is placed after any data frame variable, and allows you to select a column of the data. The next bit of code will select the column of data we want, and put it into a new variable called <code>Baseline</code>. Note, if you type <code>exp1$</code> then R-Studio should automatically bring up all the columns you can choose from.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb10-1" aria-hidden="true" tabindex="-1"></a>baseline <span class="ot">&lt;-</span> experiment_one<span class="sc">$</span>Baseline_Proportion_Gaze_to_Singer</span></code></pre></div>
<div id="look-at-the-numbers" class="section level4 hasAnchor" number="4.2.4.1">
<h4><span class="header-section-number">4.2.4.1</span> Look at the numbers<a href="lab-4-t-test-one-sample-paired-sample.html#look-at-the-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="marginnote">
<p><strong>Question:</strong> Why is it important to look at your numbers? What could happen if you didn’t?</p>
</div>
<p>OK, we could just do the <em>t</em>-test right away, it’s really easy, only one line of code. But, we haven’t even looked at the numbers yet. Let’s at least do that. First, we’ll just use plot. It will show every data point for each infant as a dot.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(baseline)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>That’s helpful, we see that the dots are all over the place. Let’s do a histogram, so we can get a better sense of the frequency of different proportions.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(baseline)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="look-at-the-descriptives" class="section level4 hasAnchor" number="4.2.4.2">
<h4><span class="header-section-number">4.2.4.2</span> Look at the descriptives<a href="lab-4-t-test-one-sample-paired-sample.html#look-at-the-descriptives" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s get the mean and standard deviation of the sample</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(baseline)</span></code></pre></div>
<pre><code>## [1] 0.5210967</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(baseline)</span></code></pre></div>
<pre><code>## [1] 0.1769651</code></pre>
<p>OK, so just looking at the mean, we see the proportion is close to .5 (it’s .521). And, we see there is a healthy amount of variance (the dots were all over the place), as the standard deviation was about .176.</p>
<div class="marginnote">
<p><strong>Question:</strong> Based on the means and standard deviations can you make an educated guess about what the <em>t</em> and <em>p</em> values might be? Learn how to do this and you will be improving your data-sense.</p>
</div>
<p>Now, before we run the <em>t</em>-test, what do you think is going to happen? We are going to get a t-value, and an associated p-value. If you can make a guess at what those numbers would be right now in your head, and those end up being pretty close to the ones we will see in a moment, then you should pat yourself on the back. You have learned how to have intuitions about the data. As I am writing this I will tell you that 1) I can’t remember what the <em>t</em> and <em>p</em> was from the paper, and I haven’t done the test yet, so I don’t know the answer. So, I am allowed to guess what the answer will be. Here are my guesses <em>t</em>(31) = 0.2, <em>p</em> = .95. The numbers in the brackets are degrees of freedom, which we know are 31 (<em>df</em>= <em>n</em> - 1 = 32 - 1 = 31). More important than the specific numbers I am guessing (which will probably be wrong), I am guessing that the p-value will be pretty large, it will not be less than .05, which the author’s set as their alpha rate. So, I am guessing we will not reject the hypothesis that .52 is different from .5.</p>
<p>Let’s do the <em>t</em>-test and see what happens.</p>
</div>
<div id="conduct-t.test" class="section level4 hasAnchor" number="4.2.4.3">
<h4><span class="header-section-number">4.2.4.3</span> Conduct t.test<a href="lab-4-t-test-one-sample-paired-sample.html#conduct-t.test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(baseline, <span class="at">mu=</span>.<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  baseline
## t = 0.67438, df = 31, p-value = 0.5051
## alternative hypothesis: true mean is not equal to 0.5
## 95 percent confidence interval:
##  0.4572940 0.5848994
## sample estimates:
## mean of x 
## 0.5210967</code></pre>
<div class="marginnote">
<p><strong>Question:</strong> Why was the baseline condition important for the experiment? What does performance in this condition tell us?</p>
</div>
<p>So, there we have it. We did a one-sample <em>t</em>-test. Here’s how you would report it, <em>t</em>(31) = .67, <em>p</em> = .505. Or, we might say something like:</p>
<blockquote>
<p>During the baseline condition, the mean proportion looking time toward the singer was .52, and was not significantly different from .5, according to a one-sample test, <em>t</em>(31) = .67, <em>p</em> = .505.</p>
</blockquote>
<p>You should take the time to check this result, and see if it is the same one that was reported in the paper.</p>
</div>
</div>
<div id="test-phase" class="section level3 hasAnchor" number="4.2.5">
<h3><span class="header-section-number">4.2.5</span> Test phase<a href="lab-4-t-test-one-sample-paired-sample.html#test-phase" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Remember how the experiment went. Infants watched silent video recordings of two women (Baseline). Then each person sung a song, one was familiar to the infant (their parents sung the song to them many times), and one was unfamiliar (singing phase). After the singing phase, the infants watched the silent video of the two singers again (test phase). The critical question was whether the infants would look more to the person who sung the familiar song compared to the person who sun the unfamiliar song. If the infants did this, they should look more than 50% of the time to the singer who sang the familiar song. We have the data, we can do another one sample <em>t</em>-test to find out. We can re-use all the code we already wrote to do this. I’ll put it all in one place. If we run all of this code, we will see all of the things we want to see.</p>
<p>We only need to make two changes. We will change <code>experiment_one$Baseline_Proportion_Gaze_to_Singer</code> to <code>experiment_one$Test_Proportion_Gaze_to_Singer</code>, because that column has the test phase data. And, instead of putting the data into the variable <code>baseline</code>. We will make a new variable called <code>test_phase</code> to store the data.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb19-1" aria-hidden="true" tabindex="-1"></a>test_phase <span class="ot">&lt;-</span> experiment_one<span class="sc">$</span>Test_Proportion_Gaze_to_Singer</span>
<span id="cb19-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(test_phase)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(test_phase)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(test_phase)</span></code></pre></div>
<pre><code>## [1] 0.5934913</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(test_phase)</span></code></pre></div>
<pre><code>## [1] 0.1786884</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(test_phase, <span class="at">mu =</span> .<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  test_phase
## t = 2.9597, df = 31, p-value = 0.005856
## alternative hypothesis: true mean is not equal to 0.5
## 95 percent confidence interval:
##  0.5290672 0.6579153
## sample estimates:
## mean of x 
## 0.5934913</code></pre>
<div class="marginnote">
<p><strong>Question:</strong> Why was the test condition important for the experiment? What does performance in this condition tell us?</p>
</div>
<p>Alright. What did we find? You should take a stab at writing down what we found. You can use the same kind of language that I used from the first one sample-test. You should state the mean proportion, the <em>t</em>-value, the <em>df</em>s, and the <em>p</em>-value. You should be able to answer the question, did the infants look longer at the singer who sang the familiar song? And, did they look longer than would be consist with chance at 50%.</p>
</div>
<div id="paired-samples-t-test" class="section level3 hasAnchor" number="4.2.6">
<h3><span class="header-section-number">4.2.6</span> Paired-samples <em>t</em>-test<a href="lab-4-t-test-one-sample-paired-sample.html#paired-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The paired samples <em>t</em>-test is easy to do. We’ve already made two variables called <code>baseline</code>, and <code>test_phase</code>. These contain each of the infants looking time proportions to the singer for both parts of the experiment. We can see if the difference between them was likely or unlikely due to chance by running a paired samples <em>t</em>-test. We do it like this in one line:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(test_phase, baseline, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  test_phase and baseline
## t = 2.4164, df = 31, p-value = 0.02175
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.01129217 0.13349698
## sample estimates:
## mean of the differences 
##              0.07239458</code></pre>
<div class="marginnote">
<p><strong>Question:</strong> Why was the paired samples <em>t</em>-test necessary if we already did two one sample <em>t</em>-test? What new question is the paired samples <em>t</em>-test asking?</p>
</div>
<p>I’ll leave it to you to interpret these values, and to see if they are the same as the ones in the paper. Based on these values what do you conclude? Is there a difference between the mean proportion looking times for the baseline and testing phase?</p>
<div id="relationship-between-one-sample-and-paired-sample-t-test" class="section level4 hasAnchor" number="4.2.6.1">
<h4><span class="header-section-number">4.2.6.1</span> Relationship between one-sample and paired sample <em>t</em>-test<a href="lab-4-t-test-one-sample-paired-sample.html#relationship-between-one-sample-and-paired-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="marginnote">
<p><strong>Question:</strong> Why is it that a paired samples <em>t</em>-test can be the same as the one sample <em>t</em>-test? What do you have to do the data in the paired samples <em>t</em>-test in order to conduct a one-sample <em>t</em>-test that would give you the same result?</p>
</div>
<p>We’ve discussed in the textbook that the one-sample and paired sample <em>t</em>-tests are related, they can be the same test. The one-sample test is to determine whether a sample mean is different from some particular mean. The paired sample <em>t</em>-test is to determine whether one sample mean is different from another sample mean. If you take the scores for each variable in a paired samples <em>t</em>-test, and subtract them from one another, then you have one list of difference scores. Then, you could use a one sample <em>t</em>-test to test whether these difference scores are different from 0. It turns out you get the same answer from a paired sample <em>t</em>-test testing the difference between two sample means, and the one sample <em>t</em>-test testing whether the mean difference of the difference scores between the samples are different from 0. We can show this in r easily like this:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(test_phase, baseline, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  test_phase and baseline
## t = 2.4164, df = 31, p-value = 0.02175
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.01129217 0.13349698
## sample estimates:
## mean of the differences 
##              0.07239458</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb31-1" aria-hidden="true" tabindex="-1"></a>difference_scores<span class="ot">&lt;-</span>test_phase<span class="sc">-</span>baseline</span>
<span id="cb31-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(difference_scores, <span class="at">mu=</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  difference_scores
## t = 2.4164, df = 31, p-value = 0.02175
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.01129217 0.13349698
## sample estimates:
##  mean of x 
## 0.07239458</code></pre>
</div>
<div id="usefulness-of-difference-scores" class="section level4 hasAnchor" number="4.2.6.2">
<h4><span class="header-section-number">4.2.6.2</span> Usefulness of difference scores<a href="lab-4-t-test-one-sample-paired-sample.html#usefulness-of-difference-scores" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>OK fine, the paired samples <em>t</em>-test can be a one sample <em>t</em>-test if you use the difference scores. This might just seem like a mildly useful factoid you can use for stats trivia games (which no one plays). The point of drawing your attention to the relationship, is to get you to focus on the difference scores. These are what we are actually interested in.</p>
<p>Let’s use the difference scores to one more useful thing. Sometime the results of a <em>t</em>-test aren’t intuitively obvious. By the <em>t</em>-test we found out that a small difference between the test phase and baseline was not likely produced by chance. How does this relate to the research question about infants using familiar songs as cues for being social? Let’s ask a very simple question. How many infants actually showed the bias? How many infants out of 32 looked longer at the singer who sang the familiar song during test, compared to during baseline.</p>
<p>We can determine this by calculating the difference scores. Then, asking how many of them were greater than zero:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb33-1" aria-hidden="true" tabindex="-1"></a>difference_scores <span class="ot">&lt;-</span> test_phase<span class="sc">-</span>baseline</span>
<span id="cb33-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(difference_scores[difference_scores<span class="sc">&gt;</span><span class="dv">0</span>])</span></code></pre></div>
<pre><code>## [1] 22</code></pre>
<p>So, 22 out of 32 infants showed the effect. To put that in terms of probability, 68.75% of infants showed the effect. These odds and percentages give us another way to appreciate how strong the effect is. It wasn’t strong enough for all infants to show it.</p>
</div>
</div>
<div id="graphing-the-findings" class="section level3 hasAnchor" number="4.2.7">
<h3><span class="header-section-number">4.2.7</span> Graphing the findings<a href="lab-4-t-test-one-sample-paired-sample.html#graphing-the-findings" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is often useful to graph the results of our analysis. We have already looked at dot plots and histograms of the individual samples. But, we also conducted some <em>t</em>-tests on the means of the baseline and test_phase samples. One of the major questions was whether these means are different. Now, we will make a graph that shows the means for each condition. Actually, we will make a few different graphs, so that you can think about what kinds of graphs are most helpful. There are two major important things to show: 1) the sample means, and 2) a visual aid for statistical inference showing whether the results were likely due to chance.</p>
<p>We will use the ggplot2 package to make our graphs. Remember, there are two steps to take when using ggplot2. 1) put your data in a long form data frame, where each measure has one row, and 2) define the layers of the ggplot.</p>
<div id="make-the-dataframe-for-plotting" class="section level4 hasAnchor" number="4.2.7.1">
<h4><span class="header-section-number">4.2.7.1</span> Make the dataframe for plotting<a href="lab-4-t-test-one-sample-paired-sample.html#make-the-dataframe-for-plotting" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To start we will need 2 columns. One column will code the experimental phase, Baseline or Test. There are 32 observations in each phase, so we want the word <code>Baseline</code> to appear 32 times, followed by the word <code>Test</code> 32 times. Then we want a single column with each of the proportions for each infant.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb35-1" aria-hidden="true" tabindex="-1"></a>Phase <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;Baseline&quot;</span>,<span class="st">&quot;Test&quot;</span>), <span class="at">each =</span> <span class="dv">32</span>)</span>
<span id="cb35-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb35-2" aria-hidden="true" tabindex="-1"></a>Proportions <span class="ot">&lt;-</span> <span class="fu">c</span>(baseline,test_phase)</span>
<span id="cb35-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb35-3" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Phase,Proportions)</span></code></pre></div>
</div>
<div id="dot-plot-of-raw-scores" class="section level4 hasAnchor" number="4.2.7.2">
<h4><span class="header-section-number">4.2.7.2</span> Dot plot of raw scores<a href="lab-4-t-test-one-sample-paired-sample.html#dot-plot-of-raw-scores" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>This shows every scores value on the y-axis, split by the baseline and test groups. If you just looked at this, you might not think the test phase was different from the baseline phase. Still very useful to see the spread of individual scores. Supports the intuition that the scores are still kind of in a similar ballpark.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.1.2</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(<span class="at">x=</span>Phase, <span class="at">y=</span>Proportions))<span class="sc">+</span></span>
<span id="cb38-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="dot-plot-with-means-and-raw-scores" class="section level4 hasAnchor" number="4.2.7.3">
<h4><span class="header-section-number">4.2.7.3</span> Dot plot with means and raw scores<a href="lab-4-t-test-one-sample-paired-sample.html#dot-plot-with-means-and-raw-scores" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="marginnote">
<p><strong>Question:</strong> What kinds of inferences about the role of chance in producing the difference between the means can we make from this graph? What is missing?</p>
</div>
<p><code>ggplot2</code> is great because it let’s us add different layers on top of an existing plot. It would be good to see where the mean values for each sample lie on top of the sample scores. We can do this. But, to do it, we need to supply ggplot with another data frame, one that contains the means for each phase in long form. There are are only two phases, and two means, so we will make a rather small data.frame. It will have two columns, a Phase column, and Mean_value column. There will only be two rows in the data frame, one for the mean for each phase.</p>
<p>To make the smaller data frame for the means we will use the <code>aggregate</code> function. This allows us to find the means for each phase from the plot_df data frame. It also automatically returns the data frame we are looking for.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb39-1" aria-hidden="true" tabindex="-1"></a>mean_df <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Proportions <span class="sc">~</span> Phase, plot_df, mean)</span>
<span id="cb39-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(<span class="at">x=</span>Phase, <span class="at">y=</span>Proportions))<span class="sc">+</span> </span>
<span id="cb39-4"><a href="lab-4-t-test-one-sample-paired-sample.html#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb39-5"><a href="lab-4-t-test-one-sample-paired-sample.html#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>mean_df, <span class="at">color=</span><span class="st">&quot;Red&quot;</span>, <span class="at">size=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
<div id="bar-plot" class="section level4 hasAnchor" number="4.2.7.4">
<h4><span class="header-section-number">4.2.7.4</span> Bar plot<a href="lab-4-t-test-one-sample-paired-sample.html#bar-plot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>It’s very common to use bars in graphs. We can easily do this by using <code>geom_bar</code>, rather than <code>geom_point</code>. Also, we can plot bars for the means, and keep showing the dots like this…(note this will be messed up, but I want to show you why).</p>
<p>Also look for these changes.</p>
<ol style="list-style-type: decimal">
<li>added <code>stat="identity"</code> Necessary for bar plot to show specific numbers</li>
<li>added <code>aes(fill=Phase)</code> Makes each bar a different color, depending on which phase it comes from</li>
</ol>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(<span class="at">x=</span>Phase, <span class="at">y=</span>Proportions))<span class="sc">+</span> </span>
<span id="cb40-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb40-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">data=</span>mean_df, <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>,<span class="fu">aes</span>(<span class="at">fill=</span>Phase))</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>OK, we see the bars and some of the dots, but not all of them. What is going on? Remember, ggplot2 works in layers. Whatever layer you add first will be printed first in the graph, whatever layer you add second will be printed on top of the first. We put the bars on top of the dots. Let’s change the order of the layers so the dot’s go on top of the bars.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(<span class="at">x=</span>Phase, <span class="at">y=</span>Proportions))<span class="sc">+</span> </span>
<span id="cb41-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">data=</span>mean_df, <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>,<span class="fu">aes</span>(<span class="at">fill=</span>Phase))<span class="sc">+</span></span>
<span id="cb41-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
<div id="bar-plot-with-error-bars" class="section level4 hasAnchor" number="4.2.7.5">
<h4><span class="header-section-number">4.2.7.5</span> Bar plot with error bars<a href="lab-4-t-test-one-sample-paired-sample.html#bar-plot-with-error-bars" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>So far we have only plotted the means and individual sample scores. These are useful, but neither of them give us clear visual information about our statistical test. Our paired sample <em>t</em>-test suggested that the mean difference between Baseline and Test was not very likely by chance. It could have happened, but wouldn’t happen very often.</p>
<div class="marginnote">
<p><strong>Question:</strong> Why would the standard deviation of each mean, or the standard error of each mean be inappropriate to use in this case?</p>
</div>
<div class="marginnote">
<p><strong>Question:</strong> How would error bars based on the standard error of the mean differences aid in visual inference about the role of chance in producing the difference?</p>
</div>
<p>Error bars are commonly used as an aid for visual inference. The use of error bars can be a subtle nuanced issue. This is because there a different kinds of error bars that can be plotted, and each one supports different kinds of inference. In general, the error bar is supposed to represent some aspect of the variability associated with each mean. We could plot little bars that are +1 or -1 standard deviations of each mean, or we would do +1 or -1 standard errors of each mean. In the case of paired samples, neither or these error bars would be appropriate, they wouldn’t reflect the variability associated with mean we are interested in. In a paired samples <em>t</em>-test, we are interested in the variability of the mean of the difference scores. Let’s calculate the standard error of the mean (SEM) for the difference scores between Baseline and Test, and then add error bars to the plot.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-1" aria-hidden="true" tabindex="-1"></a>difference_scores <span class="ot">&lt;-</span> baseline<span class="sc">-</span>test_phase <span class="co">#calculate difference scores</span></span>
<span id="cb42-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-2" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> <span class="fu">sd</span>(difference_scores)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(difference_scores)) <span class="co">#calculate SEM</span></span>
<span id="cb42-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(<span class="at">x=</span>Phase, <span class="at">y=</span>Proportions))<span class="sc">+</span> </span>
<span id="cb42-6"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">data=</span>mean_df, <span class="at">stat=</span><span class="st">&quot;identity&quot;</span>,<span class="fu">aes</span>(<span class="at">fill=</span>Phase))<span class="sc">+</span></span>
<span id="cb42-7"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data=</span>mean_df, <span class="fu">aes</span>(<span class="at">ymin=</span>Proportions<span class="sc">-</span>standard_error, </span>
<span id="cb42-8"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-8" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">ymax=</span>Proportions<span class="sc">+</span>standard_error), <span class="at">width=</span>.<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb42-9"><a href="lab-4-t-test-one-sample-paired-sample.html#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span>.<span class="dv">25</span>)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<div class="marginnote">
<p><strong>Question:</strong> What is one reason why these error bars (standard error of the mean difference between Baseline and Test) are appropriate to use. What is one reason they are not appropriate to use?</p>
</div>
<p>We have done something that is useful for visual inference. From the textbook, we learned that differences of about 2 standard errors of the mean are near the point where we would claim that chance is unlikely to have produced the difference. This is a rough estimate. But, we can see that the top of the error bar for Baseline is lower than the bottom of the error bar for Test, resulting in a difference greater than 2 standard error bars. So, based on this graph, we might expect the difference between conditions to be significant. We can also complain about what we have done here, we are placing the same error bars from the mean difference scores onto the means for each condition. In some sense this is misleading. The error bars are not for the depicted sample means, they are for the hidden single set of difference scores. To make this more clear, we will make a bar plot with a single bar only for the differences scores.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-1" aria-hidden="true" tabindex="-1"></a>difference_scores <span class="ot">&lt;-</span> test_phase<span class="sc">-</span>baseline <span class="co">#calculate difference scores</span></span>
<span id="cb43-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-2" aria-hidden="true" tabindex="-1"></a>standard_error <span class="ot">&lt;-</span> <span class="fu">sd</span>(difference_scores)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(difference_scores)) <span class="co">#calculate SEM</span></span>
<span id="cb43-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-3" aria-hidden="true" tabindex="-1"></a>mean_difference <span class="ot">&lt;-</span> <span class="fu">mean</span>(difference_scores)</span>
<span id="cb43-4"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="at">x=</span><span class="st">&quot;MeanDifference&quot;</span>, <span class="at">y=</span>mean_difference)<span class="sc">+</span></span>
<span id="cb43-6"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">width=</span>.<span class="dv">5</span>, <span class="at">alpha=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb43-7"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>)<span class="sc">+</span></span>
<span id="cb43-8"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>difference_scores), <span class="at">alpha=</span>.<span class="dv">25</span>)<span class="sc">+</span></span>
<span id="cb43-9"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>mean_difference<span class="sc">-</span>standard_error, </span>
<span id="cb43-10"><a href="lab-4-t-test-one-sample-paired-sample.html#cb43-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">ymax=</span>mean_difference<span class="sc">+</span>standard_error), <span class="at">width=</span>.<span class="dv">1</span>)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="marginnote">
<p><strong>Question:</strong> Why is is it more appropriate to put the standard error of the difference on this bar graph? What important aspects of the original results shown in the previous graph are missing from this graph?</p>
</div>
<p>This plot is very useful, too; it gives us some new information. We can see that the mean difference (test - baseline) was greater than 0. And, we are plotting the standard error of the mean differences, which are the error bars that more formally belong to this graph. Still, we are in a position to make some guesses for visual inference. The lower error bar represents only 1 SEM. It does not cross 0, but the fact that 1 SEM does not cross zero isn’t important. For SEMs it’s usually closer to 2. We can sort of visually guesstimate that that 2 SEMs would not cross zero, which would suggest we would obtain a small p-value. We also see each of the mean difference scores. It’s very clear that they are all over the place. This means that not every infant showed a looking time preference toward the singer of the familiar song. Finally, this single bar plot misses something. It doesn’t tell us what the values of the original means were.</p>
</div>
<div id="bar-plot-with-confidence-intervals" class="section level4 hasAnchor" number="4.2.7.6">
<h4><span class="header-section-number">4.2.7.6</span> Bar plot with confidence intervals<a href="lab-4-t-test-one-sample-paired-sample.html#bar-plot-with-confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Confidence intervals are also often used for error bars, rather than the standard error (or other measure of variance). If we use 95% confidence intervals, then our error bars can be even more helpful for visual inference. Running the <code>t.test</code> function produces confidence interval estimates, and we can pull them out and use them for error bars.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-1" aria-hidden="true" tabindex="-1"></a>t_test_results <span class="ot">&lt;-</span> <span class="fu">t.test</span>(difference_scores)</span>
<span id="cb44-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-2" aria-hidden="true" tabindex="-1"></a>lower_interval<span class="ot">&lt;-</span> t_test_results<span class="sc">$</span>conf.int[<span class="dv">1</span>]</span>
<span id="cb44-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-3" aria-hidden="true" tabindex="-1"></a>upper_interval<span class="ot">&lt;-</span> t_test_results<span class="sc">$</span>conf.int[<span class="dv">2</span>]</span>
<span id="cb44-4"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="at">x=</span><span class="st">&quot;MeanDifference&quot;</span>, <span class="at">y=</span>mean_difference)<span class="sc">+</span></span>
<span id="cb44-6"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>, <span class="at">width=</span>.<span class="dv">5</span>, <span class="at">alpha=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb44-7"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>)<span class="sc">+</span></span>
<span id="cb44-8"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>difference_scores), <span class="at">alpha=</span>.<span class="dv">25</span>)<span class="sc">+</span></span>
<span id="cb44-9"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>lower_interval, </span>
<span id="cb44-10"><a href="lab-4-t-test-one-sample-paired-sample.html#cb44-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">ymax=</span>upper_interval), <span class="at">width=</span>.<span class="dv">1</span>)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Notice that the 95% confidence intervals around the mean are wider than the SEM error bars from the previous graph. These new confidence intervals tell us that 95% of the time our sample mean will fall between the two lines. The bottom line is slightly above 0, so we can now visually see support for our statistical inference that chance was unlikely to produce the result. If chance was likely to produce the result, the horizontal line indicating 0, would be well inside the confidence interval. We can also notice that the mean difference was just barely different from chance, that lower bar is almost touching 0.</p>
</div>
</div>
<div id="data-simulation" class="section level3 hasAnchor" number="4.2.8">
<h3><span class="header-section-number">4.2.8</span> Data-simulation<a href="lab-4-t-test-one-sample-paired-sample.html#data-simulation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can do a little bit of data simulation to get a better feel for this kind of data. For example, we saw that the dots in our plots were quite variable. We might wonder about what chance can do in the current experiment. One way to do this is to estimate the standard deviation of the looking time proportions. Perhaps the best way to do that would be to an average of the standard deviation in the baseline and test_phase conditions. Then, we could simulate 32 scores from a normal distribution with mean = .5, and standard deviation equaling our mean standard deviation. We could calculate the mean of our simulated sample. And, we could do this many times, say 1000 times. Then, we could look at a histogram of our means. This will show the range of sample means we would expect just by chance. This is another way to tell whether the observed difference in this experiment in the testing phase was close or not close from being produced by chance. Take a look at the histogram. What do you think?</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb45-1" aria-hidden="true" tabindex="-1"></a>sample_sd   <span class="ot">&lt;-</span> (<span class="fu">sd</span>(baseline)<span class="sc">+</span><span class="fu">sd</span>(test_phase))<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb45-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb45-3" aria-hidden="true" tabindex="-1"></a>simulated_means <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb45-4"><a href="lab-4-t-test-one-sample-paired-sample.html#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb45-5"><a href="lab-4-t-test-one-sample-paired-sample.html#cb45-5" aria-hidden="true" tabindex="-1"></a> simulated_means[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">rnorm</span>(<span class="dv">32</span>,.<span class="dv">5</span>, sample_sd))</span>
<span id="cb45-6"><a href="lab-4-t-test-one-sample-paired-sample.html#cb45-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb45-7"><a href="lab-4-t-test-one-sample-paired-sample.html#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="lab-4-t-test-one-sample-paired-sample.html#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(simulated_means)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-22-1.png" width="672" />
#### Simulating the mean differences</p>
<p>We can do the simulation slightly differently to give us a different look at chance. Above we simulated the sample means from a normal distribution centered on .5. The experimental question of interest was whether the mean difference between the baseline and test_phase condition was different. So, we should do a simulation of the difference scores. First, we estimate the standard deviation of the difference scores, and then run the simulation with a normal distribution centered on 0 (an expected mean difference of 0). This shows roughly how often we might expect mean differences of various sizes to occur. One major limitation is that we likely had only a rough estimate of the true standard deviation of these mean differences, after all there were only 32 of them, so we should take this with a grain of salt. Nevertheless, the pattern in the simulation fits well with the observations in that we already made from the data.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb46-1" aria-hidden="true" tabindex="-1"></a>sample_sd   <span class="ot">&lt;-</span> <span class="fu">sd</span>(baseline<span class="sc">-</span>test_phase)</span>
<span id="cb46-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="lab-4-t-test-one-sample-paired-sample.html#cb46-3" aria-hidden="true" tabindex="-1"></a>simulated_mean_difference <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb46-4"><a href="lab-4-t-test-one-sample-paired-sample.html#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb46-5"><a href="lab-4-t-test-one-sample-paired-sample.html#cb46-5" aria-hidden="true" tabindex="-1"></a> simulated_mean_difference[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">rnorm</span>(<span class="dv">32</span>,<span class="dv">0</span>, sample_sd))</span>
<span id="cb46-6"><a href="lab-4-t-test-one-sample-paired-sample.html#cb46-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb46-7"><a href="lab-4-t-test-one-sample-paired-sample.html#cb46-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-8"><a href="lab-4-t-test-one-sample-paired-sample.html#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(simulated_mean_difference)</span></code></pre></div>
<p><img src="Statistics_Lab_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="generalization-exercise-2" class="section level3 hasAnchor" number="4.2.9">
<h3><span class="header-section-number">4.2.9</span> Generalization Exercise<a href="lab-4-t-test-one-sample-paired-sample.html#generalization-exercise-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>( 1 point - Pass/Fail )</p>
<p>The following code creates two variables with simulated means for each of 20 subjects in two conditions (A and B). Each sample comes from a normal distribution with mean = 100, and standard deviation = 25.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="lab-4-t-test-one-sample-paired-sample.html#cb47-1" aria-hidden="true" tabindex="-1"></a>Condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>,<span class="dv">100</span>,<span class="dv">25</span>)</span>
<span id="cb47-2"><a href="lab-4-t-test-one-sample-paired-sample.html#cb47-2" aria-hidden="true" tabindex="-1"></a>Condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>,<span class="dv">100</span>,<span class="dv">25</span>)</span></code></pre></div>
<ol style="list-style-type: decimal">
<li><p>Conduct a paired samples <em>t</em>-test on sample data stored in the variables <code>Condition_A</code>, and <code>Condition_B</code>. Report the results of the <em>t</em>-test, and the mean difference between conditions</p></li>
<li><p>The above code assumes no difference in the means between Condition A and Condition B. Both samples come from the same normal distribution. Change the mean for one of the distributions. Make the change large enough so that you find a significant <em>p</em>-value (p &lt; 0.05) when you conduct the <em>t</em>-test on the new simulated data. Report the <em>t</em>-test and the means for each condition</p></li>
</ol>
</div>
<div id="writing-assignment-2" class="section level3 hasAnchor" number="4.2.10">
<h3><span class="header-section-number">4.2.10</span> Writing assignment<a href="lab-4-t-test-one-sample-paired-sample.html#writing-assignment-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>(2 points - Graded)</p>
<p>Complete the writing assignment described in your R Markdown document for this lab. When you have finished everything. Knit the document and hand in your stuff (you can submit your .RMD file to blackboard if it does not knit.)</p>
<ol style="list-style-type: decimal">
<li>Answer the following questions</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Explain the general concept of a <em>t</em>-value, and how it is different from a mean and the standard error. (.33 points)</p></li>
<li><p>Imagine you obtained a <em>t</em>-value with an associated <em>p</em>-value of .25. Explain what this means. (.33 points)</p></li>
<li><p>Imagine the critical <em>t</em>-value for a particular test was 2.6. What does the critical <em>t</em>-value mean (assuming alpha = 0.05 and the test is two-tailed). (.33 points)</p></li>
<li><p>Explain the differences between a one-sample and paired-sample <em>t</em>-test. ( 1 point )</p></li>
</ol>
<p>General grading.</p>
<ul>
<li>You will receive 0 points for missing answers</li>
<li>You must write in complete sentences. Point form sentences will be given 0 points.</li>
<li>Completely incorrect answers will receive 0 points.</li>
<li>If your answer is generally correct but very difficult to understand and unclear you may receive half points for the question</li>
</ul>
</div>
</div>
<div id="excel-4" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Excel<a href="lab-4-t-test-one-sample-paired-sample.html#excel-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How to do it in Excel</p>
</div>
<div id="spss-4" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> SPSS<a href="lab-4-t-test-one-sample-paired-sample.html#spss-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this lab, we will use SPSS to:</p>
<ol style="list-style-type: decimal">
<li>Perform a one sample <em>t</em>-test</li>
<li>Perform a paired samples <em>t</em>-test</li>
<li>Graph the data</li>
<li>Assess the relationship between a one-sample and a paired-samples <em>t</em>-test</li>
<li>Practice using descriptive statistics to give context to inferential statistics</li>
</ol>
<div id="experiment-background" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Experiment Background<a href="lab-4-t-test-one-sample-paired-sample.html#experiment-background" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this lab, we will be using the data from Mehr, Song, and Spelke’s (2016) study of how music may convey important social information to infants.</p>
<p>To test their hypothesis, the researchers recruited 32 infants and their parents to complete an experiment. During their first visit to the lab, the parents were taught a new lullaby (one that neither they nor their infants had heard before). The experimenters asked the parents to sing the new lullaby to their child every day for the next 1-2 weeks.</p>
<p>Following this exposure period, the parents and their infants returned to the lab to complete the experimental portion of the study. Infants were first shown a screen with side-by-side videos of two unfamiliar people, each of whom were silently smiling and looking at the infant. The researchers recorded the looking behavior (or gaze) of the infants during this ‘baseline’ phase. Next, one by one, the two unfamiliar people on the screen sang either the lullaby that the parents learned or a different lullaby (that had the same lyrics and rhythm, but a different melody). Finally, the infants saw the same silent video used at baseline, and the researchers again recorded the looking behavior of the infants during this ‘test’ phase.</p>
</div>
<div id="optional-performing-a-one-sample-t-test" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> OPTIONAL: Performing a one sample <em>t</em>-test<a href="lab-4-t-test-one-sample-paired-sample.html#optional-performing-a-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>First, let’s open the relevant data file. The data file has been simplified and is available on the lab Moodle page under “T-Tests.” Click on “Mehr et al. Simplified Data File” to download it, note the filename and where you’ve downloaded it to, and then open it in SPSS. Your data should look like this:</p>
<p><img src="img/6.4.11.png" /><!-- --></p>
<p>We will use SPSS to determine whether the infants looked equally at each of the people in the side-by-side videos at baseline. Let’s think about why this is important. The infants in this experiment watched silent video recordings of two women (Baseline). Later, each person in the videos sang a song, one familiar (their parents had sang the song to them many times), and one unfamiliar. Afterwards, the infants watched the silent video of the two singers again (test phase). The critical question was whether the infants would look more to the person who sang the familiar song compared to the person who sang the unfamiliar song.</p>
<p>If the measure of what infants “like” or “prefer” is based on how long they look at a stimulus (in this case, a person in a video), we need to know that at baseline (before either of the people were associated with a song), infants looked equally at each person. If one of the people in the video was more memorable or attractive to the infants, then they would have a preferential bias towards looking at one person over the other. This could mean that the results of the study may have nothing to do with the songs, but rather an inherent bias towards the appearance of one of the people. This is why it is important to ensure that the infants looked at the people equally to start with (at baseline).</p>
<p>In our data file, the variable we will use is called “Baseline_Proportion_Gaze_to_Singer”; this variable represents the proportion of time (out of 100%) that the infant spent looking at the person who would later be the singer of the familiar song. If the infant looks equally at each person, then the proportion of time spent looking at one out of the two people should be .5, or half of the time. Thus, we want to test whether the proportions measured are different from .5. Whenever we want to compare a sample data set (the proportions measured for all 32 infants) to a known mean (.5, or the proportion we expect if infants looked equally at both people), we use a one sample <em>t</em>-test.</p>
<p>In order to run the <em>t</em>-test, go to the <span style="color:blue">Analyze</span> menu, then choose <span style="color:blue">Compare Means</span> and then <span style="color:blue">One-Sample T-test</span>:</p>
<p><img src="img/6.4.14.png" /><!-- --></p>
<p>This will open up a window in which you will specify which variable contains the relevant sample data. Remember, we are interested in the variable labeled <code>Baseline_Proportion_Gaze_to_Singer</code>, so let’s choose this variable from the list on the left and move it to the right-hand field using the arrow.</p>
<p>Next, make sure to change the value in the field labeled “Test Value” to the mean to which you are comparing the sample. Since we are comparing our sample’s proportions to the proportion that represents equal time spent looking at both people in the video, we are going to use .5 as our test value. Enter this number in the appropriate field. Your window should look like this:</p>
<p><img src="img/6.4.15.png" /><!-- --></p>
<p>Now, click <span style="color:blue">OK</span>. SPSS will produce several output tables.</p>
<p><img src="img/6.4.16.png" /><!-- --></p>
<p>The first table contains descriptive statistics related to the sample. We can see from this table that the average proportion of time spent looking at the person who would later be the familiar song singer is .52. This is very close to .50.</p>
<p>The second table contains the information resulting from our <em>t</em>-test: The t-statistic calculated is .67, with 31 (N-1) degrees of freedom. The p-value is listed under “Sig. (2-tailed)”. The fact that this value is not less than our alpha level (set at .05) means we fail to reject the null hypothesis. In other words, the proportion of time infants spent looking at the singer was not different from .50. We might formally words this as follows:</p>
<p>During the baseline condition, the mean proportion looking time toward the singer was .52, and was not significantly different from .50, according to a one-sample test, <em>t</em>(31) = 0.67, <em>p</em> = .51.</p>
<p>Alternatively, you could also write:
During the baseline condition, the mean proportion looking time toward the singer was .52, and was not significantly different from .50, according to a one-sample test, <em>t</em>(31) = 0.67, <em>p</em> &gt; .05.</p>
</div>
<div id="performing-a-paired-samples-t-test" class="section level3 hasAnchor" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> Performing a paired-samples <em>t</em>-test<a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-paired-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this example, we will be comparing data from two measurements taken from the same individuals. In the same data file as above, we have two variables named <code>Baseline_Proportion_Gaze_to_Singer</code> and <code>Test_Proportion_Gaze_to_Singer</code>. These variables represent the proportion of time spent looking at the familiar song singer at baseline, and then again in the test phase (after the 1-2 week period in which infants have been familiarized with the song). Because each infant was measured once (baseline), and then re-measured again (test), we will use a paired samples <em>t</em>-test.</p>
<p><strong>Important terminology note:</strong> <code>Baseline_Proportion_Gaze_to_Singer</code> and <code>Test_Proportion_Gaze_to_Singer</code> are represented as two variables in SPSS, but they refer to two levels of a single independent variable. You can think of the independent variable as timepoint with two levels: baseline and test.</p>
<p>In order to run the paired-samples <em>t</em>-test, go to <span style="color:blue">Analyze</span>, then <span style="color:blue">Compare Means</span>, then <span style="color:blue">Paired-Samples T-test..</span>.</p>
<p><img src="img/6.4.17.png" /><!-- --></p>
<p>A window will appear with a list of all variables in a field on the left. We must choose the two variables that contain our data: <code>Baseline_Proportion_Gaze_to_Singer</code> and <code>Test_Proportion_Gaze_to_Singer</code>. Move these into the right-hand field individually using the arrow. Make sure that they appear next to each other in the right-hand field, as follows:</p>
<p><img src="img/6.4.18.png" /><!-- --></p>
<p>Click <span style="color:blue">OK</span>, and SPSS will produce several output tables. The tables are as follows:</p>
<p><img src="img/6.4.19.png" /><!-- --></p>
<p>The paired samples <em>t</em>-test produces a <em>t</em>-value (i.e., our observed <em>t</em>), degrees of freedom (N-1), and a <em>p</em>-value. You can interpret these values the same way as in the previous example.</p>
<p>During the baseline condition, the difference between infants’ mean proportion looking time toward the singer at baseline and the test phase was -0.07, and this difference was significant according to a paired samples <em>t</em>-test, t(31) = -2.42, <em>p</em> &lt; .05.</p>
</div>
<div id="graphing-your-results" class="section level3 hasAnchor" number="4.4.4">
<h3><span class="header-section-number">4.4.4</span> Graphing your results<a href="lab-4-t-test-one-sample-paired-sample.html#graphing-your-results" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In order to visualize the difference between means (for a paired-samples <em>t</em>-test, in this case), it is most appropriate to create a bar chart, or bar plot. Because our two conditions (baseline and test) make up a discrete (and not continuous) categorical variable (also called a nominal variable), a bar chart is most appropriate. Let’s begin by going to <span style="color:blue">Graphs</span>, then <span style="color:blue">Chart Builder…</span></p>
<p><img src="img/6.4.20.png" /><!-- --></p>
<p>The Chart Builder window will open and look like this:</p>
<p><img src="img/6.4.21.png" /><!-- --></p>
<p>We are going to choose a simple bar chart, which is represented by the bar icon at the top left of the set of chart options. Click on this icon and drag it into the chart window as follows:</p>
<p><img src="img/6.4.22.png" /><!-- --></p>
<p>Once you do this, your window should look like this:</p>
<p><img src="img/6.4.23.png" /><!-- --></p>
<p>From here, you must indicate which variables should be included in the chart on the y-axis. We will first take the <code>Baseline_Proportion_Gaze_to_Singer</code> variable, found in the list on the left of the window, and drag it to the y-axis in the chart window. You will see that the y-axis area will highlight with a red border when you do this.</p>
<p><img src="img/6.4.24.png" /><!-- --></p>
<p>Now, take the next variable, <code>Test_Proportion_Gaze_to_Singer</code>, and drag it over the same y-axis title, but this time aim for the very top of the variable field. You will know you’re doing it right when a red plus sign appears in this area as you hover:</p>
<p><img src="img/6.4.25.png" /><!-- --></p>
<p>Drop this variable into this field once you see the plus sign. A window will pop us asking if you want both variables on this axis. <span style="color:blue">Click OK</span>.</p>
<p><img src="img/6.4.26.png" /><!-- --></p>
<p>The result will look like this (both variables’ means, baseline and test, appear in the chart).</p>
<p><img src="img/6.4.27.png" /><!-- --></p>
<p>From here, you can customize the appearance of the graph. One thing we will do is add Error Bars. Find the window to the right of the main chart builder window, and select <span style="color:blue">Error Bars</span>. You will have the option to select Confidence Intervals, Standard Error, etc. Choose <span style="color:blue">Standard Error</span> and set the <span style="color:blue">Multiplier to 2</span>. Click <span style="color:blue">Apply</span>. Now, you should be able to see the bars in the chart builder window.</p>
<p><img src="img/6.4.29.png" /><!-- --></p>
<p>If you are satisfied with the chart, click OK and it will appear in an SPSS output window:</p>
<p><img src="img/6.4.30.png" /><!-- --></p>
</div>
<div id="optional-the-relationship-between-the-one-sample-and-the-paired-samples-t-test" class="section level3 hasAnchor" number="4.4.5">
<h3><span class="header-section-number">4.4.5</span> OPTIONAL: The relationship between the one-sample and the paired-samples <em>t</em>-test<a href="lab-4-t-test-one-sample-paired-sample.html#optional-the-relationship-between-the-one-sample-and-the-paired-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This section is dedicated to demonstrating that the one-sample and paired-samples <em>t</em>-tests are almost the very same thing. In order to understand this, we must reframe how we think about the paired-samples <em>t</em>-test. We typically consider it a comparison between two samples in which observations have been repeated (like in a before-after scenario, for example). We can also think of the paired samples <em>t</em>-test as testing the difference scores between two conditions. If the difference between two conditions is 0, then there is no difference, or there is no effect of the independent variable. If the difference is non-zero, then we can say there is a difference.</p>
<p>Thus, the paired-samples <em>t</em>-test is exactly the same as the one-sample <em>t</em>-test if we consider it as a comparison of the mean difference score to 0. Let’s demonstrate this using SPSS.</p>
<p>We’ll continue using the same data as above. Specifically, locate the variable named <code>Difference_in_Proportion_Looking</code>. This variable contains the difference score between the baseline and test conditions for each infant. We’re going to treat this as our one sample (as in the one-sample <em>t</em>-test), and we’ll be comparing it to a mean of 0.</p>
<p>Let’s begin. Go to <span style="color:blue">Analyze</span>, then <span style="color:blue">Compare Means</span>, then <span style="color:blue">One-Sample <em>t</em>-test…</span></p>
<p><img src="img/6.4.31.png" /><!-- --></p>
<p>A window will appear. Move the variable of interest, <code>Difference_in_Proportion_Looking</code>, into the “Test Variable(s)” field. Below that, make sure to enter 0 in the “Test Value” field.</p>
<p><img src="img/6.4.32.png" /><!-- --></p>
<p>Then click <span style="color:blue">OK</span>. SPSS will generate several tables in the output window. They should look like this:</p>
<p><img src="img/6.4.33.png" /><!-- --></p>
<p>You will see that the t-statistic and p-value are identical to the ones obtained when we conducted a paired-samples <em>t</em>-test. Therefore, a paired-samples <em>t</em>-test conducted on two samples is equivalent to a one-sample <em>t</em>-test conducted on the difference scores (calculated on the two samples) compared against 0.</p>
<p>Nota Bene: You will see that in the previous paired-samples <em>t</em>-test we obtained a t-statistic of -2.42, but here the t-statistic is positive. This difference comes from the fact that SPSS automatically subtracts the later-occurring variable in your spreadsheet from the earlier-occurring one. If your variables were ordered differently, you would obtain a positive t-statistic as well. In other words, the sign does not matter; it results from the order of the variables.</p>
</div>
<div id="using-descriptive-statistics-to-give-context-to-inferential-statistics" class="section level3 hasAnchor" number="4.4.6">
<h3><span class="header-section-number">4.4.6</span> Using descriptive statistics to give context to inferential statistics<a href="lab-4-t-test-one-sample-paired-sample.html#using-descriptive-statistics-to-give-context-to-inferential-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In Section 2.4.1 of the lab manual, you learned how to request descriptive statistics. If you return to the output generated by SPSS when we ran the paired-samples <em>t</em>-test, you should notice that the first table depicted in the output provides the mean, the sample size, the standard deviation, and the standard error of the mean for each measurement - Baseline_Proportion_Gaze_to_Singer and Test_Proportion_Gaze_to_Singer.</p>
<p><img src="img/6.4.34.png" /><!-- --></p>
<p>These descriptive statistics are useful for contextualizing the inferential statistics. In this case, we see that, for Baseline_Proportion_Gaze_to_Singer, the mean is 0.52 while for Test_Proportion_Gaze_to_Singer, the mean for 0.59. The standard deviation for both rounds to 0.18. In Section 6.6.3, we reported the mean difference of -0.07 was significant according to the paired-samples <em>t</em>-test. Now, we might add another sentence to explain the difference.</p>
<p>Using the means and the standard deviations for each level of the independent variable, we will generate a more detailed interpretation which includes a statement about whether there is an increase or a decrease:</p>
<p>There was a significant difference between infants’ mean proportion looking time toward the singer between the baseline (<em>M</em> = 0.52; <em>SD</em> = 0.18) and the test phase (<em>M</em> = 0.59; <em>SD</em> = 0.18). This difference was significant according to a paired samples <em>t</em>-test, <em>t</em>(31) = -2.42, <em>p</em> &lt; .05.</p>
</div>
<div id="lab-homework-6" class="section level3 hasAnchor" number="4.4.7">
<h3><span class="header-section-number">4.4.7</span> Lab Homework #6<a href="lab-4-t-test-one-sample-paired-sample.html#lab-homework-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr />
<ol style="list-style-type: decimal">
<li><p>Use the data file from this lab to test whether the number of frames the baby spent gazing at the familiar song is significantly different than the number of frames spent gazing at the unfamiliar song (use alpha = .05). Hint: If you are having trouble figuring out what variables to use, remember to check the <span style="color:blue">Label</span> column in <span style="color:blue">Variable View</span>. Complete the Moodle quiz, which will ask you about both descriptive and inferential statistics.</p></li>
<li><p>Graph this result (including 1 SEM error bars) as a bar graph. Upload your output file, including the graph, to Moodle.</p></li>
</ol>
</div>
</div>
<div id="jamovi---week-9---march-14th-15th" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> JAMOVI - Week 9 - March 14th &amp; 15th<a href="lab-4-t-test-one-sample-paired-sample.html#jamovi---week-9---march-14th-15th" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="marginnote">
<p>This lab activity was developed by Erin Mazerolle, Christine Lomore, and Sherry Neville-MacLean.</p>
</div>
<div id="learning-objectives-1" class="section level3 hasAnchor" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Learning Objectives<a href="lab-4-t-test-one-sample-paired-sample.html#learning-objectives-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this lab, we will use jamovi to:</p>
<ol style="list-style-type: decimal">
<li>Perform a paired-sample <em>t</em>-test (an inferential statistic)</li>
<li>Use descriptive statistics and graphs to give context to inferential statistics</li>
<li>Report a paired-sample <em>t</em>-test in APA format</li>
<li>Perform a one-sample <em>t</em>-test</li>
</ol>
</div>
<div id="pre-lab-tasks-2" class="section level3 hasAnchor" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Pre-lab Tasks<a href="lab-4-t-test-one-sample-paired-sample.html#pre-lab-tasks-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before lab, be sure to complete the <a href="https://moodle.stfx.ca/mod/quiz/view.php?id=837148">Psychology 291 Data: Terms of Use quiz</a>.</p>
<p>When you pass that quiz, download the data file and data dictionary from <a href="https://moodle.stfx.ca/mod/url/view.php?id=837149">OneDrive</a>. Be sure to practice your data management skills and save the files in an appropriate file folder in your Psych 292 Lab folder.</p>
<p>This week we will be importing a different file format. The data file in OneDrive is a .sav file. Be sure to use the import function in JAMOVI instead of open. We did some testing and this seems to work better for more versions of JAMOVI. Be sure to have the data file opened in JAMOVI before your lab begins.</p>
</div>
<div id="research-context-for-data-set" class="section level3 hasAnchor" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> Research Context for Data Set<a href="lab-4-t-test-one-sample-paired-sample.html#research-context-for-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The data set with which we will be working is from an online survey. Participants were students in a 200-level, Research Methods in Psychology course. They responded to questions about anxiety, stress, sleep, self-care, and substance use. We are using a subset of the data from the survey for this lab.</p>
<p>The survey was delivered to the same class of students twice during the semester - once early in the term and once immediately after the course midterm. The person who constructed the data file used T1_ and T2_ before variable names to denote whether the data came from the beginning of the term (T1) or immediately after the midterm (T2).</p>
</div>
<div id="performing-a-paired-samples-t-test-1" class="section level3 hasAnchor" number="4.5.4">
<h3><span class="header-section-number">4.5.4</span> Performing a Paired-Samples <em>t</em>-Test<a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-paired-samples-t-test-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="motivation-to-perform-statistical-analyses" class="section level4 hasAnchor" number="4.5.4.1">
<h4><span class="header-section-number">4.5.4.1</span> Motivation to perform statistical analyses<a href="lab-4-t-test-one-sample-paired-sample.html#motivation-to-perform-statistical-analyses" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Imagine you are a researcher who is interested in how midterms impact students’ sleep patterns. You are curious about whether the number of nightly sleep hours changes during midterm time. You plan to use the survey data described above to answer your question.</p>
<p>First, what is your research question?</p>
<p>Possible research question: Do the number of hours of sleep change during midterms?</p>
<p>Note that this is just one possible research question. You might also ask a directional question. Consider the following example: Do the number of hours of sleep decrease during midterms? We will use the non-directional research question for now.</p>
</div>
<div id="using-descriptive-statistics-to-look-at-the-question" class="section level4 hasAnchor" number="4.5.4.2">
<h4><span class="header-section-number">4.5.4.2</span> Using descriptive statistics to look at the question<a href="lab-4-t-test-one-sample-paired-sample.html#using-descriptive-statistics-to-look-at-the-question" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>What might you do to answer this question? You can use some JAMOVI skills we’ve already learned to explore the differences in sleep duration between the two timepoints: descriptive statistics! graphing! You should recall the commands used to request <a href="https://www.erinmazerolle.com/statisticsLab/lab-2-descriptive-statistics-and-more-graphs.html#jamovi---week-4---february-8-9">descriptive statistics</a> and <a href="https://www.erinmazerolle.com/statisticsLab/lab-1-graphing-data.html#jamovi---week-3---february-1-2">graphs</a> from previous chapters. Let’s make those requests now.</p>
<p><img src="img/SleepHours_Descriptives.png" /><!-- --></p>
<p><img src="img/T1_SleepHours_Histogram.png" /><!-- --></p>
<p><img src="img/T2_SleepHours_Histogram.png" /><!-- --></p>
<p>Stretch your Thinking: Why do the histograms look high-low-high-low?</p>
<p>(Answer: because people tend to write/remember whole hours, so those values occur more frequently in the data).</p>
</div>
<div id="motivation-to-perform-inferential-statistics" class="section level4 hasAnchor" number="4.5.4.3">
<h4><span class="header-section-number">4.5.4.3</span> Motivation to perform inferential statistics<a href="lab-4-t-test-one-sample-paired-sample.html#motivation-to-perform-inferential-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Having looked at the descriptive statistics and graphs, we see differences between the sleep scores at the two timepoints. It looks like the mean sleep duration is slightly lower during midterms, compared to the beginning of term. But, how confident are we that that the means are truly different? That is, do the differences between these timepoints represent true differences in the sleep of students between the beginning of term and midterms? Or, could the differences explained by sampling error?</p>
<p>Remember: Each sample is different. If you repeated these surveys with a different sample, would you expect to get the same results? (Answer: <strong>No.</strong>) Do the differences between timepoints exist in the population of all students? That is what inferential statistics will help us decide.</p>
<p>We use a paired-samples <em>t</em>-test in this case because the data are paired. The survey was completed by the same participants at both time points. Paired-samples <em>t</em>-tests are also known as paired <em>t</em>-tests, matched <em>t</em>-tests, and dependent <em>t</em>-tests.</p>
<p>First, we need to set up our null and alternative hypotheses. Remember our research question: Does sleep change during midterms?
So, our null hypothesis (<span class="math inline">\(H_0\)</span>) is there is no difference in sleep between the two timepoints: <span class="math inline">\(\mu_{T1}\)</span> = <span class="math inline">\(\mu_{T2}\)</span>.
Our alternative hypothesis (<span class="math inline">\(H_A\)</span> or <span class="math inline">\(H_1\)</span>) is there is a difference: <span class="math inline">\(\mu_{T1}\)</span> <span class="math inline">\(\neq\)</span> <span class="math inline">\(\mu_{T2}\)</span>.</p>
<p>Question: Why are our hypotheses about the mean, as opposed to a different measure of central tendency, or the distributions? Answer: <em>t</em>-tests answer questions about means. Other tests can be used for research questions about different statistics.</p>
</div>
<div id="using-jamovi-to-request-the-paired-samples-t-test" class="section level4 hasAnchor" number="4.5.4.4">
<h4><span class="header-section-number">4.5.4.4</span> Using JAMOVI to request the paired-samples <em>t</em>-test<a href="lab-4-t-test-one-sample-paired-sample.html#using-jamovi-to-request-the-paired-samples-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>You can find the paired <em>t</em>-tests in JAMOVI by clicking Analyses -&gt; T-Tests, Paired Samples T-Test:</p>
<p><img src="img/paired_menu.png" /><!-- --></p>
<p>Move your two variables of interest to “Paired Variables”:</p>
<p><img src="img/select_vars_pairedttest.png" /><!-- --></p>
<p>Under Tests, “Student’s” should be selected (Student was the pseudonym of the person who invented the t-test). Also, make sure Measure 1 <span class="math inline">\(\neq\)</span> Measure 2 under Hypothesis (because we have a non-directional hypothesis for this example):</p>
<p><img src="img/paired_ttest_params1.png" /><!-- --></p>
<p>Under Additional Statistics, select Mean difference and under that, Confidence Interval. Select Effect size. You can also select Descriptives and Descriptive Plots:</p>
<p><img src="img/paired_ttest_params2.png" /><!-- --></p>
<p>There will now be some output in the JAMOVI output panel. The first table is Paired Samples T-Test. It names the variables that were used in the test (T1_sleep_hours and T2_sleep hours), gives the Student’s t-value (under the statistic column), the degrees of freedom (df), the p-value (p), the mean difference, the standard error (SE) of the difference, the 95% Confidence Interval lower and upper bounds, and Cohen’s <em>d</em> (under the Effect size column). This table is quite wide, so we’ve split it into two below:</p>
<p><img src="img/pairedttestoutput_1.png" /><!-- --></p>
<p><img src="img/pairedttestoutput_2.png" /><!-- --></p>
<p>The Descriptives table gives some descriptive statistics, which is convenient for writing up your results:</p>
<p><img src="img/paireddescriptives.png" /><!-- --></p>
<p>Compare these descriptive statistics to the ones we generated earlier via the Exploration function. Why are they different? We’ll answer this question below.</p>
<p>The plot includes both the mean and the median of both variables. The mean has “whiskers” that represent the 95% confidence interval. You can think of this plot as a bar graph, without the bars:</p>
<p><img src="img/pairedplot.png" /><!-- --></p>
<p><strong>Tip</strong>: If you would like to make a bar graph corresponding to a paired <em>t</em>-test, it’s a bit tricky in JAMOVI. We recommend using Excel to plot your means. Usually, the standard errors (SE), which can be found in the Descriptives table, are a good choice for your error bars.</p>
</div>
<div id="interpreting-the-paired-samples-t-test-output" class="section level4 hasAnchor" number="4.5.4.5">
<h4><span class="header-section-number">4.5.4.5</span> Interpreting the Paired Samples <em>t</em>-Test output<a href="lab-4-t-test-one-sample-paired-sample.html#interpreting-the-paired-samples-t-test-output" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>What output do you look at to determine the answer to your research question (Does sleep change during midterms?)? The Paired Samples T-Test table has two particularly important numbers, the <em>p</em>-value (in this case, 0.009) and the effect size (in this case, 0.308). The p-value is the probability of observing a difference, as or more extreme than the one you observed, assuming the null hypothesis is true (that is, assuming that sleep duration at time is the same as sleep duration at time 2). In this case, the probability is 0.009, or 0.9%, which is very low. How do you decide if your p-value is “low enough”? We typically use a cutoff, called an alpha, of 0.05 or 5%. If your p-value is lower than your alpha value, we conclude that it is very unlikely that the null hypothesis is true. We often call this rejecting the null hypothesis. In this case, 0.009 &lt; 0.05, so we reject the null hypothesis. Note that we do not accept the alternative hypothesis!</p>
<p>In research papers, we often use the phrase “statistically significant” or “significantly different” to mean reject the null hypothesis. For example, we observed significantly different sleep durations at time 1 versus time 2.</p>
<p>The effect size gives us a sense for how large the difference is. Cohen’s <em>d</em> is the appropriate effect size for a <em>t</em>-test, but we will learn about effect sizes for other tests as the course progresses. Cohen’s <em>d</em> tells us how large the mean difference is, in units of standard deviation. In this case, Cohen’s <em>d</em> is 0.308, so the difference in sleep duration between time 1 and time 2 is about 0.3 standard deviations.</p>
<p>The degrees of freedom (df) for a paired <em>t</em>-test is equal to the number of participants included in the test minus one:
<span class="math inline">\(df = N - 1\)</span></p>
<div class="marginnote">
<p>Note: Different tests use different formulas for df.</p>
</div>
<p>Our df = 76, meaning that 77 participants were included in the paired <em>t</em>-test. There are actually 103 participants in the dataset, but not all participants had sleep duration data for both time points. Participants with missing data at one or both timepoints get excluded from the test. This is why the descriptives statistics are different depending on whether you generate them via the Exploration panel or the Paired T-Test. The Exploration descriptives table includes all participants with data, whereas the Paired T-Test descriptives table only includes participants with data at both time points.</p>
<p>The 95% confidence interval for a paired <em>t</em>-test are limits constructed that, for 95% of samples, the population mean difference will fall within the limits. This means that, assuming our sample belongs to that 95% of samples, the population mean difference is between 0.101 and 0.670. Remember, if we collected the data again using a different sample, we would get a different estimate for the population mean.</p>
</div>
</div>
<div id="writing-results-in-apa-format" class="section level3 hasAnchor" number="4.5.5">
<h3><span class="header-section-number">4.5.5</span> Writing results in APA format<a href="lab-4-t-test-one-sample-paired-sample.html#writing-results-in-apa-format" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can write sentences in APA format to describe our results. Such sentences are what you tend to see in Results sections of research papers. For the paired <em>t</em>-test example above, we would write a sentence such as:</p>
<p>Using a paired <em>t</em>-test, we observed a significant difference in sleep duration between the beginning of term and midterms (<em>t</em>(76) = 2.70, <em>p</em> = .009, <em>d</em> = 0.31). Mean (standard deviation) sleep duration at the beginning of term was 7.03 (1.14) hours, dropping to 6.64 (1.30) hours at midterms. The mean difference was 0.39 hours (95% CI [0.10, 0.67]).</p>
<p>Can you find where all the numbers in the sentence came from in the two tables?</p>
<p>A few notes about APA format:</p>
<ol style="list-style-type: decimal">
<li><p>Always note the name of the test you performed (in this case, paired <em>t</em>-test).</p></li>
<li><p>We usually round to two decimal places, except for <em>p</em>-values.</p></li>
<li><p>Do not include a leading 0 before the decimal for the <em>p</em>-value (<em>p</em> = .009 not <em>p</em> = 0.009)</p></li>
</ol>
<div class="marginnote">
<p>Yes, I’m serious. No, I don’t know why. Yes, it does seem a bit silly. Yes, you lose points if you don’t adhere to APA format when requested to do so.</p>
</div>
<ol start="4" style="list-style-type: decimal">
<li><p>Pay attention to spaces, parentheses, etc. APA is very picky about that. For example, it’s <em>t</em>(76) = 2.70 <strong>not</strong> <em>t</em>(76)=2.70.</p></li>
<li><p>Symbols such as <em>M</em>, <em>SD</em>, <em>t</em>, <em>p</em>, and <em>d</em> are italicized.</p></li>
</ol>
</div>
<div id="performing-a-one-sample-t-test" class="section level3 hasAnchor" number="4.5.6">
<h3><span class="header-section-number">4.5.6</span> Performing a one-sample <em>t</em>-test<a href="lab-4-t-test-one-sample-paired-sample.html#performing-a-one-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sometimes you are interested in whether a sample’s mean is different from a specific value. For example, you might wonder whether students are getting 8 hours of sleep per night at the start of term. To ask this question, we use a one-sample <em>t</em>-test:</p>
<p><img src="img/onesample.png" /><!-- --></p>
<p>Move your variable of interest (T1_sleep_hours) into the Dependent Variables box.</p>
<p>Under hypothesis, be sure to set your test value to 8. If you leave it at 0, it will test whether the mean sleep duration is equal to 0. So, your null hypothesis is that sleep duration at the start of term is equal to 8 hours, i.e., <span class="math inline">\(H_0: \mu = 8\)</span></p>
<p>Your output will look like this:</p>
<p><img src="img/onesampleoutput.png" /><!-- --></p>
<p>The <em>p</em>-value is less than .05, so we reject our null hypothesis. Sleep duration is significantly different from 8 hours per night at the beginning of term.</p>
<p>You can also add the outputs we included for the paired <em>t</em>-test, including mean difference, confidence interval, descriptives, and descriptive plots.</p>
</div>
<div id="homework-questions" class="section level3 hasAnchor" number="4.5.7">
<h3><span class="header-section-number">4.5.7</span> Homework Questions<a href="lab-4-t-test-one-sample-paired-sample.html#homework-questions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>See Moodle.</p>
</div>
<div id="practice-questions-1" class="section level3 hasAnchor" number="4.5.8">
<h3><span class="header-section-number">4.5.8</span> Practice Questions<a href="lab-4-t-test-one-sample-paired-sample.html#practice-questions-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Canada’s Healthy Drinking Guidelines suggest that women should consume “no more than 2 standard drinks on most days and no more than 10 drinks per week.” Using the data collected in PSYC 291, select only those participants who identify as cisgender women (hint: review lab manual section on <a href="https://www.erinmazerolle.com/statisticsLab/lab-3-sampling-and-sampling-distributions.html#other-types-of-filters">filters</a>). Compare the number of drinks women in PSYC 291 consumed in the week prior to Time 1 (September) to the healthy drinking standard. Conduct the appropriate <em>t</em>-test. What can you conclude? Write your answer in APA format, including the 95% confidence interval, and effect size (Cohen’s <em>d</em>).</p></li>
<li><p>Is there a significant difference in cannabis use between the beginning of term versus midterms? Report your results in APA format.</p></li>
<li><p>Consider the sleep duration example. Use JAMOVI to perform a directional test, such that the alternative hypothesis is that sleep duration at the beginning of term is longer than sleep duration at midterms. Compare your results to the non-directional test. What are the similarities and what are the differences?</p></li>
<li><p>Does it matter in what order you input the variables for the paired <em>t</em>-test? Why or why not? If you aren’t sure, given it a try!</p></li>
</ol>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lab-3-sampling-and-sampling-distributions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lab-5-t-test-independent-sample.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/CrumpLab/statisticsLab/blob/master/04-tTest1.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Statistics_Lab.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
